INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(1481, 'FLORADA BRASIL ARMAZENS GERAIS', 'FLORADA BRASIL ARMAZENS GERAIS', 
'RODOVIA CANDIDO PORTINARI', 'S/N', NULL, 
NULL, 'FRANCA', NULL, 
'SP', '14406-081', '(16) 3720-1307', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '13.442.415/0001-67', NULL, 
'310.289.423.119', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1345, 'FM-ARMAZENS GERAIS LTDA', 'FM-ARMAZENS GERAIS LTDA', 
'Rua Rivalino Antonio Barros', '20', 'Sao Sebastiao da Estrela', 
NULL, 'Santo Antonio do Amparo', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '10.478.416/0001-73', NULL, 
'001.099.622-0020', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1719, 'FUNCHAL ARMAZENS GERAIS LTDA', 'FUNCHAL  ARMAZEM GERAIS', 
'ROD MG 235 KM 89,921', 'S/N', NULL, 
'ZONA RURAL', 'SAO GOTARDO', NULL, 
NULL, '38800000', '34 3671 6116', 
NULL, NULL, NULL, 
'ARMAZENS@GRUPOFUNCHAL.COM.BR', NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '66.398.298/0004-90', NULL, 
'621.774339.0390', true, 9, 
9, NULL, NULL, 
NULL, NULL),
(706, 'G.P.I. ARMAZENS GERAIS LTDA', 'G.P.I', 
'ROD. SP. 346 KM 202', NULL, NULL, 
NULL, 'ESP. STO. DO PINHAL', 'ESP. STO. DO PINHAL', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
NULL, '02.816.871/0001-03', NULL, 
'530.032.100-114', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(716, 'GUILHERME JOSE REHDER', 'GUILHERME', 
'FAZ. BARREIRO REHDER - ROD. SÃO JOÃO/AGUAI- SP 344', 'KM 216,5', NULL, 
NULL, 'AGUAI', 'AGUAI', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'AR', 'AR', NULL, 
'QUALICAFEX', 'CNPJ08196949/0001-10', '270.948.048-49', 
'152082230110', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(72, 'ICATU COMERCIO EXP. E IMPORT. LTDA', NULL, 
'Rodovia MG 290 s/n KM 55', NULL, NULL, 
NULL, 'OURO FINO', NULL, 
'MG', NULL, '(19) 6511551', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'AR', NULL, 
NULL, '24.896.409/0001-04', NULL, 
'647.030.846.0096', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(121, 'INCOFEX   ARMAZEM  GERAIS LTDA', NULL, 
'ROD. VIÇOSA - PORTO FIRME', 'KM 4', NULL, 
NULL, 'VIÇOSA', 'VIÇOSA', 
'MG', '36.570-000', '(31) 8919559', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO: REGINALDO', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(254, 'INTERNACIONAL - ARMAZÉNS GERAIS', 'INTERNACIONAL', 
'AV. PRESIDENTE WENCESLAU BRAZ', '2600B', NULL, 
NULL, 'POÇOS DE CALDAS', NULL, 
'MG', '37.706-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '02.218.866/0001-07', NULL, 
'518.724.144.0069', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(39, 'IRMAOS PEREIRA COM. EXP. IMP. CAFE LTDA', NULL, 
'ROD.SP 346', 'KM 202', NULL, 
NULL, 'ESP. SANTO DO P', 'ESP. SANTO DO P', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '54.228.093/0001-35', NULL, 
'530.002.423.119', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1874, 'JOSÉ MARIA DE OLIVEIRA', 'JOSÉ MARIA DE OLIVEIRA', 
'Fazenda Santa Luzia', NULL, NULL, 
NULL, 'Campos Altos', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CL', 'AR', NULL, 
'cafeeiragalvao@hotmail.com
administrativo@cafecamposaltos.com.br', NULL, '195.570.356-68', 
'001141444.00-90', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1702, 'JULIO CESAR SA SILVERA RAMOS', 'JULIO CESAR SA SILVERA RAMOS', 
'Rua Manoel Barra da Silva', '255', NULL, 
NULL, 'Patrocinio', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '01.939.995/0001-13', '481.718.615-0068', 
NULL, true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1037, 'Kaffehuseti Karlstad AB', NULL, 
'Tolagsgatan 1', NULL, NULL, 
NULL, 'Karlstad', 'Sweden', 
NULL, 'SE 652 22', NULL, 
NULL, NULL, NULL, 
NULL, '\u0015M�\u000efۜ��{\u0015z\u001f�<7i�y��d��������9�oOE\u0018Q�\\��\u001d_T��5\rkK���\u0018 ����K\u001c��P��\u0000���ۙ$''����\u001f\u00165�\u001ejz����Z�� Y���2�\u0006�la��\u001fC^̺���O�)&� \u0017.;\u0004f*������\b�\\�\f\u001e\u0018�=�c��-�c�P�zp�d\/*�͆�|\u001c������i�;潝!�\r\u000b���fu�\u0014�\u0000\u0000\u001e�t���II��o#53�O��:����WS��ͥՍ��+��E��n�\u0007�ھz�I�mw��c��\u0005�0�\u0005��[�X�!�����q�~o�\u000eT�S�\/\u0019x���\r<}�_j�}��ݭ�N\u0016��t;����n\u000e�s?�O����p��\u0000BJ�X~JU9�@�v����\u001d�\u0000��K\/\u001a�', 'J', 
'CL', 'AR', NULL, 
'Kaffehuset i Karlstad  AB
Tolagsgatan 1
SE 652 22 Karlstad
Sweden

P.O. Box 1501
SE 651 21 Karlstad
Sweden



Bank Instructions received on July 15th, 2009:

Bank name: Handelsbanken 
Adress: Tingvallagatan 17, Box 497 
             651 11 Karlstad 
             Sweden', NULL, NULL, 
NULL, false, NULL, 
3, '����\u0000\u0010JFIF\u0000\u0001\u0001\u0001\u0000`\u0000`\u0000\u0000��\u0000C\u0000\u0006\u0004\u0005\u0006\u0005\u0004\u0006\u0006\u0005\u0006\u0007\u0007\u0006\b\n\u0010\n\n\t\t\n\u0014\u000e\u000f\f\u0010\u0017\u0014\u0018\u0018\u0017\u0014\u0016\u0016\u001a\u001d%\u001f\u001a\u001b#\u001c\u0016\u0016', NULL, 
NULL, false),
(1040, 'KAFFIBRENNSLA AKUREYRAR HF', 'KEA ICELAND', 
'TRYGGVABRAUT, 16IS - 600', NULL, NULL, 
NULL, 'AKUREYRIICELAND', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1815, 'LCP ARMAZENS GERAIS LTDA', 'LCP ARMAZENS GERAIS LTDA', 
'AV:  VEREADOR GERALDO TEODORO DA SILVA', '1001', NULL, 
NULL, 'ARAGUARI', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'AR', NULL, 
NULL, '10.616.500/0001-06', NULL, 
'001.107.882-0023', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(38, 'LEME ARMAZENS GERAIS LTDA', 'LEME', 
'VIA AHANGUERA', 'KM 186,5', NULL, 
NULL, 'LEME', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '66.089.418/0001-25', NULL, 
'415.038.624.112', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1636, 'Liv Logística Armazens Gerais LTDA', 'Liv Logística Armazens Gerais LTDA', 
'ROD. BR-491 VARGINHA-TRÊS CORAÇÕES - KM 16 - S/N', NULL, NULL, 
NULL, 'Varginha', NULL, 
'MG', '37062-195', '(35)3219-1239', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '21.977.425/0001-25', NULL, 
'002518650.00-54', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1732, 'LOUIS DREYFUS COMPANY BRASIL S.A', 'LOUIS DREYUS  AG', 
'RODOVIA MG 852 ,', 'S/N', NULL, 
'N SENHORA  DO ROSARIO', 'MATIPO', 'BRASIL', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '47 067 525/0204-86', NULL, 
NULL, true, 9, 
9, NULL, NULL, 
NULL, NULL),
(752, 'MANTIQUEIRA ARMAZENS GERAIS LTDA', 'MANT', 
'AV. JOÃO PINHEIRO', '6410', NULL, 
'BORTOLAN', 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
NULL, '17.605.627/0001-79', NULL, 
'518.390.286.0086', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1240, 'MARCELO PEREIRA DA SILVA', 'MARCELO PEREIRA DA SILVA', 
'FAZENDA SÃO BENTO', NULL, NULL, 
NULL, 'CAJURU', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CL', 'AR', NULL, 
NULL, '08.344.175/0001-28', '113.334.298-19', 
'243.071.142.113', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1577, 'MARIMBONDO ARMAZENS GERAIS LTDA', 'MARIMBONDO ARMAZENS GERAIS LTDA', 
'Av. Flavio da Silva Tavera,', '10', NULL, 
'Campos Verdes', 'Campos Altos', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '28.263.706/0001-65', NULL, 
'00301110800.00-53', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1468, 'Mazza Armazens Gerais', 'Mazza Armazens Gerais', 
'Rua Maria de Simone Prosperi', '65', 'Chacara Bom Jardim', 
NULL, 'Guaxupe', 'Brasil', 
'MG', '37.800-000', '(35)3551-0501', 
NULL, NULL, NULL, 
'mazzaag@hotmail.com', NULL, 'J', 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, 8, 
8, NULL, NULL, 
NULL, NULL),
(1765, 'MCC ARMAZENS GERAIS LTDA', 'MCC ARMAZENS GERAIS LTDA', 
'ROD. BR 491', NULL, NULL, 
NULL, 'TRES CORACOES', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '18.705.971/0001-00', NULL, 
'0039460940072', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1764, 'MCC SPECIALTY COFFEE EXPORTADORA LTDA', 'MCC SPECIALTY COFFEE EXPORTADORA LTDA', 
'ROD. BR 491', NULL, NULL, 
NULL, 'TRES CORACOES', NULL, 
'MG', '37066-800', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', 'logistica@mangacoffee.com.br
qualidade@mangacoffee.com.br', 
'MANGA', '20.694.905/0001-16', NULL, 
'002398525.00-49', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(129, 'MINAS COFFEE ARMAZENS GERAIS LTDA', NULL, 
'AV. ANANIAS LUIZ AVELAR', '53', NULL, 
NULL, 'SANTO ANTONIO D', 'SANTO ANTONIO D', 
'MG', NULL, '(35) 8631304', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO: EVANDRO', '19.308.410/0001-22', NULL, 
'599.228.980.0066', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1395, 'MONTECCER ARMAZENS', 'MONTECCER', 
'ROD. MG 190 KM 3.9 - S/N', NULL, NULL, 
NULL, 'MONTE CARMELO', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, 2, 
2, NULL, NULL, 
NULL, NULL),
(120, 'MUZAMBINHO ARMAZENS GERAIS', NULL, 
'AV. VER.DR.ANT.VERISSIMO DA COSTA', '1220', NULL, 
NULL, 'MUZAMBINHO', 'MUZAMBINHO', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '24.001.802/0001-84', NULL, 
'441.570.823.0020', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1823, 'NM JR EMPREENDIMENTOS, COM, PARTI LTDA', 'NM', 
'RODOVIA RONAN ROCHA KM 13', 'S/N', NULL, 
NULL, 'PATROCINIO PAULISTA', NULL, 
'SP', '14415-00', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, 2, 
2, NULL, NULL, 
NULL, NULL),
(86, 'NOVA AMERICA ARMAZENS GERAIS LTDA', NULL, 
'RUA DR. JOSE MAMBRINI', '605', NULL, 
'VILA HELENA', 'SAO SEBASTIAO D', 'SAO SEBASTIAO D', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '00.426.485/0001-80', NULL, 
'647.981.274.0018', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1296, 'P&B ARMAZENS GERAIS LTDA', 'P&B ARMAZENS GERAIS LTDA', 
'Avenida  Sebastiao Lima Campos', '341', NULL, 
NULL, 'Campos Altos', NULL, 
'MG', '38.970-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1829, 'PASSARO ARMAZENS GERAIS LTDA', 'PASSARO ARMAZENS GERAIS LTDA', 
'Rodovia BR 491, S/N Km 04', NULL, NULL, 
NULL, 'Varinha', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '32.689.883/0001-85', NULL, 
'33732660036', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1734, 'PHV ARMAZENS GERAIS LTDA', 'PHV ARMAZENS GERAIS LTDA', 
'Av. Bela Vista', '81', 'anexo a', 
'JB', 'Carmo do Paranaiba', NULL, 
'MG', '38840-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '22.619.217/0004-60', NULL, 
'0029227680055', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1378, 'PRINCIPADO ARMAZENS GERAIS LTDA', 'PRINCIPADO', 
'Rod. BR 265 Km 063', 's/n', 'Zona Rural', 
NULL, 'Boa Esperança', NULL, 
'MG', '37.170-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, 2, 
2, NULL, NULL, 
NULL, NULL),
(886, 'QUOTA MILLE COMÉRCIO EXPORTAÇÃO E IMPORTAÇÃO LTDA', 'QUOTA', 
'RUA JOAQUIM DE ARAÚJO ALMEIDA, S/N', NULL, NULL, 
NULL, 'SERRA NEGRA', 'SERRA NEGRA', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'SARA LEE', '71.968.739/0001-30', NULL, 
'662.019.340.110', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(920, 'QUOTAMILLE COMERCIO EXP. E IMP. LTDA', 'QUOTTA', 
'RUA JOAQUIM ARAUJO ALMEIDA', 'S/N', NULL, 
NULL, NULL, NULL, 
NULL, NULL, '19-3892-1355', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(888, 'R.C. ARMAZÉNS GERAIS LTDA', 'RC', 
'RODOVIA MG 29 ,', '95', NULL, 
NULL, 'ARAGUARI', 'ARAGUARI', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
NULL, '07.886.593/0001-84', NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(138, 'RICAFÉ ARMAZÉNS GERAIS LTDA', NULL, 
'RUA MANOEL MADEIRA', '67', NULL, 
NULL, 'VARGINHA', 'VARGINHA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '27.994.979/0006-21', NULL, 
'707.408.988.0000', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(937, 'SAAG - Sociedade de Armazenamento e Agricultura Ltda.', 'SAAG', 
'Rod. BR 265, KM 412', 'S/N', NULL, 
NULL, 'Santana da Vargem', NULL, 
'MG', '37196-000', '(35) 3858-1291', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'AR', NULL, 
'SAAG Sociedade de Armazenamento e Agricultura Ltda
Rod. BR 265, KM 408
CEP: 37196-000
(35) 3858-1291
Santana da Vargem / MG', '02.181.142/0001-28', NULL, 
'583.718.990-0006', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(963, 'SANTA CLARA IMOVEIS,ARMAZENS GERAIS E SERVIÇOS LTD', 'ARM', 
'RUA TRÊS', '410', NULL, 
'CLAUDIO G. NOGUEIRA', 'VARGINHA', 'VARGINHA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
NULL, '06.189.718/0005-88', NULL, 
'001.091.150.0367', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(451, 'SANTO ANTONIO REBENEFICIADORA E ARMAZENS GERAIS S/', 'STO. ANTONIO', 
'AV. ANANIAS LUIS AVELAR', '53', NULL, 
'CENTRO', 'STO ANT. AMPARO', 'STO ANT. AMPARO', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO: EVANDRO', '04.434.663/0001-75', NULL, 
'599.134.695.0032', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(113, 'SARA LEE CAFÉS DO BRASIL LTDA', 'SARA LEE', 
'AV. CAFE DO POTNO', '479', NULL, 
NULL, 'BARUERI', 'BARUERI', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '02.333.707/0001-45', NULL, 
'206.007.782.111', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1854, 'SJS ARMAZENS GERAIS LTDA', 'SJS', 
'Rua Antonio Moreira Maia', '205', NULL, 
NULL, 'Campo Belo', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '22.941.388/0001-68', NULL, 
'002.599.648.0018', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1580, 'SUPER SAFRA ARMAZENS GERAIS LTDA', 'SUPER SAFRA ARMAZENS GERAIS LTDA', 
'RUA SÃO VICENTE', '510', NULL, 
NULL, 'CONCEICAO APARECIDA', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '04.492.438/0001-95', NULL, 
'171.130.883-0054', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1834, 'TABATINGA COMERCIO DE CAFE LTDA', 'CAFE TABATINGA  ARMAZEM', 
'RUA PADRE JOAQUIM CARDOSO', '668', NULL, 
'CENTRO', 'SAO FRANCISCO DE PAULA', 'BRAZIL', 
'MG', '35543000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'AR', NULL, 
NULL, '34.875 218/0002-92', NULL, 
NULL, NULL, 9, 
9, NULL, NULL, 
NULL, NULL),
(468, 'TELECAFÉ ARMAZÉM GERAIS LTDA', 'TELECAFE', 
'AV. FARIA PEREIRA', '4022', NULL, 
NULL, 'PATROCINIO', 'PATROCINIO', 
'MG', NULL, '(34) 38313434', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '41.935.580/0001-15', NULL, 
'481.803.990.0098', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(75, 'TELECAFE ARMAZENS GERAIS', NULL, 
'AV. FARIA PEREIRA', '4022', NULL, 
NULL, 'PATROCINIO', 'PATROCINIO', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '41.935.560/0001-15', NULL, 
'481.803.990.0098', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1591, 'TERRANOVA ARMAZENS GERAIS LTDA', 'TERRANOVA', 
'RUA CAETANO LEONE', '597', NULL, 
'JARDIM SANTA INES', 'MONTE SANTO DE MINAS', 'BRASIL', 
'MG', '37968-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', 'CONTATO: EMANUEL', 
NULL, '33.625.325/0001-19', NULL, 
'00.344.541.800-40', true, 9, 
2, NULL, NULL, 
NULL, NULL),
(974, 'Teste', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CL', 'AR', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
7, NULL, NULL, 
NULL, NULL),
(1157, 'TRES CORAÇOES IMOVEIS ARMAZENS GERAIS E SERVIÇOS LTDA.', NULL, 
'RUA  ZOROASTRO HENRIQUE AMORIM', '410', 'DISTRITO INDUSTRIAL', 
'CLAUDIO GALVÃO NOGUEIRA', 'VARGINHA', 'BRASIL', 
'MG', '37066-415', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '06.189.718/0005-88', NULL, 
'001091150.03-67', true, 9, 
9, NULL, NULL, 
NULL, NULL),
(1241, 'Três Irmãos Armazéns Gerais - TRIAG', 'Três Irmãos Armazéns Gerais - TRIAG', 
'Alameda Altino Ozório de Oliveira', '809', 'Dist.Industrial', 
NULL, 'Altinopolis', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '06.149.576/0001-00', NULL, 
'159.063.923.110', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(274, 'TRISCAFÉ DE ARMAZENS GERAIS LTDA', 'GRO', 
'AV. JOSÉ RIBEIRO TRISTÃO', '505', NULL, 
NULL, 'VARGINHA', 'VARGINHA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO: TRISTÃO', '28.134.443/0016-70', NULL, 
'707.221.177.0135', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1631, 'UBIRAJARA ARMAZENS GERAIS', 'UBIRAJARA ARMAZENS GERAIS', 
'Avenida Vereador Joao Alegre', '677', NULL, 
NULL, 'Campos Altos', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '07.691.238/0001-50', NULL, 
'115.426.753.0020', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(14, 'UNICAFE - EMPRESA DE ARMAZENS GERAIS', 'UNICAFE', 
'AV. PRINCESA DO SUL', '2025', NULL, 
NULL, 'VARGINHA', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'AR', 'AR', NULL, 
'CONTATO:', '28.154.698/0011-90', NULL, 
'707.579.360.0052', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(1258, 'VERDES GRAOS E ARMAZENS GERAIS LTDA', 'VERDES GRAOS', 
'Rua Olinto Lamounier', '280', NULL, 
NULL, 'Candeias', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'AR', NULL, 
NULL, '09.325.276/0001-14', NULL, 
'001.156.369.0004', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1663, '.Al Wazzan Trading Corporation', 'Al Wazzan Trading Corporation', 
'Baghdad Street, Wazzan Building', NULL, 'Latakia - Syria', 
NULL, 'P.O BOX: 2952', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Buyer address:
Al Wazzan Trading Corporation
BAGHDAD STREET
WAZZAN BUILDING
P.O BOX: 2952
LATAKIA - SYRIA

contact: Mr. Nabil Rifaai

Baghdad Street, Wazzan Building', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(1671, '.BANO GIDA ITHALAT VE IHRACAT SANAYI VE TICARET LIMITED SIRKETI.', 'BANO GIDA', 
'Incilipinar Mah. 36011 Nolu SK. No.14/39', NULL, NULL, 
NULL, 'V.D. Gazikent V.No.1400654796', 'Sehitkamil/Gaziantep, Turkey', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'BANO GIDA ITHALAT VE IHRACAT SANAYI VE TICARET LIMITED SIRKETI 
Incilipinar Mah. 36011 Nolu SK. No.14/39
V. D. Gazikent V. No. 1400654796
Sehitkamil/Gaziantep, Turkey', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(1704, '.BASEL AL-KURDI', 'BASEL AL-KURDI', 
'Al-Furkan', NULL, 'Syriatel Street,                  Sarmini Building', 
NULL, 'Aleppo, Syria', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'info@nrifaai.com', 'J', 
'RE', 'CO', NULL, 
'BASEL AL-KURDI
Al-Furkan 
Syriatel Street, Sarmini Building
Aleppo, Syria

Broker:
Nabil Rifaai Co.
Hamra Street, Opposite Blue Tower,

PSS info 10/09/2020:
Tom, 17:01 skype
pode alterar so uma coisa por favor
PSS approval com Wolthers
mas daqui pra frente, todos os contratos do Nabil, 
PSS com Wolthers.', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1662, '.HASeeb CO.', 'HASEEB CO.', 
'Ali Midan Korneeah', NULL, 'Haseeb Building, 1st Floor', 
NULL, 'Damascus, Syria', NULL, 
NULL, NULL, '9631147373201', 
NULL, NULL, NULL, 
NULL, 'info@nrifaai.com', 'J', 
'CL', 'CO', NULL, 
'Broker:

Nabil Rifaai Co.
Hamra Street, Opposite Blue Tower,
Hallal Building, 3rd Floor, Office No.7
Damascus - Syria
Mr. Nabil Rifaai

HASEEB CO.
Al Midan Korneeah
Haseeb Building, 1st Floor
Damascus - Syria
TEL/FAX : 009631147373201

PSS info 10/09/2020:
Tom, 17:01 skype
pode alterar so uma coisa por favor
PSS approval com Wolthers
mas daqui pra frente, todos os contratos do Nabil, 
PSS com Wolthers.', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1676, '.Loyal Agro Company Gida Maddeleri Insaat Malz. Temiz. Malze. Tekstil Kimy.', 'Loyal Agro Company', 
'Guzeller Commercial Centre 5232 nº 1/2nd floor', 'nº 1/2nd floor', NULL, 
'Jamisherif region, Akdeniz', NULL, 'Mersin, Turkey', 
NULL, '33060', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', 'Profile Updated: June 18, 2020', 
'Headquarters:
Guzeller Is Mrk Kat:2/5 No: 1 
Camiserif Mahallesi 5232 Sokak Akdeniz
Mersin; Mediterranean; Postal Code: 33010


Buyer address:
Loyal Agro Company Gida Maddeleri Insaat Malz. Temiz. Malze. Tekstil Kimy., Nabil
Jamisherif region, 
Guzeller Commercial Centre 5232 - Nº 1 - 2nd floor / 5, 
Akdeniz - Mersin -Turkey
Postal Code: 33060', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(1703, '.Mohamad Refaieh', 'Mohamad Refaieh', 
'Yalda, Main Street', NULL, NULL, 
NULL, 'Rif Damascus, Syria', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'info@nrifaai.com', 'F', 
'RE', 'CO', NULL, 
'Mohamad Refaieh
Yalda, Main Street
Rif Damascus, Syria

Broker:

Nabil Rifaai Co.
Hamra Street, Opposite Blue Tower,

PSS info 10/09/2020:
Tom, 17:01 skype
pode alterar so uma coisa por favor
PSS approval com Wolthers
mas daqui pra frente, todos os contratos do Nabil, 
PSS com Wolthers.', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1705, '.Mohammed Ghazal Son Mohammed Rabee', 'Mohammed Ghazal Son Mohammed Rabee', 
'Al Oruba Street', NULL, 'Trough Harash', 
NULL, 'Latakia, Syria', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'Mohammed Ghazal Son Mohammed Rabee
Al Oruba Street
Trough Harash
Latakia - Syria


Broker:

Nabil Rifaai Co.
Hamra Street, Opposite Blue Tower,

PSS info 10/09/2020:
Tom, 17:01 skype
pode alterar so uma coisa por favor
PSS approval com Wolthers
mas daqui pra frente, todos os contratos do Nabil, 
PSS com Wolthers.', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1670, '.ZENOGLU BILGISAYAR ELEKTRONIK GIDA URUN, OTOMOTIV VE TEKSTIL IÇ VE DIS TIC. LTD.', 'ZENOGLU BILGISAYAR ELEKTRONIK', 
'Incilipinar Mah. 36011 Nolu Sok.', NULL, 'No:147 Gazikent V. D. 997 070 4121', 
NULL, 'Sehitkamil/Gaziantep, Turkey', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'Incilipinar Mah. 36011 Nolu Sok. 
No:147 Gazikent V.  D.  997 070 4121
Sehitkamil/Gaziantep 50830, Turkey', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(1212, '32CUP N.V.', '32CUP', 
'Brederodestraat 186 -', '2018', NULL, 
NULL, 'Antwerp,', 'Belgium', 
NULL, NULL, '32 3 369 32 32', 
NULL, '32 3 369 32 39', NULL, 
NULL, 'coffee@32cup.com', 'J', 
'CL', 'CO', NULL, 
'VAT: BE 0845.313.032

Account: KBC
IBAN BE43 7310 2709 4701
BIC: KREDBEBB

OLD bank: BYBLOS

NEW Bank information (Sep 21st, 2015)-
Rabobank
Croeselaan 18,
3521 CB Utrecht, The Netherlands', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(980, 'ACAÍA EXP. E IMPORTAÇÃO LTDA', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(619, 'ADAUTO MARQUES DE PAIVA', NULL, 
'FAZENDA SANTA ANA DA BELA VISTA', NULL, NULL, 
NULL, 'ELOI MENDES', 'ELOI MENDES', 
'MG', NULL, NULL, 
'35-32191770', NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, '005.197.746-04', 
'236/0989', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(929, 'ADUBOS REAL LTDA', 'ADUBOS', 
'RUA ADRIANO DE FREITAS CARDOSO, 70', NULL, 'FATIMA III', 
NULL, 'POUSO ALEGRE', 'POUSO ALEGRE', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '21.437.447/0001-00', NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(474, 'AFONSO JORGE SCHMOLZ DE MATTOS E OUTROS', 'AFONSO', 
'FAZ. BRAUNA', NULL, NULL, 
NULL, 'ARAPONGA', 'ARAPONGA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, '628.706.616-49', 
'037/0004', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1667, 'African Coffee Roasters EPZ LTD.', 'AFRICAN COFFEE ROASTERS EPZ LTD', 
'Twiga Close, Off Simba Road', NULL, 'Athi River Nairobi - Kenya', 
NULL, 'P.O.Box 535-00204', NULL, 
NULL, NULL, '254 (0) 7926528', 
'254 (0) 20 2400', NULL, NULL, 
NULL, 'svi@acr.co.ke', 'J', 
'CL', 'CO', 'Mr. Stephen E. Vick
Head of Procurement, Quality Control and Product Development
Email: svi@acr.co.ke', 
'Export Processing Zone (EPZ)



Twiga Close, Off Simba Road
P.O.Box 535-00204 Athi River Nairobi, Kenya.
www.acr.co.ke


Notify Party (BL) - 10/11/2021
Expolanka Freight Limited
Baywood Bldg,4th  Flr, Moi Avenue,
P.O BOX 83344, Mombasa, 80100 Kenya, East Africa
M + 254 735 551365, T + 254 41 2319148

Courrier Documents to - 10/11/2021
EXPOLANKA FREIGHT LIMITED
Kenroid Warehouse Unit 1,
2nd Freight Lane, Jomo Kenyatta International Airport, 
P.O. Box 49096-00100, Nairobi, Kenya, East Africa
T + 254 20 5142500 | M + 254 705 084 367   
Attn: Lucia Nzau', NULL, NULL, 
NULL, true, 7, 
15, NULL, NULL, 
NULL, NULL),
(1504, 'AGRO COFFEE COM.IMP. E EXP. LTDA', 'AGRO COFFEE COM.IMP. E EXP. LTDA', 
'Fazenda Santa Rosa', NULL, 'Zona Rural', 
NULL, 'Eloi Mendes', NULL, 
'mg', '37110-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '18.317.171/0001-04', '083506', 
'002.68304-0023', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(1403, 'AGROCAFÉ COMÉRCIO E REPRESENTAÇÃO LTDA', 'AGROCAFÉ COMÉRCIO E REPRESENTAÇÃO LTDA', 
'AVENIDA OLEGARIO MACIEL,', '988', NULL, 
NULL, 'MONTE CARMELO', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '03.348.512/0001-31', NULL, 
'431.038.635-0080', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(476, 'AGROP. BREJÕES', 'AGROP. BREJÕES', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(828, 'AGROPECUARIA MERCANTIL', 'MERCANTIL', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(534, 'AGROPECUARIA SERRA NORTE', NULL, 
'RUA SANTA CATARINA', '996', NULL, 
NULL, 'BELO HORIZONTE', 'BELO HORIZONTE', 
'MG', '30170-080', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1462, 'Ahold Delhaize Coffee Company B.V.', NULL, 
'Hoofdtocht 3', NULL, '1507 CJ Zaandam', 
NULL, 'The Netherlands', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', 'VAT number: NL002230987B01
EORI Ahold: NL002230987', 
'Attn. Martijn Duin
Ahold Delhaize Coffee Company B.V.
Hoofdtocht 3
1507 CJ
ZAANDAM
Netherlands  1507 
Vat NL002841629B01

Company name : Ahold Delhaize Coffee Company BV Zaandam 
Bank                      : ING Bank N.V.
Account numb. : 20.15.65.10
IBAN                      : NL60 INGB 0020 1565 10
Swift                      : INGBNL2A', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(477, 'ALCOFFEE', 'ALCOFFEE', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(262, 'ALFENAS CAFÉ LTDA', 'ALFENAS', 
'FAZENDA DA ILHA', NULL, NULL, 
NULL, 'ALFENAS', 'ALFENAS', 
'MG', NULL, '(35) 5732008', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: DIRCÉIA/CLOVIS', '01.893.896/0001-48', NULL, 
'016.706.932.0033', false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(903, 'ALIANÇA DE ATACADOS E SUPERMERCADOS S.A', 'ALIANÇA', 
'VIA MUNICIPAL MANOEL JACINTO COELHO', '901', NULL, 
NULL, 'CONTAGEM', 'CONTAGEM', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '07.399.636/0001-05', NULL, 
'186.348.354-0086', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(221, 'ALLCOFFEE EXP. E COM . LTDA', NULL, 
'AV. CENTENÁRIO', '551B', NULL, 
NULL, 'MANHUAÇÚ', 'MANHUAÇÚ', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '00.980.206/0004-78', NULL, 
'394.966.907-0100', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(217, 'ALLCOFFEE EXP. E COM. LTDA', NULL, 
'RUA FREI GASPAR', '24', 'CJ 61/62', 
'CENTRO', 'SANTOS', 'SANTOS', 
'SP', '11.010-190', '2198990', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: LELO', '00.980.206/0001-25', NULL, 
'633.352.611.119', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(107, 'ALLCOFFEE EXP. E COM. LTDA', 'HHF', 
'RUA JOSE A.R.VALLE', '1173 D', NULL, 
NULL, 'GUAXUPE', 'GUAXUPE', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: LELO', '00.980.206/0002-06', NULL, 
'287.966.907.0023', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1285, 'Ally Brazilian Coffee Merchants', 'Ally Brazilian Coffee', 
'7890 Peters Road Suit G-100', NULL, NULL, 
'Plantation - FL 33321', NULL, NULL, 
NULL, NULL, '+1-954-990-7428', 
NULL, '+1-480-772-4977', NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Mr. Marco Figueiredo / Bob Phillips

www.allycoffee.com


---------------------
April 22nd, 2014:
Our bank instructions are standard for all contracts.

Brown Brothers Harriman & Co
140 Broadway
New York, NY 10005
Attn. Collection Dept', NULL, NULL, 
NULL, true, 7, 
12, NULL, NULL, 
NULL, NULL),
(1707, 'Al-Yemeni Cafe Co.', 'Al-Yemeni Cafe co.', 
'1, Mazloum st., Bab Ellouk sq.', NULL, 'Down Town', 
NULL, 'Cairo - Egypt', NULL, 
NULL, NULL, '+1222100922', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'Please find below details (22/10/2020):

Al-Yemeni Cafe co.
1, Mazloum st., Bab Ellouk sq.
Down Town
Cairo - Egypt
Tax ID : 205/117/163
Mr. Ahmed Abdel Maboud
Tell: +1222100922
Email: yemenicafe@gmail.com', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(478, 'ANDRE & CIE', 'ANDRE & CIE', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(479, 'ANDRE MERCOSUR', 'ANDRE MERCOSUR', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1872, 'Anthem Coffee Imports', 'Anthem Coffee Imports', 
'13621 Wyandotte Street', NULL, 'Kansas City MO 64145', 
NULL, 'United States of America', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'TRAFFIC@ANTHEMCOFFEEIMPORTS.COM', 'J', 
'RE', 'CO', 'FDA#: 796318041', 
'ANTHEM COFFEE IMPORTS
13621 WYANDOTTE STREET
KANSAS CITY, MO 64145 - UNITED STATE 
FDA #: 796318041 PH:+1 913-856-3480', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(909, 'ARMAJARO - AGRI-COMMODITIES DO BRASIL LTDA', 'ARMAJARO', 
'RUA XV DE NOVEMBRO', '65', NULL, 
NULL, 'SANTOS', 'SANTOS', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '09.288.149/0001-92', NULL, 
'633.667.116.113', false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(996, 'ARMAJARO TRADING LIMITED', 'Armajaro', 
'Nightingale House 65 Curzon Street', NULL, 'W1J 8PE', 
NULL, 'London, UK', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Please take note since February 01st  Armajaro Londres
has been changed its address. 
Kindly  update your records as below:

Armajaro Trading Limited
Nightingale House
65 Curzon Street
London
W1J 8PE', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(999, 'ARMENIA COFFEE CORPORATION', 'ARMENIA', 
'3020 WESTSCHESTER AVE.PURCHASE', '10577', NULL, 
NULL, 'NEW YORK', 'USA', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1001, 'Arvid Nordquist H.A.B.', 'Arvid Nordquist', 
'Ekensbergsvagen', '117 - BOX 1285', NULL, 
'SE 171 25', NULL, '- Solna, Sweden', 
NULL, NULL, '00 46 87 991861', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', 'VAT SE556007786801', 
'eori number SE5560077868

23/06/2021 PSS to be sent to:

Arvid Nordquist
Ekensbergsvägen 117
171 41 Solna
Sweden

ARVID NORDQUIST H.A.B.
NORDQUIST
PHILIPPE BARRECA

Notify:
ARVID NORDQUIST H.A.B.
EKENSBERGSVAGEN 117 - 
SE 171 25
BOX 1285171 25 SOLNA
SWEDEN

Consignee: To Order

*****
Bank address (received on Sep 03rd, 2024)
Nordea Bank Abp SA
Collection Services PL Team.
al. Marsz . Edwarda Smiglego Rydza 20,
93 281 Lódz , Poland


Bank Address (as of Nov 21st, 2019):
Nordea Bank Abp, filial i Sverige
Trade Finance
Kilsgatan 4
T610
SE-40509 Gothenburg
Sweden
SWIFT: NDEASESS


Bank address (received on Sept. 22nd, 2015)
SEB
Trade Finance Operations
Östra Hamngatan 24 (Plan 5)
405 04 Göteborg 
Sweden
SWIFT: ESSESESS


Bank address (received on 21/02/2014):
Danske Bank, Sweden Branch 
Trade Finance Operations 
Norrmalmstorg 1 
SE-111 46  Stockholm, Sweden 
Contact person is Trade Finance Operations', NULL, NULL, 
NULL, true, NULL, 
27, NULL, NULL, 
NULL, NULL),
(904, 'ASSOCIAÇÃO COSTAS COFFEE', 'COSTAS', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(480, 'ATLÂNTICA EMPRESA DE COMÉRCIO EXTERIOR LTDA', 'ATLANTICA', 
'RUA ROQUE PORCARO', '14', NULL, 
NULL, 'MANHUMIRIM', 'MANHUMIRIM', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '03.936.815/0007-60', NULL, 
'394.094.584-0204', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1004, 'Aziende Riunite Caffè S.P.A.', 'Aziende', 
'Via I. Rosselini', '2', '20124', 
NULL, 'Milano', 'ITALY', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'BANCA POPOLARE COMMERCIO INDUSTRIA 
Ufficio Estero – Via Solferino, 23/A 
20123 MILANO – Italy 
Iban: IT 97 R 05048 01606 000000010439 
Beneficiary: Aziende Riunite Caffè S.p.A.

Banca  Credito Emiliano Spa
Centro Imprese Milano
Via Nazario  Sauro 4
20124 Milano
attenzione  Sig.Forneris


Aziende Riunite Caffè S.P.A.
Via I. Rosselini, 2 
20124 -  Milano - Italy', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(880, 'BANCO DO BRASIL - CPR / SOCOPA', 'CPR', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(859, 'BEIGEL COFFEE COMÉRCIO E REPRESENTAÇÕES LTDA', 'BEIGEL', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1768, 'Bentax A/S', NULL, 
'Svenstrup Banevej 3', NULL, '9230 Svenstrup J, Denmark', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', 'Part of group - related companies: Bentax Holding A/S
Collab with RoastersGreen  Guold - Soren Sylvest', 
'Bentax A/S
Svenstrup Banevej 3
9230 Svenstrup J
Denmark
VATno: DK 27665810', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1007, 'BERLINER INSTANTKAFFEEWERK CO.', 'BERLINER', 
'HABERSTRASSE 9-1112057', NULL, NULL, 
NULL, 'BERLIN', 'GERMANY', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'EUGEN ATTE', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1010, 'Bernhard Benecke Coffee GmbH & K.G.', NULL, 
'Pickhuben', '6', NULL, 
NULL, 'Hamburg', NULL, 
NULL, '20457', '49 40 3785 140', 
NULL, '49 40 37500880', NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Mr. Carsten Sievers

FLO ID 1033', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1011, 'BJORN R PAASCHE', 'PAASCHE', 
'PO BOX 318 - N-5051 NESTTUN', NULL, NULL, 
NULL, 'BERGEN', 'NORWAY', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'MR. BJORN R. PAASCHE', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1015, 'Blaser Trading USA', 'Blaser Trading USA', 
'Plantation Executive Square 7501 N.W.Fourth Street', NULL, 'Suite 201', 
'Plantation', 'Florida', 'USA', 
NULL, '33317', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Document representation for to: Blaser Trading USA, Plantation, in Trust , or

documents may be presented at your expense through:

Bank of America, N.A. Trade Operations
Mail Code PA6-580-02-30
One Fleet Way
Scranton, PA 18507-1999
Phone: +1-570-330-4333', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1017, 'Blend Minas Cafes Especiais Ltda.', NULL, 
'Rua Oliveira Nota', '273', NULL, 
NULL, 'Esp. Santo do Pinhal', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '04545573/001-91', NULL, 
'53008505411', false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1025, 'Blossom Valley International Company Limited', 'Blossom Valley', 
'72 Mo-Fan St.', NULL, 'Taichung,', 
NULL, 'Taiwan', 'China', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL);
