INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(83, 'COSTA RIBEIRO EXP. E IMP. LTDA', NULL, 
'ROD. SP 342', 'KM 204', 'SALA 3', 
NULL, 'ESP. SANTO DO P', 'ESP. SANTO DO P', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '53.446.332/0001-60', NULL, 
'530.013.407.118', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(485, 'COTIA TRADING S/A', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1086, 'CTM - Altromercato', 'Altromercato', 
'Via Macello', '18', '39100', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'A partir de Jan/06:

CTM Altromercato Soc. Coop. 
Via Crispi, 9 
39100 Bolzano (BZ) 
ITALIA', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1881, 'CULTUR COMERCIAL DE GRÃOS LTDA', 'CULTUR COMERCIAL DE GRÃOS LTDA', 
'Av. Celina Ferreira Ottoni', '518', 'loa 3', 
NULL, 'Varginha', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'PAULINHO - P & G', '22.010.233/0002-99', NULL, 
'37401540070', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(486, 'CUSTÓDIO FORZZA', 'CUSTÓDIO FORZZA', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
7, NULL, NULL, 
NULL, NULL),
(1088, 'CZARNIKON RIONDA COFFEE CO.INC', 'CZARNIKON RIONDA COFFEE CO.INC', 
'RIONDA (USA)', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, '0012124229041', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'CZARNIKON RIONDA COFFEE CO.INC
RIONDA (USA)', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1103, 'D.R. Wakefield & Co. LTD.', 'D.R. Wakefield', 
'Thompson House 42-44 Dolben Street,', NULL, 'London, SE1 0UQ', 
NULL, NULL, 'United Kingdom', 
NULL, NULL, '44 (0)20 7202 2', 
NULL, '44 (0)20 7593 1', NULL, 
'www.drwakefield.com', 'www.drwakefield.com', 'J', 
'CL', 'CO', 'Philip Searle +44 (0) 77 11381208
Henry Clifford +44 (0) 77 212 60 902
Mantvydas Trainavicius +44 (0) 77 0367 1705
Gustaaf Bremer
Chris Leavy +44 (0) 207 202 2620', 
'It would be good if they could send docs directly to our office.
D.R.Wakefield & Company Limited
Thompson House
42-44 Dolben Street
London SE1 0UQ
England

If for whatever reason this is not possible, then the address of our bank is:

HSBC BANK PLC
TRADE SERVICES
LEICESTER TRADE SERVICES CENTRE
51 DE MONTFORT STREET
LEICESTER, LE1 7BB

SWIFT CODE: HBUKGB4B

D.R. Wakefield (Europe) & Co. Limited.
108 Q House 
Furze Road, Sandyford
Dublin 18 - Ireland

Helen Shewan (head of logistics) address, when in lockdown:
MS HELEN SHEWAN
14 DERING ROAD
CROYDON
CR0 1DS
SURREY
UK.', NULL, NULL, 
NULL, true, NULL, 
7, NULL, NULL, 
NULL, NULL),
(1604, 'D.R. Wakefield (Europe) & Co. Limited.', 'D.R. Wakefield (Europe) & Co. Limited.', 
'Commercial House, Millbank Business Park', NULL, NULL, 
NULL, 'Lucan, Co. Dublin', 'Ireland', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', 'D R Wakefield - EU Trade <eutrade@drwakefield.com>', 
'from Nov/23 *NEW ADDRESS*

D.R. Wakefield (Europe) & Co Limited, 
Commercial House, 
Millbank Business Park, 
Lucan, Co. Dublin, Ireland.

Tel: 02072022620

*old address*
D.R. Wakefield (Europe) & Co. Limited.
108 Q House 
Furze Road, Sandyford
Dublin 18 - Ireland
**
Company Registration number in Ireland : 641923

De: D R Wakefield - EU Trade <eutrade@drwakefield.com> 
Enviada em: segunda-feira, 7 de outubro de 2019 07:27
Para: Contracts <contracts@wolthers.com>; D R Wakefield - Quality <quality@drwakefield.com>; Logistics <logistics@drwakefield.com>
Assunto: Any samples or Correspondence for DRW Europe should be sent to usual London ADDRESS!
Prioridade: Alta

Any samples or Correspondence for DRW Europe should be
sent to usual London ADDRESS!

INFORMED ON March 07th 2023:
docs via bank:

HSBC Continental Europe - GTRF
Client Service
38, Avenue Kleber
75116 Paris
France

SWIFT
CCFRFRPP', NULL, NULL, 
NULL, true, 7, 
21, NULL, NULL, 
NULL, NULL),
(1391, 'Daarnhouwer & Co. BV', 'Daarnhouwer & Co. BV', 
'Korte Hogendijk 18', NULL, '1506 MA', 
NULL, NULL, 'Zaandam - The Netherlands', 
NULL, NULL, '31 75 612 63 88', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', 'VAT ID: NL003160.579.B01
Daarnhouwer ID: UTZ_CF1000001182', 
'Direct contracts, send docs, OBL via Bank:

ABN AMRO Bank N.V.
Attn of  TB -Trade & Guarantees 
Coolsingel 93
3012 AE Rotterdam, The Netherlands
Tel. +31 (0)10 40 25444

Swift: ABNANL2A

PSS:

Daarnhouwer & Co. B.V.
Korte Hogendijk 18
1506 MA Zaandam
The Netherlands
P.O. Box 2037
1500 GA Zaandam
The Netherlands
T + 31 75 612 63 88
F + 31 75 631 85 32
E coffee@daarnhouwer.nl

Repasse, SWB depois do pgamento
When SWB, no need to dispatch docs

RFA ID
Daarnhouwer & CO BV

RA_00065482112', NULL, NULL, 
NULL, true, 7, 
26, NULL, NULL, 
NULL, NULL),
(667, 'DATERRA ATIVIDADES RURAIS', 'DATERRA', 
'RUA ROMUALDO ANDREAZZI', '33', NULL, 
NULL, 'CAMPINAS', 'CAMPINAS', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
7, NULL, NULL, 
NULL, NULL),
(328, 'DECOTRADE DO BRASIL', NULL, 
'AV. CAFÉ DO PONTO', '479', 'SALA. 2', 
'JARDIM DOS CAMARGOS', 'BARUERI', 'BARUERI', 
'SP', '06.410-900', '(11) 72997380', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: UNIÃO', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1882, 'DOLCE COFFEE COMERCIO E EXPORTAÇÃO DE CAFÉ LTDA', 'DOLCE COFFEE COMERCIO E EXPORTAÇÃO DE CAFÉ LTDA', 
'Rua Marieta Almeida', '443', NULL, 
NULL, 'Varginha', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'PAULINHO - P&G', '27.409.203/0001-92', NULL, 
'002.939.070-0078', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(798, 'DOUTOR COFFEE ESPECIALISTA EM CAFÉ LTDA', 'DR', 
'AVENIDA 15 DE AGOSTO', '1859', NULL, 
NULL, 'SOCORRO', 'SOCORRO', 
'SP', '13960-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '02.759.020/0001-76', NULL, 
'668.029.817.110', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1601, 'E.F. Com. e Distribuição de Produtos Alimentícios LTDA.', 'E.F. Comercio e Distribuição de Produtos Alimentícios LTDA.', 
'Av. Senador Feijó', '686', 'sala 1906', 
'Vila Mathias', 'Santos', NULL, 
'SP', '11015-504', '3468-4583', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '32.450.692/0001-66', NULL, 
'633.838.987.113', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(78, 'E.M.F COMERCIO EXP. IMP. LTDA', NULL, 
'FAZ. CACHOEIRINHA', NULL, NULL, 
NULL, 'ALBERTINA', 'ALBERTINA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: MARQUINHO', '19.658.020/0001-82', NULL, 
'914.434.054.0070', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1317, 'Ecom Japan Ltd.', 'Ecom Japan Ltd.', 
'6F Kinsan Bldg.', '4-1-21 Nihonbashi Muromachi', '103-0022 Tokyo, Japan.', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(951, 'ED&F MAN BRASIL S/A', 'VOLCAFE', 
'PRAÇA RUI BARBOSA', '300', '309', 
'CENTRO', 'UBERABA', 'UBERABA', 
'MG', '28010-240', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '35.829.068/0007-58', NULL, 
'701.226.895.0035', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(81, 'ED&F MAN VOLCAFE BRASIL LTDA', 'Volcafe Santos', 
'Rua Frei Gaspar,', '22', 'CJ 21/22', 
'Centro', 'Santos', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '33.729.690/0031-99', '254920-0', 
'633.448.619.117', true, NULL, 
9, NULL, NULL, 
NULL, NULL),
(15, 'ED&F MAN VOLCAFE BRASIL LTDA', 'VOLCAFE LTDA', 
'Av. Presidente Tancredo Neves', '1474', NULL, 
NULL, 'Caratinga', NULL, 
'MG', '35300-101', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'CONTATO:', '33.729.690/0018-11', NULL, 
'134.262.043-0102', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(991, 'EFICO S.A.', NULL, 
'IJZERLAAN 30B-2060 ANTWERPEN 6 - BELGIUN', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'N.V. EFICO S.A.
EFICO
MICHEL GERMANES', NULL, NULL, 
NULL, false, NULL, 
7, NULL, NULL, 
NULL, NULL),
(105, 'EISA - EMPRESA INTERAGRÍCOLA S.A', 'EISA MACHADO', 
'Rodovia MG 453 KM 7', NULL, NULL, 
NULL, 'Machado', NULL, 
'MG', '37750-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'CONTATO: BIRA', '62.356.878/0048-85', NULL, 
'707.711.273-0580', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(6, 'EISA - EMPRESA INTERAGRÍCOLA S.A', 'EISA', 
'Rua do Comercio do cafe', '342', NULL, 
'.', 'Varginha', NULL, 
'MG', '37026-530', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '62.356.878/0039-94', NULL, 
'707.711.273.0415', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(973, 'EISA-EMPRESA INTERAGRICOLA S/A', 'EISA -  ARAGUARI', 
'RUA BRASILIA', '300', 'SALA 01', 
'AMORIM', 'ARAGUARI', NULL, 
'MG', NULL, '34-32427677', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '62.356.878/0027-50', NULL, 
'481.711.273-03-54', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(1174, 'EISA-EMPRESA INTERAGRICOLA S/A', 'Eisa', 
'Av. Barao do Rio Branco', '194', NULL, 
NULL, 'Manhuaçu', NULL, 
'MG', NULL, '33) 3331-1546', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '62.356.878 /0011 – 9', NULL, 
'394.711273.02-31', true, 2, 
2, NULL, NULL, 
NULL, NULL),
(998, 'EKAF-IND.NAZIONALE DEL CAFFE', NULL, 
'VIA GRAMSCI 27-16010 MANESSENOGENOVA - ITALY', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'EKAF-IND.NAZIONALE DEL CAFFE
EKAF
C.I.C.E.', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(895, 'EPS - CORRETORA DE MERCADORIAS LTDA', 'EPS', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(897, 'ESPLANADA COM. REP. DE CAFÉ LTDA', 'ESPL', 
'ESTRADA VICINAL - STO ANTONIO DO JARDIM A SÃO JOÃO', 'DA BOA', 'VISTA KM 01 S/N', 
NULL, 'STO ANTONIO DO JARDIM', 'STO ANTONIO DO JARDIM', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '04.593.983/0001-78', NULL, 
'628.057.829.114', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(343, 'ESTEVE S/A', 'ESTEVE S/A', 
'AV. BARÃO DO RIO BRANCO', '194', NULL, 
'BAIXADA', 'MANHUAÇU', 'MANHUAÇU', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '62.356.878/0011-93', NULL, 
'394.711.273.0231', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(519, 'ESTEVE S/A', 'ESTEVE S/A', 
'AVENIDA COLOMBO', '3361', NULL, 
NULL, 'MARINGÁ', 'MARINGÁ', 
'PR', '37030-120', '(44) 222-7845', 
NULL, '(44)', NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '62.356.878/000383', NULL, 
'70.101.789-70', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(455, 'ESTEVE S/A', 'ESTEVE S/A', 
'RUA PRUDENTE DE MORAIS', '80', NULL, 
NULL, 'VITÓRIA DA CONQ', 'VITÓRIA DA CONQ', 
'BA', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '62.356.878/0019-40', NULL, 
'40.219.699-NO', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(579, 'ESTEVE S/A', 'ESTEVE S/A', 
'AV. MARCIANO PIRES', '1300', NULL, 
NULL, 'PATROCINIO', 'PATROCINIO', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '62.356.878/0027-50', NULL, 
'481.711.273.0354', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(557, 'ESTEVE S/A', 'ESTEVE S/A', 
'AV. COLOMBO', '3361', NULL, 
NULL, 'MARINGÁ', 'MARINGÁ', 
'PR', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '62.356.878/0003-83', NULL, 
'70.101.789-70', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1461, 'Eugen Atté GmbH', 'Eugen Atté GmbH', 
'Pickhuben 6,', NULL, NULL, 
NULL, '20457 Hamburg, Germany', NULL, 
NULL, NULL, '49 40 3786200', 
NULL, NULL, NULL, 
NULL, 'eugenatte@coffeeagents.com,', 'J', 
'CL', 'CO', NULL, 
'Managing directors : Otto Bertram, Michael Frontzeck,
Joachim Taubensee
AG Hamburg, HRB 58782 / VAT Nr.: DE 172 862 113', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(598, 'EUROBRASIL LTDA', 'EUROBRASIL LTDA', 
'RUA FREI GASPAR', '20', 'TERREO', 
NULL, 'SANTOS', 'SANTOS', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '01.453.839/0001-48', '120808-9', 
'633.362.876-112', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(85, 'EUROBRASIL LTDA', 'EUROBRASIL LTDA', 
'ROD. BR 491 - K 06', 'SALA A', NULL, 
NULL, 'S.S DO PARAISO', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '01.453.839/0002-29', NULL, 
'647.197.912.0087', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(985, 'EUROCA GMBH', NULL, 
'SANDTORKAI 420457 HAMBURG - GERMANY', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, '(40) 3743755-6', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'EUROCA GMBH
EUROCA GMBH
MR. LUDWIG SPRENGEL', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(488, 'EVAIR', 'EVAIR', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(103, 'EXP. E IMP. MARUBENI - COLORADO LTDA', NULL, 
'RUA FREI GASPAR', '22', 'CJ 91/92', 
'CENTRO', 'SANTOS', NULL, 
'SP', NULL, '2195141', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '58.154.840/0001-99', NULL, 
'633.028.586.115', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(652, 'EXP. E IMP. MARUBENI COLORADO LTDA', 'MARUBENI', 
'ROD. MELO PEIXOTO - BR 369 KM 88', NULL, NULL, 
NULL, 'CORNELIO PROCOPIO', 'CORNELIO PROCOPIO', 
'PR', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '76.255.926/0001-99', NULL, 
'534.00815-54', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(444, 'EXP. E IMP. MARUBENI COLORADO LTDA', NULL, 
'AV. IRIRI', '339', 'SALA 2', 
NULL, 'SERRA', 'SERRA', 
'ES', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '58.154.840/0017-56', NULL, 
'082.074.04-6', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(411, 'EXP. E IMP. MARUBENI COLORADO LTDA', 'MARUBENI', 
'ROD. BR 267 KM 01', '1321', 'SALA 1', 
'DIST. INDL.', 'MACHADO', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:
CNPJ: 58.154.840/0001-99 DA CONTA CORRENTE', '58.154.840/0004-31', NULL, 
'390.107.486.0018', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(130, 'EXP. E IMP. MARUBENI-COLORADO LTDA', 'MARUBENI', 
'RUA EZZIO PUCCI', '2901', NULL, 
'DIST. INDL.', 'FRANCA', NULL, 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '58.154.840/0007-84', NULL, 
'310.041.218.115', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(993, 'Expocafe S.A.', NULL, 
'Carrera  7 # 74 - 36 Piso - Bogota / Colombia', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(727, 'EXPORTADORA DE CAFÉ CENTRO OESTE LTDA', 'EP', 
'RUA BERNARDINO DE CAMPOS 2-42', NULL, NULL, 
NULL, 'BAURU', 'BAURU', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '04.181.421/0002-06', '209.311.998.110', 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(698, 'EXPORTADORA DE CAFE TURQUESA LTDA', 'TURQUESA', 
'RUA DO COMERCIO', '26', 'SALA 28', 
'CENTRO', 'SANTOS', 'SANTOS', 
'SP', NULL, '3219-1276', 
NULL, '3219-8412', NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(469, 'EXPORTADORA POÇOS DE CALDAS LTDA', 'EXP. POÇOS', 
'RUA PIAUI', '129', NULL, 
NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 
'MG', '37701-024', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: CRISTIANO OTTONI', '04.935.791/0001-00', NULL, 
'518.169.029-0018', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(16, 'EXPRINSUL COMERCIO EXTERIOR LTDA.', 'EXPRINSUL', 
'PRAÇA CHAMPAGNAT', '29', '10° ANDAR S101', 
'CENTRO', 'VARGINHA', 'VARGINHA', 
'MG', '37.002-150', '(35) 2191112', 
NULL, '(35) 2191512', NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: ZE CARLOS', '86.431.889/0001-87', NULL, 
'707.877.445-0035', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(490, 'F.S.A  ( AMOCA )', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, false, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1351, 'Falcon Coffees Limited', 'Falcon Coffees', 
'The Candlemakers,', 'West Street, Lewes', NULL, 
'East Sussex -', 'BN7 2NZ /', 'United Kingdom', 
NULL, NULL, '+44 1273 476 28', 
NULL, '+44 1273 376 83', NULL, 
NULL, 'coffee@falconcoffees.com', 'J', 
'CL', 'CO', NULL, 
'Falcon Coffees Limited
The Candlemakers
West Street, Lewes
East Sussex - BN7 2NZ
United Kingdom

Tel: (+44) 1273 476289

Contact: Mr. Matt Horsbrugh
               Mr. Marek Glowa', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(491, 'FAZENDA FORTALEZA', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(811, 'FAZENDA SANTA FÉ', 'STA', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(878, 'FAZENDA SÃO PEDRO', 'CERTRA COFFEE', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1009, 'FINAGRA (UK) LTD', NULL, 
'EUROPE HOUSE WORLD TRADE CENTRE LONDON E1 9AAENGLA', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'FAX 44171481012', NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'FINAGRA (UK) LTD
FINAGRA
DAVID MARGULIES/PHIL MUNDEN', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(871, 'FORTALEZA IND. E COM.DE EXPORTAÇÃO DE CAFÉ', 'FORTALEZA', 
'Rua Pinto Ribeiro, 759', NULL, NULL, 
NULL, 'S.Sebastiao do Paraiso', NULL, 
'MG', '37960-000', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1006, 'FRELLSEN KAFFE', NULL, 
'INDUSTRIVEJ 144000 ROSKILDEDENMARK', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, '45 46757300', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
NULL, 'CO', NULL, 
'FRELLSEN KAFFE.
FRELLSEN KAFFE
MR. CLAUS FRELLSEN


NORDEA BANK
Registration number: 2232
Account number 0280300004
Swift: NDEA DKKK
IBAN: DK2320000280300004', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1146, 'Futura Café Comercio e Assessoria em Mercado de Café Ltda', 'FuturaCafé', 
'Rua Infante Vieira', '2986', NULL, 
NULL, 'Patrocínio', 'Brasil', 
'MG', '38740-000', '(34) 3831-1831', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, '23.215.299/0001-05', NULL, 
'00262235400-78', true, 8, 
2, NULL, NULL, 
NULL, NULL),
(1008, 'G.VESCOVI SPA', NULL, 
'VIA VICENZA 1, 35100PADOVA/ITALY', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'G.VESCOVI SPA
VESCOVI
COFFEE DEPARTMENT', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(251, 'GERSON EUGÊNIO TUDELA', 'GERSON', 
'FAZ. MACAUBÁS - BR 364', 'KM 509', NULL, 
NULL, 'MONTE CARMELO', 'MONTE CARMELO', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
'CONTATO: PLENO', NULL, '029.158.398-91', 
'431/0969', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(458, 'GOLDEN COFFEE COMÉRCIO E EXPORTAÇÃO LTDA', NULL, 
'AV. JOÃO BATISTA DA SILVA', '830', NULL, 
NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '00.800.254/0001-94', NULL, 
'143.942.583.0045', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1366, 'Golluecke & Rothfos GMBH', 'Golluecke & Rothfos GMBH', 
'Schlachte 3-5,', '28195', NULL, 
NULL, 'Bremen, Germany', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Golluecke & Rothfos GMBH
Schlachte 3-5
28195 Bremen, Germany', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(972, 'GRANCER', 'GRANCER', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'RONALDO TABOADA', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(370, 'GRAND CAFÉ COM. EXTERIOR LTDA', NULL, 
'RUA XV DE NOVEMBRO', '41', 'SALA 41', 
NULL, 'SANTOS', 'SANTOS', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: HENRIQUE', '55.202.592/0001-16', NULL, 
'633.218.534.114', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(365, 'GRAND CAFÉ COMÉRCIO EXTERIOR LTDA', NULL, 
'RUA PONTAL', NULL, 'SALA 6', 
'DT.INDUSTRIAL', 'ELOÍ MENDES', 'ELOÍ MENDES', 
'MG', '37.110-000', '32196105', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: HENRIQUE', '55.202.592/0004-69', NULL, 
'236.092.139.0016', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(826, 'GRANDE LESTE', 'GRANDE LESTE', 
'RUA DOMINGOS TEODORO', '34', NULL, 
NULL, 'SÃO JOÃO DA BOA VISTA', 'SÃO JOÃO DA BOA VISTA', 
'SP', '13872-006', '(19)3623-6676', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(492, 'GRANOCERES', 'GRANOCERES', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1153, 'GSC International Co., Ltd.', 'GSC International Co., Ltd.', 
'385-38 GSC Building, Mangwon-Dong, Map-Ku', NULL, NULL, 
NULL, 'Seoul', 'Korea', 
NULL, '121-821', '82-2-325-3031', 
NULL, '82-2-325-3047', NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'Mr. Eugene

Mitsui´s final client', NULL, NULL, 
NULL, true, 3, 
3, NULL, NULL, 
NULL, NULL),
(1878, 'Hansson BV', 'All Go Forwarding B.V.', 
'Newtonstraat 8,', NULL, '3281 NM Numansdorp', 
NULL, 'The Netherlands', NULL, 
NULL, NULL, '+31(0)186667111', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', 'EORI Hansson:  NL802020574B01', 
'All Go Forwarding B.V.
Hansson BV, Newtonstraat 8, 
3281 NM Numansdorp, The Netherlands', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1772, 'Harar Ltd.', 'Harar Ltd.', 
'Planetnaya Street', 'Building 11', 'Room 6/19 PM-8', 
NULL, 'Moscow', 'Russian Federation', 
NULL, '125167', NULL, 
NULL, NULL, NULL, 
NULL, 'coffee@harar.ru', 'J', 
NULL, 'CO', NULL, 
NULL, '1177746931823', NULL, 
NULL, true, 21, 
21, NULL, NULL, 
NULL, NULL),
(792, 'HEDGING GRIFFO VERDE MASTER FIM', 'HEDGING', 
'AV. PRES. JUSCELINO KUBITSCHEK', '1830', NULL, 
NULL, 'SÃO PAULO', 'SÃO PAULO', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '07.455.507/0001-89', NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(493, 'HERON COFFEE', 'HERON COFFEE', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1022, 'HOLLAND COFFEE (CALIFORNIA) IN', NULL, 
'505-A SAN MARIN DRIVE, SUITE 118', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, '(415) 893 1988', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'HOLLAND COFFEE (CALIFORNIA) INC.
HOLLAND COFFEE
ALLAN ODOM', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1024, 'HOLLAND COFFEE B.V.', NULL, 
'NIEUWE STEEN 45', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, '31 (0) 229-2840', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'HOLLAND COFFEE B.V.
HOLLAND B.V.
TRADING DEPARTMENT


ATTN: MRS. TRAMMAN103 Q. OLGAS AVE.,545 23 THESSALONIKI/GREECET.B.I.', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1250, 'Illyrians Developments Sh.P.K.', 'Illyrians Developments', 
'Ibrahim Rugova Street, 1 - 8th floor', NULL, 'Green Park complex,', 
NULL, 'Tirana - Albania', NULL, 
NULL, NULL, '+355 668088803', 
NULL, NULL, NULL, 
NULL, 'ben@sopranoscaffe.com', 'J', 
'CL', 'CO', NULL, 
'contact person: Mr. Elvis Shyta', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1242, 'Importadora Real S.R.L.', 'Importadora Real', 
'Fernadez de Enciso,', '3777', '1419 -', 
NULL, 'Buenos Aires', 'Argentina', 
NULL, '1419', '45 4639 9865', 
NULL, NULL, NULL, 
'importadorareal@fibertel.com.ar', 'importadorareal@fibertel.com.ar', 'J', 
'CL', 'CO', NULL, 
NULL, '970014666', NULL, 
NULL, true, 15, 
7, NULL, NULL, 
NULL, NULL),
(770, 'INDUSTRIA ALIMENTICIAS MARATÁ LTDA', 'MARATA', 
'BR. 101 KM 118', 'S/N', NULL, 
NULL, 'ITAPORANGA D''AJUDA', 'ITAPORANGA D''AJUDA', 
'SE', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '03.861.512/0001-30', NULL, 
'27.101.089-4', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(959, 'INDUSTRIA E COMÉRCIO CAFÉ FLORESTA S/A', 'FLORESTA', 
'RUA SÃO BENTO', '116', NULL, 
'VALONGO', 'SANTOS', 'SANTOS', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '45.046.703/0001-99', NULL, 
'633.012.467.119', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(264, 'INDÚSTRIA E TORREFAÇÃO E MOAGEM CAFÉ MARATA LTDA', NULL, 
'POVOADO CIDADE NOVA', NULL, NULL, 
NULL, 'LAGARTO', 'LAGARTO', 
'SE', '49.400-000', '(79) 6311224', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: LIMA', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1068, 'InterAmerican Coffee', 'InterAmerican Coffee', 
'1001 Country Club Drive, Suite E', NULL, NULL, 
'Moranga', 'California', 'U.S.A', 
NULL, '94556', NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1737, 'Interamerican Coffee GMBH', 'IAC Hamburg', 
'Coffee Plaza Am Sandtorpark 4', NULL, '20457 Hamburg, Germany', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'IAC Hamburg

Inacio Teixeira - inacio.teixeira@nkg.coffee
Interamerican Coffee GMBH
Coffee Plaza
Am Sandtorpark 4
20457 Hamburg
Germany

August 18th, 2021:
(Contracts of IAC London are done via IAC Hamburg)
Tim Gammer and Gerrit Krueger', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1736, 'InterAmerican Coffee Schweiz', 'IAC Schweiz', 
'Bahnhofstrasse 22', NULL, '6300 Zug · Switzerland', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'RE', 'CO', NULL, 
'IAC Schweiz

IAC - Christian Cvrljak christian.cvrljak@nkg.coffee
InterAmerican Coffee Schweiz
(a division of Bernhard Rothfos Intercafé AG)
Bahnhofstrasse 22
6300 Zug · Switzerland', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL),
(1065, 'Interamerican Commodities', 'Interamerican', 
'7600 W.Tidwell, Suite 111', '7704', NULL, 
NULL, 'Houston - Texas', 'U.S.A', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1074, 'Intercoffee LLP', NULL, 
'81, Fenchurch Street - CH 3001', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(965, 'INTERCOM CORRETAGENS COMERCIO E EXPORTAÇÃO LTDA', 'ATLANTICA', 
'AV. BARÃO HOMEM DE MELO', '4500', 'SALA 1217', 
'ESTORIL', 'BELO HORIZONTE', 'BELO HORIZONTE', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '04.565.932/0001-32', NULL, 
'001.078.652.0043', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(297, 'INTRADE PINHAL EXP. E IMP. LTDA', NULL, 
'RUA GUERINO COSTA', '150', NULL, 
'VILA NORMA', 'ESPIRITO SANTO', 'ESPIRITO SANTO', 
'SP', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO:', '62.251.616/0001-92', NULL, 
'530.020.830.116', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(703, 'Ipanema Agrícola S/A', 'Faz. Rio Verde', 
'ROD BR 267 - KM 321 - FAZENDA RIO VERDE', NULL, NULL, 
NULL, 'CONCEIÇÃO DO RIO VERDE', NULL, 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'USAR CNPJ: 42.135.913/0002-46', '42.135.913/0006-70', NULL, 
'IPR 177/0986', true, NULL, 
2, NULL, NULL, 
NULL, NULL),
(750, 'Ipanema Comercial e Exportadora S/A', 'Fazenda Rio Verde', 
'Rodovia BR 267', 'KM 321', NULL, 
NULL, 'Conceição do Rio verde', 'Brasil', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, '01.983.074/0004-09', NULL, 
'177 697 825 0214', true, NULL, 
7, NULL, NULL, 
NULL, NULL),
(891, 'Ipanema Comercial e Exportadora S/A', 'Fazenda Maringá', 
'Rodovia MG 179', 'KM 13', NULL, 
NULL, 'Alfenas', 'Brasil', 
'MG', NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'IPANEMA', '01.983.074/0003-10', NULL, 
'016.697.825-0188', true, NULL, 
7, NULL, NULL, 
NULL, NULL),
(1099, 'Iricaf Italia S.R.L', 'Iricaf', 
'Via Di Tor Cervara', '27300155', NULL, 
NULL, 'Roma', 'Italy', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(265, 'IRMÃOS KUHL', 'IRMÃOS KUHL', 
'AV. VITORINO ARIGONE', '355', NULL, 
'JARDIM SANTA BARBARÁ', 'LIMEIRA', 'LIMEIRA', 
'SP', '13.480-309', '(19) 4411204', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: ERNESTO', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(134, 'IRMÃOS RIBEIRO EXP. IMP. LTDA', NULL, 
'ROD. SP 342', 'KM 204', NULL, 
NULL, 'ESP. SANTO DO P', 'ESP. SANTO DO P', 
'SP', NULL, '(19) 6511867', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: FRANCISCO', '54.226.717/0001-85', NULL, 
'530.002.432.110', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(142, 'J.R. EXPORTADORA DE CAFÉ LTDA', NULL, 
'RUA XV DE NOVEMBRO', '41', 'CJ 40', 
NULL, 'SANTOS', 'SANTOS', 
'SP', NULL, '2197600', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
'CONTATO: GILBERTO', '60.820.560/0001-14', NULL, 
'633.263.390-110', true, NULL, 
7, NULL, NULL, 
NULL, NULL),
(494, 'JOÃO MARCOS', 'JOÃO MARCOS', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1030, 'Joh Johansson Coffee Department', 'Joh. Johannson Kaffee AS', 
'Filipstadveien', '11', NULL, 
NULL, 'Oslo', 'Norway', 
NULL, NULL, '47 22 83 43 50', 
'+47 23 11 77 00', NULL, NULL, 
NULL, NULL, NULL, 
NULL, 'CO', NULL, 
'Mr. Roger Wilhelmsen

Docs to be sent thru: 
DnB NOR ASA
Boks 1171 Sentrum 
Norway                                       
Swift: DNBANOKK  
IBAN: NO3470920442658

Joh. Johannson Kaffe AS
Filipstadveien 11-13
N-0250 Oslo, Norway', NULL, NULL, 
NULL, NULL, NULL, 
7, NULL, NULL, 
NULL, NULL),
(516, 'JOSÉ BATISTA FERREIRA', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'F', 
'CO', 'CO', NULL, 
'PORTUGUÊS', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(495, 'KAFFEE', 'KAFFEE', 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CO', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1028, 'KAFFEE EXPORTADORA E IMPORTADORA LTDA', NULL, 
'Rodovia ES 146 Km 6,1', NULL, NULL, 
NULL, 'Marechal Floriano', NULL, 
NULL, NULL, '(027) 3288-3178', 
'(027) 3288-3181', NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'KAFFEE EXPORTADORA E IMPORTADORA LTDA
KAFFEE
RUBENS/ GERVÁSIO', '39.309.521/0001-60', NULL, 
'081.599.55-2', true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1031, 'KAFFEE-EINKAUFSKONTOR W.HERZ', NULL, 
'PICKHUBEN 520457', NULL, NULL, 
NULL, 'HAMBURG', 'GERMANY', 
NULL, NULL, '00 49 40 638722', 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
'KAFFEE-EINKAUFSKONTOR W.HERZ
TCHIBO
HANZ', NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1034, 'Kaffehuset Friele AS', 'FRIELE', 
'Midtunhaugen 6,', NULL, NULL, 
NULL, 'Nesttun', 'Norway', 
NULL, 'N-5224', '4755926673', 
NULL, NULL, NULL, 
NULL, 'q��N\u0007Rpp\u0001���KKo\u000e�\u0000ei�\u001b8����8%�@&�<��8�:׀��^\u0018�f�u�\u001b�>M�0�����<\u001e�q�\b;��*��\u0007�}F\u000f\u0013C�h��v+g\u0018i�\tZ3#8\u0004\u0002U�\u0000c�\u001c�[��\u001b����\\��>8:O�Z��5~\f�\"\u001d+�\u001e�q�èG��j�\u000fjP4�̅I''\f�m8''\"L�<���v�(��\/��?�\u0016�ʎ����\u0006\u0019�c�\u0013��\u0001<�\u0019v����-�]I�(\\\u001f��e�''r�v�pOe\u0003=�!?��|\u000e67�y�mlm���\u0003K.K��>Q��p\u0000�֮����q2�����{�U����#�\"�\u0015�S�\u0007�\u0018�4�;�%�Y;�w\u001b�\t��\u000e@\u001c�:��\u0018\u0019�u���ж���+.T͜\u000f��;�`@�\u0018\u0004zm��\f�\r\/�����KmfB��@N��l1��{��\u0019���\u001a\u001b�P\u001dCU�\u0000L��RJ�1�@�\u0007\u00078', NULL, 
NULL, 'CO', NULL, 
'KAFFEHUSET FRIELE AS
FRIELE
BERNT TVEITSME

Contrato do Friele com a Maersk Lines
56 763

(as of Jan 17th, 2014)
DnB NOR Bank ASA
Pb 1600 Sentrum
N-0021 Oslo
Norway

IBAN N071 5202 0494 840 
Swift DNBANOKKXXX', NULL, NULL, 
NULL, true, NULL, 
15, '����\u0000\u0010JFIF\u0000\u0001\u0001\u0001\u0000`\u0000`\u0000\u0000��\u0000C\u0000\u0006\u0004\u0005\u0006\u0005\u0004\u0006\u0006\u0005\u0006\u0007\u0007\u0006\b\n\u0010\n\n\t\t\n\u0014\u000e\u000f\f\u0010\u0017\u0014\u0018\u0018\u0017\u0014\u0016\u0016\u001a\u001d%\u001f\u001a\u001b#\u001c\u0016\u0016', NULL, 
NULL, false),
(1042, 'Kemp Management Services Corp.', NULL, 
'Palm Chambers, 3', NULL, NULL, 
NULL, 'Tortola /British Virgin Island', NULL, 
NULL, NULL, NULL, 
NULL, NULL, NULL, 
NULL, NULL, 'J', 
'CL', 'CO', NULL, 
NULL, NULL, NULL, 
NULL, true, NULL, 
NULL, NULL, NULL, 
NULL, NULL),
(1215, 'Kolanda-Regina AG', 'Kolanda-Regina', 
'Binningerstrasse 87 -', NULL, NULL, 
NULL, '4123 Allschwil -', 'Switzerland', 
NULL, NULL, '41 61 486 90 00', 
NULL, NULL, NULL, 
NULL, 'jan.schenk@kolanda-regina.ch', 'J', 
'CL', 'CO', NULL, 
'www.kolanda.ch', NULL, NULL, 
NULL, true, 7, 
7, NULL, NULL, 
NULL, NULL);
