-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(1088, 'CZARNIKON RIONDA COFFEE CO.INC', 'CZARNIKON RIONDA COFFEE CO.INC', 'RIONDA (USA)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0012124229041', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'CZARNIKON RIONDA COFFEE CO.INC
RIONDA (USA)', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1103, 'D.R. Wakefield & Co. LTD.', 'D.R. Wakefield', 'Thompson House 42-44 Dolben Street,', NULL, 'London, SE1 0UQ', NULL, NULL, 'United Kingdom', NULL, NULL, '44 (0)20 7202 2', NULL, '44 (0)20 7593 1', NULL, 'www.drwakefield.com', 'www.drwakefield.com', 'J', 'CL', 'CO', 'Philip Searle +44 (0) 77 11381208
Henry Clifford +44 (0) 77 212 60 902
Mantvydas Trainavicius +44 (0) 77 0367 1705
Gustaaf Bremer
Chris Leavy +44 (0) 207 202 2620', 'It would be good if they could send docs directly to our office.
D.R.Wakefield & Company Limited
Thompson House
42-44 Dolben Street
London SE1 0UQ
England

If for whatever reason this is not possible, then the address of our bank is:

HSBC BANK PLC
TRADE SERVICES
LEICESTER TRADE SERVICES CENTRE
51 DE MONTFORT STREET
LEICESTER, LE1 7BB

SWIFT CODE: HBUKGB4B

D.R. Wakefield (Europe) & Co. Limited.
108 Q House 
Furze Road, Sandyford
Dublin 18 - Ireland

Helen Shewan (head of logistics) address, when in lockdown:
MS HELEN SHEWAN
14 DERING ROAD
CROYDON
CR0 1DS
SURREY
UK.', NULL, NULL, NULL, true, NULL, 7, NULL, NULL, NULL, NULL),
(1604, 'D.R. Wakefield (Europe) & Co. Limited.', 'D.R. Wakefield (Europe) & Co. Limited.', 'Commercial House, Millbank Business Park', NULL, NULL, NULL, 'Lucan, Co. Dublin', 'Ireland', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', 'D R Wakefield - EU Trade <eutrade@drwakefield.com>', 'from Nov/23 *NEW ADDRESS*

D.R. Wakefield (Europe) & Co Limited, 
Commercial House, 
Millbank Business Park, 
Lucan, Co. Dublin, Ireland.

Tel: 02072022620

*old address*
D.R. Wakefield (Europe) & Co. Limited.
108 Q House 
Furze Road, Sandyford
Dublin 18 - Ireland
**
Company Registration number in Ireland : 641923

De: D R Wakefield - EU Trade <eutrade@drwakefield.com> 
Enviada em: segunda-feira, 7 de outubro de 2019 07:27
Para: Contracts <contracts@wolthers.com>; D R Wakefield - Quality <quality@drwakefield.com>; Logistics <logistics@drwakefield.com>
Assunto: Any samples or Correspondence for DRW Europe should be sent to usual London ADDRESS!
Prioridade: Alta

Any samples or Correspondence for DRW Europe should be
sent to usual London ADDRESS!

INFORMED ON March 07th 2023:
docs via bank:

HSBC Continental Europe - GTRF
Client Service
38, Avenue Kleber
75116 Paris
France

SWIFT
CCFRFRPP', NULL, NULL, NULL, true, 7, 21, NULL, NULL, NULL, NULL),
(1391, 'Daarnhouwer & Co. BV', 'Daarnhouwer & Co. BV', 'Korte Hogendijk 18', NULL, '1506 MA', NULL, NULL, 'Zaandam - The Netherlands', NULL, NULL, '31 75 612 63 88', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', 'VAT ID: NL003160.579.B01
Daarnhouwer ID: UTZ_CF1000001182', 'Direct contracts, send docs, OBL via Bank:

ABN AMRO Bank N.V.
Attn of  TB -Trade & Guarantees 
Coolsingel 93
3012 AE Rotterdam, The Netherlands
Tel. +31 (0)10 40 25444

Swift: ABNANL2A

PSS:

Daarnhouwer & Co. B.V.
Korte Hogendijk 18
1506 MA Zaandam
The Netherlands
P.O. Box 2037
1500 GA Zaandam
The Netherlands
T + 31 75 612 63 88
F + 31 75 631 85 32
E coffee@daarnhouwer.nl

Repasse, SWB depois do pgamento
When SWB, no need to dispatch docs

RFA ID
Daarnhouwer & CO BV

RA_00065482112', NULL, NULL, NULL, true, 7, 26, NULL, NULL, NULL, NULL),
(667, 'DATERRA ATIVIDADES RURAIS', 'DATERRA', 'RUA ROMUALDO ANDREAZZI', '33', NULL, NULL, 'CAMPINAS', 'CAMPINAS', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, 7, NULL, NULL, NULL, NULL),
(328, 'DECOTRADE DO BRASIL', NULL, 'AV. CAFÉ DO PONTO', '479', 'SALA. 2', 'JARDIM DOS CAMARGOS', 'BARUERI', 'BARUERI', 'SP', '06.410-900', '(11) 72997380', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: UNIÃO', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1882, 'DOLCE COFFEE COMERCIO E EXPORTAÇÃO DE CAFÉ LTDA', 'DOLCE COFFEE COMERCIO E EXPORTAÇÃO DE CAFÉ LTDA', 'Rua Marieta Almeida', '443', NULL, NULL, 'Varginha', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'PAULINHO - P&G', '27.409.203/0001-92', NULL, '002.939.070-0078', true, 2, 2, NULL, NULL, NULL, NULL),
(798, 'DOUTOR COFFEE ESPECIALISTA EM CAFÉ LTDA', 'DR', 'AVENIDA 15 DE AGOSTO', '1859', NULL, NULL, 'SOCORRO', 'SOCORRO', 'SP', '13960-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '02.759.020/0001-76', NULL, '668.029.817.110', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1601, 'E.F. Com. e Distribuição de Produtos Alimentícios LTDA.', 'E.F. Comercio e Distribuição de Produtos Alimentícios LTDA.', 'Av. Senador Feijó', '686', 'sala 1906', 'Vila Mathias', 'Santos', NULL, 'SP', '11015-504', '3468-4583', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '32.450.692/0001-66', NULL, '633.838.987.113', true, 2, 2, NULL, NULL, NULL, NULL),
(78, 'E.M.F COMERCIO EXP. IMP. LTDA', NULL, 'FAZ. CACHOEIRINHA', NULL, NULL, NULL, 'ALBERTINA', 'ALBERTINA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: MARQUINHO', '19.658.020/0001-82', NULL, '914.434.054.0070', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1317, 'Ecom Japan Ltd.', 'Ecom Japan Ltd.', '6F Kinsan Bldg.', '4-1-21 Nihonbashi Muromachi', '103-0022 Tokyo, Japan.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(951, 'ED&F MAN BRASIL S/A', 'VOLCAFE', 'PRAÇA RUI BARBOSA', '300', '309', 'CENTRO', 'UBERABA', 'UBERABA', 'MG', '28010-240', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '35.829.068/0007-58', NULL, '701.226.895.0035', true, NULL, NULL, NULL, NULL, NULL, NULL),
(81, 'ED&F MAN VOLCAFE BRASIL LTDA', 'Volcafe Santos', 'Rua Frei Gaspar,', '22', 'CJ 21/22', 'Centro', 'Santos', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '33.729.690/0031-99', '254920-0', '633.448.619.117', true, NULL, 9, NULL, NULL, NULL, NULL),
(15, 'ED&F MAN VOLCAFE BRASIL LTDA', 'VOLCAFE LTDA', 'Av. Presidente Tancredo Neves', '1474', NULL, NULL, 'Caratinga', NULL, 'MG', '35300-101', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'CONTATO:', '33.729.690/0018-11', NULL, '134.262.043-0102', true, NULL, 2, NULL, NULL, NULL, NULL),
(991, 'EFICO S.A.', NULL, 'IJZERLAAN 30B-2060 ANTWERPEN 6 - BELGIUN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'N.V. EFICO S.A.
EFICO
MICHEL GERMANES', NULL, NULL, NULL, false, NULL, 7, NULL, NULL, NULL, NULL),
(105, 'EISA - EMPRESA INTERAGRÍCOLA S.A', 'EISA MACHADO', 'Rodovia MG 453 KM 7', NULL, NULL, NULL, 'Machado', NULL, 'MG', '37750-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'CONTATO: BIRA', '62.356.878/0048-85', NULL, '707.711.273-0580', true, NULL, 2, NULL, NULL, NULL, NULL),
(6, 'EISA - EMPRESA INTERAGRÍCOLA S.A', 'EISA', 'Rua do Comercio do cafe', '342', NULL, '.', 'Varginha', NULL, 'MG', '37026-530', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '62.356.878/0039-94', NULL, '707.711.273.0415', true, NULL, 2, NULL, NULL, NULL, NULL),
(973, 'EISA-EMPRESA INTERAGRICOLA S/A', 'EISA -  ARAGUARI', 'RUA BRASILIA', '300', 'SALA 01', 'AMORIM', 'ARAGUARI', NULL, 'MG', NULL, '34-32427677', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '62.356.878/0027-50', NULL, '481.711.273-03-54', true, NULL, 2, NULL, NULL, NULL, NULL),
(1174, 'EISA-EMPRESA INTERAGRICOLA S/A', 'Eisa', 'Av. Barao do Rio Branco', '194', NULL, NULL, 'Manhuaçu', NULL, 'MG', NULL, '33) 3331-1546', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '62.356.878 /0011 – 9', NULL, '394.711273.02-31', true, 2, 2, NULL, NULL, NULL, NULL),
(998, 'EKAF-IND.NAZIONALE DEL CAFFE', NULL, 'VIA GRAMSCI 27-16010 MANESSENOGENOVA - ITALY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'EKAF-IND.NAZIONALE DEL CAFFE
EKAF
C.I.C.E.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(895, 'EPS - CORRETORA DE MERCADORIAS LTDA', 'EPS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(897, 'ESPLANADA COM. REP. DE CAFÉ LTDA', 'ESPL', 'ESTRADA VICINAL - STO ANTONIO DO JARDIM A SÃO JOÃO', 'DA BOA', 'VISTA KM 01 S/N', NULL, 'STO ANTONIO DO JARDIM', 'STO ANTONIO DO JARDIM', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '04.593.983/0001-78', NULL, '628.057.829.114', true, NULL, NULL, NULL, NULL, NULL, NULL),
(343, 'ESTEVE S/A', 'ESTEVE S/A', 'AV. BARÃO DO RIO BRANCO', '194', NULL, 'BAIXADA', 'MANHUAÇU', 'MANHUAÇU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '62.356.878/0011-93', NULL, '394.711.273.0231', true, NULL, NULL, NULL, NULL, NULL, NULL),
(519, 'ESTEVE S/A', 'ESTEVE S/A', 'AVENIDA COLOMBO', '3361', NULL, NULL, 'MARINGÁ', 'MARINGÁ', 'PR', '37030-120', '(44) 222-7845', NULL, '(44)', NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '62.356.878/000383', NULL, '70.101.789-70', true, NULL, NULL, NULL, NULL, NULL, NULL),
(455, 'ESTEVE S/A', 'ESTEVE S/A', 'RUA PRUDENTE DE MORAIS', '80', NULL, NULL, 'VITÓRIA DA CONQ', 'VITÓRIA DA CONQ', 'BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '62.356.878/0019-40', NULL, '40.219.699-NO', true, NULL, NULL, NULL, NULL, NULL, NULL),
(579, 'ESTEVE S/A', 'ESTEVE S/A', 'AV. MARCIANO PIRES', '1300', NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '62.356.878/0027-50', NULL, '481.711.273.0354', true, NULL, NULL, NULL, NULL, NULL, NULL),
(557, 'ESTEVE S/A', 'ESTEVE S/A', 'AV. COLOMBO', '3361', NULL, NULL, 'MARINGÁ', 'MARINGÁ', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '62.356.878/0003-83', NULL, '70.101.789-70', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1461, 'Eugen Atté GmbH', 'Eugen Atté GmbH', 'Pickhuben 6,', NULL, NULL, NULL, '20457 Hamburg, Germany', NULL, NULL, NULL, '49 40 3786200', NULL, NULL, NULL, NULL, 'eugenatte@coffeeagents.com,', 'J', 'CL', 'CO', NULL, 'Managing directors : Otto Bertram, Michael Frontzeck,
Joachim Taubensee
AG Hamburg, HRB 58782 / VAT Nr.: DE 172 862 113', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(598, 'EUROBRASIL LTDA', 'EUROBRASIL LTDA', 'RUA FREI GASPAR', '20', 'TERREO', NULL, 'SANTOS', 'SANTOS', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '01.453.839/0001-48', '120808-9', '633.362.876-112', true, NULL, NULL, NULL, NULL, NULL, NULL),
(85, 'EUROBRASIL LTDA', 'EUROBRASIL LTDA', 'ROD. BR 491 - K 06', 'SALA A', NULL, NULL, 'S.S DO PARAISO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '01.453.839/0002-29', NULL, '647.197.912.0087', true, NULL, 2, NULL, NULL, NULL, NULL),
(985, 'EUROCA GMBH', NULL, 'SANDTORKAI 420457 HAMBURG - GERMANY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '(40) 3743755-6', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'EUROCA GMBH
EUROCA GMBH
MR. LUDWIG SPRENGEL', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(488, 'EVAIR', 'EVAIR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(103, 'EXP. E IMP. MARUBENI - COLORADO LTDA', NULL, 'RUA FREI GASPAR', '22', 'CJ 91/92', 'CENTRO', 'SANTOS', NULL, 'SP', NULL, '2195141', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '58.154.840/0001-99', NULL, '633.028.586.115', true, NULL, NULL, NULL, NULL, NULL, NULL),
(652, 'EXP. E IMP. MARUBENI COLORADO LTDA', 'MARUBENI', 'ROD. MELO PEIXOTO - BR 369 KM 88', NULL, NULL, NULL, 'CORNELIO PROCOPIO', 'CORNELIO PROCOPIO', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '76.255.926/0001-99', NULL, '534.00815-54', true, NULL, NULL, NULL, NULL, NULL, NULL),
(444, 'EXP. E IMP. MARUBENI COLORADO LTDA', NULL, 'AV. IRIRI', '339', 'SALA 2', NULL, 'SERRA', 'SERRA', 'ES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '58.154.840/0017-56', NULL, '082.074.04-6', true, NULL, NULL, NULL, NULL, NULL, NULL),
(411, 'EXP. E IMP. MARUBENI COLORADO LTDA', 'MARUBENI', 'ROD. BR 267 KM 01', '1321', 'SALA 1', 'DIST. INDL.', 'MACHADO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:
CNPJ: 58.154.840/0001-99 DA CONTA CORRENTE', '58.154.840/0004-31', NULL, '390.107.486.0018', true, NULL, NULL, NULL, NULL, NULL, NULL),
(130, 'EXP. E IMP. MARUBENI-COLORADO LTDA', 'MARUBENI', 'RUA EZZIO PUCCI', '2901', NULL, 'DIST. INDL.', 'FRANCA', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '58.154.840/0007-84', NULL, '310.041.218.115', true, NULL, NULL, NULL, NULL, NULL, NULL),
(993, 'Expocafe S.A.', NULL, 'Carrera  7 # 74 - 36 Piso - Bogota / Colombia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(727, 'EXPORTADORA DE CAFÉ CENTRO OESTE LTDA', 'EP', 'RUA BERNARDINO DE CAMPOS 2-42', NULL, NULL, NULL, 'BAURU', 'BAURU', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '04.181.421/0002-06', '209.311.998.110', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(698, 'EXPORTADORA DE CAFE TURQUESA LTDA', 'TURQUESA', 'RUA DO COMERCIO', '26', 'SALA 28', 'CENTRO', 'SANTOS', 'SANTOS', 'SP', NULL, '3219-1276', NULL, '3219-8412', NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(469, 'EXPORTADORA POÇOS DE CALDAS LTDA', 'EXP. POÇOS', 'RUA PIAUI', '129', NULL, NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 'MG', '37701-024', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: CRISTIANO OTTONI', '04.935.791/0001-00', NULL, '518.169.029-0018', true, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'EXPRINSUL COMERCIO EXTERIOR LTDA.', 'EXPRINSUL', 'PRAÇA CHAMPAGNAT', '29', '10° ANDAR S101', 'CENTRO', 'VARGINHA', 'VARGINHA', 'MG', '37.002-150', '(35) 2191112', NULL, '(35) 2191512', NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: ZE CARLOS', '86.431.889/0001-87', NULL, '707.877.445-0035', true, NULL, NULL, NULL, NULL, NULL, NULL),
(490, 'F.S.A  ( AMOCA )', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(1351, 'Falcon Coffees Limited', 'Falcon Coffees', 'The Candlemakers,', 'West Street, Lewes', NULL, 'East Sussex -', 'BN7 2NZ /', 'United Kingdom', NULL, NULL, '+44 1273 476 28', NULL, '+44 1273 376 83', NULL, NULL, 'coffee@falconcoffees.com', 'J', 'CL', 'CO', NULL, 'Falcon Coffees Limited
The Candlemakers
West Street, Lewes
East Sussex - BN7 2NZ
United Kingdom

Tel: (+44) 1273 476289

Contact: Mr. Matt Horsbrugh
               Mr. Marek Glowa', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(491, 'FAZENDA FORTALEZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(811, 'FAZENDA SANTA FÉ', 'STA', NULL, NULL, NULL, NULL, NULL, NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(878, 'FAZENDA SÃO PEDRO', 'CERTRA COFFEE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1009, 'FINAGRA (UK) LTD', NULL, 'EUROPE HOUSE WORLD TRADE CENTRE LONDON E1 9AAENGLA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FAX 44171481012', NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'FINAGRA (UK) LTD
FINAGRA
DAVID MARGULIES/PHIL MUNDEN', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(871, 'FORTALEZA IND. E COM.DE EXPORTAÇÃO DE CAFÉ', 'FORTALEZA', 'Rua Pinto Ribeiro, 759', NULL, NULL, NULL, 'S.Sebastiao do Paraiso', NULL, 'MG', '37960-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1006, 'FRELLSEN KAFFE', NULL, 'INDUSTRIVEJ 144000 ROSKILDEDENMARK', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '45 46757300', NULL, NULL, NULL, NULL, NULL, 'J', NULL, 'CO', NULL, 'FRELLSEN KAFFE.
FRELLSEN KAFFE
MR. CLAUS FRELLSEN


NORDEA BANK
Registration number: 2232
Account number 0280300004
Swift: NDEA DKKK
IBAN: DK2320000280300004', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL);
