-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(408, 'DIRCEU APARECIDO PIOVESAN', NULL, 'FAZ. SANTA BÁRBARA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '974.777.458-53', '431/2012', true, NULL, NULL, NULL, NULL, NULL, NULL),
(431, 'DIRCEU APARECIDO PIOVEZAN', NULL, 'FAZ. NOSSA SENHORA DA ABADIA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '974.777.458-53', '431/2517', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1243, 'DIVINO GARCIA MAIA E OUTRO', 'D I V I N O G A RC I A M A I A E O U T RO', 'Sitio Bela Vista', 's/n', NULL, NULL, 'Santo Antonio da Alegria', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '10.143.104/0001-09', NULL, '627.062.076.119', true, 2, 2, NULL, NULL, NULL, NULL),
(822, 'DONISETE BERMUDES & OUTROS', 'DONI', 'FAZENDA PRIMAVERA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '308.803.359-04', '481/3553', true, NULL, NULL, NULL, NULL, NULL, NULL),
(435, 'DORICO JOSÉ DA SILVA', NULL, 'FAZ. RANCHARIA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '135.897.509-44', '431/0869', true, NULL, NULL, NULL, NULL, NULL, NULL),
(655, 'DORIVAL VIEIRA DE AGUIAR E OUTRO', NULL, 'FAZ. CHACARA VIEIRA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '617.743.249-20', '564/0614', true, NULL, NULL, NULL, NULL, NULL, NULL),
(846, 'DOUGLAS BRASILEIRO', 'DOUGLAS', NULL, NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(279, 'DOUGLAS RAMOS GIMENES', NULL, 'FAZ. ESTRELA', NULL, NULL, NULL, 'ESTRELA DO SUL', 'ESTRELA DO SUL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '614.489.408-00', '248/1023', true, NULL, NULL, NULL, NULL, NULL, NULL),
(280, 'DULCILIO PERGO', 'DULCILIO PERGO', 'FAZ. SANTA JULIA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '108.368.969-04', '564/0597', true, NULL, NULL, NULL, NULL, NULL, NULL),
(228, 'E.M.F. COM. EXP. E IMP. LTDA', NULL, 'RUA GOV. PEDRO DE TOLEDO', '220', NULL, 'MONTE NEGRO', 'ESP. SANTO DO P', 'ESP. SANTO DO P', 'SP', '13.990-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: MARQUNHO', '19.658.020/0002-63', NULL, '530.023.402.117', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1401, 'ED&F MAN Volcafe Brasil Ltda', 'Volcafe Brasil LTDA', 'Av. Nossa Senhora dos Navegantes, 675', NULL, NULL, 'Enseada do Suá,', 'Vitoria - ES', NULL, NULL, '29050-912', '27 3026-4347', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Bruno Forzza Sarcinelli
Comercial Director
  
ED&F MAN Volcafe Brasil Ltda
Member of ED&F MAN Coffee Division
29050-912 - Avenida Nossa Senhora dos Navegantes, 675 - Sala 1401/09
Enseada do Suá - Vitória - ES - Brasil
Office:  +55 27 3227-1456 /+55 27 3089-2416  Mobile: +55 27 9 9982-1529
bforzza@volcafe.com.br  Skype: bruno.forzza', '33.729.690/003-35', '3071-3', '080.247.52-0', true, 7, 7, NULL, NULL, NULL, NULL),
(834, 'EDMAR LOPES', 'ARAPONGA', NULL, NULL, NULL, NULL, 'ARAPONGA', 'ARAPONGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1648, 'EDNA MIEKO KATO DAI E OUTROS', 'EDNA MIEKO', 'Fzenda Nossa Senhora Mediugorie', NULL, NULL, NULL, 'Araxa', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '883.478.006-00', '001907954-0013', true, 2, 2, NULL, NULL, NULL, NULL),
(514, 'EDSON LUIS CARDOSO PEREIRA', NULL, 'FAZ. QUATRO IRMÃS', NULL, NULL, NULL, 'COROMANDEL', 'COROMANDEL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '239.501.450-87', '193/3121', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1756, 'EDU LEANDRO MELO', 'EDU LEANDRO MELO', 'Faz. Espigao do Palmital', NULL, NULL, NULL, 'Pratinha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '102.628.016-80', '001.889.121-0099', true, 2, 2, NULL, NULL, NULL, NULL),
(931, 'EDUARDO BARBOSA MARRA', 'MARRA', 'FAZ. SANTO ANTONIO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '807.772.366-72', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(179, 'EDUARDO EUSTÁQUIO DE ANDRADE E OUTROS', 'EDUARDO', 'FAZ. LAGOA SECA/SOARES', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '177.336.426-04', '143/0888', true, NULL, NULL, NULL, NULL, NULL, NULL),
(180, 'EDUARDO EUSTÁQUIO DE ANDRADE E OUTROS', NULL, 'FAZ. CÓRREGO DO SÃO BENTO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(182, 'EDUARDO EUSTÁQUIO DE ANDRADE E OUTROS', NULL, 'FAZ. SÃO BENTO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '177.336.426-04', '143/0886', true, NULL, NULL, NULL, NULL, NULL, NULL),
(132, 'EDUARDO EUSTÁQUIO DE ANDRADE E/OU', NULL, 'FAZ. CUSCUZEIRO-CAMPO DO MEIO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, '(34) 8512455', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ISMAEL', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(276, 'EDUARDO EUSTÁQUIO DE ANDRADE E/OU', NULL, 'FAZ. SÃO SILVESTRE', NULL, NULL, NULL, 'SERRA DO SALITR', 'SERRA DO SALITR', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE BROS', NULL, '177.336.426-04', '667/1527', true, NULL, NULL, NULL, NULL, NULL, NULL),
(181, 'EDUARDO EUSTÁQUIO DE ANDRADE EOUTROS', NULL, 'FAZ. SÃO BENTO / LENHEIROS', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '177.336.426-04', '143/0882', true, NULL, NULL, NULL, NULL, NULL, NULL),
(593, 'EDUARDO LANGONI PENA', NULL, 'FAZ. PIRAPITINGA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', 'CONTATO: AMOCA', NULL, NULL, '491.398.516-72', '431/0989', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1610, 'EDUARDO REIS CHAVES', 'EDUARDO REIS CHAVES', 'Fazenda Ouro Verde', NULL, NULL, NULL, 'Coqueiral', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '779.226.546-34', '001.503.380-0078', true, 2, 2, NULL, NULL, NULL, NULL),
(1649, 'EDUARDO ROXO NOBRE DIAS E OUTROS', 'EDUARDO ROXO NOBRE DIAS E OUTROS', 'Fazenda do Mirante', NULL, NULL, NULL, 'Ibia', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '379.681.408-54', '003090925-0065', true, 2, 2, NULL, NULL, NULL, NULL),
(404, 'EDVALDO HARUO HARADA', NULL, 'FAZ. PARANÁ', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '680.724.906-30', '431/2250', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1187, 'Efico NV/SA', 'Efico', 'Italielei', '181', '2000 Antwerpen', NULL, NULL, 'Belgium', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(1685, 'ELCI BATISTA DOS SANTOS', 'ELCI BATISTA DOS SANTOS', 'Faz. dos Santos', NULL, NULL, NULL, 'Pratinha', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '737.047.506-97', '001.370.925-009', true, 2, 2, NULL, NULL, NULL, NULL),
(799, 'ELCI GONÇALVES DE OLIVEIRA', 'ELCI', 'FAZ. VIEIRA', NULL, NULL, NULL, 'BAMBUI', 'BAMBUI', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COPACAFE', NULL, '326.768.836-15', '051/2097', true, NULL, NULL, NULL, NULL, NULL, NULL),
(647, 'ELIAS CARLO HOTTES PEREIRA', NULL, 'FAZ. SERRA NEGRA DO CORREGO FEIO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '375.012.917-72', '481/2493', true, NULL, NULL, NULL, NULL, NULL, NULL),
(710, 'ELIAS FERNANDES DA SILVA', 'ELIAS', 'SITIO SÃO JOÃO', NULL, NULL, 'BORGES', 'CORUMBATAI DO SUL', 'CORUMBATAI DO SUL', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '485.773.089-87', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1277, 'ELIO TREVISOLI', 'ELIO', 'Faz. Faria', NULL, NULL, NULL, 'Lavras', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '303.016.968-53', '001.282.753-0104', true, 2, 2, NULL, NULL, NULL, NULL),
(544, 'ELISABETE ALVES DE MELO E/OUTRO', NULL, 'FAZ. SAO BERNARDO', NULL, NULL, NULL, NULL, NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ADAILTON', NULL, '255.631.066-91', '481/4889', true, NULL, NULL, NULL, NULL, NULL, NULL),
(418, 'ELISABETH MITIKO HARADA SATO', NULL, 'FAZ. CREOULOS', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '912.074.796-91', '431/2501', true, NULL, NULL, NULL, NULL, NULL, NULL),
(723, 'ELMIRO RESENDE CUNHA', 'CUBH', 'FAZ. CHACARÁ CLÁUDIA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '004.663.956-04', '431/2946', true, NULL, NULL, NULL, NULL, NULL, NULL),
(659, 'ELMIRO RESENDE CUNHA', NULL, 'FAZ. LAGO AZUL', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '004.663.956-04', '431/0171', true, NULL, NULL, NULL, NULL, NULL, NULL),
(553, 'EMERSON DE MOURA BONTEMPO', NULL, 'FAZ. SANTA CECILIA', NULL, NULL, NULL, 'CAM. PARANAIBA', 'CAM. PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AGROP. MVR', NULL, '914.272.906-87', '143/2889', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1712, 'EMERSON HENRIQUE MESSIAS CHAVES', 'EMERSON HENRIQUE MESSIAS CHAVES', 'Faz. Mantibio', NULL, NULL, NULL, 'Medeiros', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '068.206.526-90', '0020.112.150-098', true, 2, 2, NULL, NULL, NULL, NULL),
(356, 'EMILIO PICININI', 'EMILIO PICININI', 'FAZ. TRÊS IRMÃOS-AV. JOSÉ CARNEIRO DE MENDONÇA', '293', NULL, NULL, 'COROMANDEL', 'COROMANDEL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: SABANA TRADING', NULL, '726.161.218-91', '193/1285', true, NULL, NULL, NULL, NULL, NULL, NULL),
(628, 'EMILIO RICARDO MASS', NULL, 'FAZ. ESTRELA', NULL, NULL, NULL, 'ESTRELA DO SUL', 'ESTRELA DO SUL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '449.905.379-04', '248/1100', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1138, 'Empreendimentos Market Share Export LTDA', 'Market Share', 'Rua José Ricardo', '51', 'room 42', 'Centro', 'Santos', 'Brasil', 'SP', '11010-190', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'margareth@marketexport.com.br - Margareth Lima
real_corretora@hotmail.com - Antonio Morine', '03.708.642/0001-38', '191.317-0', '633.702.170.111', true, 7, 7, NULL, NULL, NULL, NULL),
(988, 'Empreendimentos Market Share Export Ltda.', 'Market Share', 'Rua  José Ricardo', '51', 'room 42', 'Centro', 'Santos', 'Brazil', 'SP', '11010-190', '32194255', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'margareth@marketexport.com.br - Margareth Lima
real_corretora@hotmail.com - Antonio Morine', '03.708.642/0001-38', NULL, '633.702.170.111', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1447, 'Engelhart Commodities Trading Partners', 'ECTP (Ex. BTG Pactual)', 'Rua Frei Gaspar,', '24', '6º floor room 61/62', NULL, 'Santos/SP', NULL, NULL, '11010-090', '55 13 3213 2855', NULL, NULL, NULL, NULL, NULL, 'J', 'RE', 'VE', NULL, '+55 13 98131 0690
Rafael.Martins@ectp.com
ectp.com


Engelhart Commodities
Route de Pre-Bois 29
Case Postale 149
1215 Geneva 15 Depot
Switzerland



Engelhart CTP US LLC
400 Atlantic Street  , 11th floor
Stamford, Ct 06901
Michael.Kelly@ectp.com', NULL, NULL, NULL, true, 7, 4, NULL, NULL, NULL, NULL),
(1365, 'EREMITA BARCELOS VELOSO', 'EREMITA BARCELOS VELOSO', 'FAZ. BERRADOR - RODOVIA BR 354 KM 273', NULL, NULL, NULL, 'CARMO DO PARANAÍBA', NULL, 'MG', '38840-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '037.219.266-17', '001382076.00-75', true, 2, 2, NULL, NULL, NULL, NULL),
(137, 'ERLEY NUNES COELHO', NULL, 'FAZ. MORRO GRANDE', NULL, NULL, NULL, 'CASA GRANDE', 'CASA GRANDE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '155.967.106-87', '149/0118', true, NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'ERNESTO BARBOSA & FILHOS LTDA.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: DAVID GAGO', NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(717, 'ERNESTO BARBOSA NETO', 'ERNEST', 'SITIO JAGUARI ESTRADA IBITIURA/ANDRADAS', NULL, NULL, NULL, 'ANDRADAS', 'ANDRADAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'QUALICAFEX', NULL, '005.234.616-15', '026/0448', true, NULL, NULL, NULL, NULL, NULL, NULL),
(699, 'ERNESTO CARVALHO DIAS', 'ERNESTO', 'FAZ. SÃO FRANCISCO', NULL, NULL, NULL, 'BAMBUI', 'BAMBUI', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '005.282.266-49', '051/0220', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1655, 'ERON VALERIANO DOMINGOS', 'ERON VALERIANO DOMINGOS', 'Fazenda Santa Tereza', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '052.637.416-00', '001279396-0055', true, 2, 2, NULL, NULL, NULL, NULL),
(559, 'ESPÓLIO AGEU GARCIA DE DEUS', NULL, 'FAZ. CABECEIRA DA CACHOEIRA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '393.955.616-53', '143/2837', true, NULL, NULL, NULL, NULL, NULL, NULL);
