-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(381, 'HAMILTON JOSÉ PINTO', NULL, 'FAZ. CACHOEIRA', NULL, NULL, NULL, 'RIO PARANAÍBA', 'RIO PARANAÍBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: QUENIO', NULL, '122.491.146-67', '555/3039', true, NULL, NULL, NULL, NULL, NULL, NULL),
(591, 'HARUMI SHIMADA', 'HARUMI SHIMADA', 'FAZ. VISTA ALEGRE', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', 'CONTATO: ACAIA', NULL, NULL, '449.959.039-68', '481/4401', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1484, 'HATUNE MAMOSE', 'HATUNE MAMOSE', 'Faz. Pastao III', NULL, NULL, NULL, 'Monte Carmelo', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CORRETOR: PAULINHO', NULL, '025.731.299-42', '002615641-0066', true, 2, 2, NULL, NULL, NULL, NULL),
(1621, 'HEBERT HERMOGENES SOARES ROCHA', 'HEBERT HERMOGENES SOARES ROCHA', 'Faz. Jararaca', NULL, NULL, NULL, 'S.S. Paraiso', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '102.637.816-82', '003112590.00-24', true, 2, 2, NULL, NULL, NULL, NULL),
(428, 'HEITOR JOSE RODIRGUES', NULL, 'FAZ. CHAPADÃO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ISMAEL', NULL, '359.391.841-20', '143/2194', true, NULL, NULL, NULL, NULL, NULL, NULL),
(284, 'HELENA PINGNATTI RICCI E OUTRO', NULL, 'FAZ. SANTA MARGARIDA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '652.357.629-91', '431/2427', true, NULL, NULL, NULL, NULL, NULL, NULL),
(679, 'HELIO BERMUDES', 'HELIO', 'FAZ. PRIMAVERA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '198.933.889-53', '481/3553', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1713, 'HELVECIO FARIA DE OLIVEIRA', 'HELVECIO FARIA DE OLIVEIRA', 'Faz. Boa Vista', NULL, NULL, NULL, 'Tapirai', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '938.108.736-91', '001.428.593-0072', true, 2, 2, NULL, NULL, NULL, NULL),
(611, 'HEMERSON BOVI', 'HEMERSON BOVI', 'FAZ. CHACARÁ DAS MANGUEIRAS', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '776.642.306-59', '431/2756', true, NULL, NULL, NULL, NULL, NULL, NULL),
(457, 'HEMERSON BOVI', 'HEMERSON BOVI', 'FAZ. CHACARÁ OLHOS D''ÁGUA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '776.642.306-59', '431/2037', true, NULL, NULL, NULL, NULL, NULL, NULL),
(525, 'HENRIQUE D. CAMBRAIA', NULL, 'FAZ. SAMAMBAIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1748, 'HERMANDO JOSE FERREIRA', 'HERMANDO JOSE FERREIRA', 'Faz. Perobas', NULL, NULL, NULL, 'Indaizainho', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '048.867.796-38', '001.376.133-0049', true, 2, 2, NULL, NULL, NULL, NULL),
(597, 'HIROKO SHIMADA', 'HIROKO SHIMADA', NULL, NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ACAIA', NULL, '029.349.886-51', '481/1946', true, NULL, NULL, NULL, NULL, NULL, NULL),
(439, 'HITOSE MAMOSE', 'HITOSE MAMOSE', 'FAZ. PASTÃO 2', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '011.957.009-20', '431/0559', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1249, 'HUGO FELIZALI DE BRITO', 'HUGO', NULL, NULL, NULL, NULL, 'TRES PONTAS', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 2, 2, NULL, NULL, NULL, NULL),
(704, 'HUGO PASSOS SWERTS JUNIOR', 'HUGO', 'FAZ. SÃO GERALDO', NULL, NULL, NULL, 'VARGINHA', 'VARGINHA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '454.883.048-00', '707/0425', true, NULL, NULL, NULL, NULL, NULL, NULL),
(644, 'HUGO PASSOS SWERTS JUNIOR', 'HUGO', 'FAZ. SANTA CRUZ', NULL, NULL, NULL, 'VARGINHA', 'VARGINHA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '454.883.048-00', '707/0426', false, NULL, 8, NULL, NULL, NULL, NULL),
(259, 'HUMBERTO CARDOSO', 'HUMBERTO', 'FAZENDA ARARAS', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA
ESTADO CIVIL: DESQUITADO', 'M-754.320', '104.316.086-87', '431/0527', true, NULL, NULL, NULL, NULL, NULL, NULL),
(943, 'HUMBERTO PASCUINI', 'PASCUINI', 'SÍTIO RECREIO NOSSA SENHORA DO CARMO', NULL, NULL, NULL, 'ESP. STO DO PINHAL', 'ESP. STO DO PINHAL', 'SP', '13990-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'QUALICAFEX', '08.238.543/0001-53', NULL, '530.971.114', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1036, 'ICATU COM. EXP. E IMP. LTDA.', NULL, 'Rua Governador Pedro de Toledo', '230A', NULL, NULL, 'Esp.Sto do Pinhal', 'Brasil', 'SP', '13990-000', '19 3661-9066', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '43.614.536/0001-00', NULL, '530.010.931.118', true, NULL, 4, NULL, NULL, NULL, NULL),
(724, 'IEDA CRISTINA DE QUEIROZ PEREIRA E OUTRO', 'IEDA', 'FAZ. SANTA BARBARA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '835.423.379-00', '431/2817', true, NULL, NULL, NULL, NULL, NULL, NULL),
(312, 'IGNÊS CLAPPIS DE FREITAS', NULL, 'FAZ. PAULISTA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '042.116.176-05', '431/0372', true, NULL, NULL, NULL, NULL, NULL, NULL),
(912, 'ILHA CAFÉ COM.EXP.IMP.LTDA', 'ILHA', 'RUA JOSÉ MARIA WHITACKER', '50', NULL, NULL, 'ESP. STO DO PINHAL', 'ESP. STO DO PINHAL', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'QUALICAFEX', '540.094/0001-91', NULL, '530.584.388-34', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1497, 'Inacio Carlos Urban', 'Inacio Carlos Urban', 'Fazenda Rio Brilhante Café', NULL, NULL, NULL, 'Coromandel', NULL, 'MG', '38550-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '194.096.130-00', '001112255.04 - 64', false, 2, 7, NULL, NULL, NULL, NULL),
(1475, 'Inacio Carlos Urban e outros', 'Inacio Carlos Urban', 'Fazenda Rio Brilhante Café', NULL, 'Rodovia MG 88, KM 2', 'Zona Rural', 'Coromandel/MG - Brazil', NULL, NULL, '38.550-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'Inacio Carlos Urban       
End: Fazenda Rio Brilhante Café  
Rodovia MG 88, KM 25 á direita 
Município: Coromandel - MG    
Bairro/Distrito: Zona Rural    
CPF : 194.096.130-00    
Inscrição Estadual : 002935594.06-70    
Cep....: 38.550-000', 'CPF : 194.096.130-00', NULL, '002935594.06-70', true, 7, 2, NULL, NULL, NULL, NULL),
(779, 'INACIO MOREIRA GARCIA', 'COPACAFE', 'SITIO INALI PERDÕES', NULL, NULL, NULL, 'PERDÕES', 'PERDÕES', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '060.075.116-34', '499/0497', true, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'INAGRO - INTEGRACAO AGROPECUARIA S/A', NULL, 'FAZ. BOA VISTA', NULL, NULL, NULL, 'BAMBUÍ', 'BAMBUÍ', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: SR. MURILO', '22.618.508/0003-52', 'IPR: 051/0875', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(128, 'INAGRO- INTEGRAÇÃO AGROPECUARIA S/A', NULL, 'FAZENDA SANTA MARIA', NULL, NULL, NULL, 'BOM SUCESSO', 'BOM SUCESSO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: ERLEY', '22.618.508/0007-86', NULL, '080/0836', true, NULL, NULL, NULL, NULL, NULL, NULL),
(551, 'INCOFEX', 'INCOFEX', 'ROD. VIÇOSA -PORTO FIRME KM 04', NULL, NULL, 'COLÔNIA VAZ DE MELLO', 'VIÇOSA', 'VIÇOSA', 'MG', '36570-000', '(31)3891-9559', NULL, '(31)3891-9339', NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(354, 'IND. E COM. DE CAFÉ "2 P "LTDA', NULL, 'RUA CORONEL DIOGO', '80', NULL, NULL, 'MOCOCA', 'MOCOCA', 'SP', '13.730-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(361, 'IND. E COM. DE CAFÉ E CEREAIS MOURÃO LTDA', NULL, 'RUA JOSÉ DO PATROCÍNIO', '2061', NULL, 'CENTRO', 'CACOAL', 'CACOAL', 'RO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: NICCHIO SOBRINHO', '02.951.417/0001-65', NULL, '51545-1', true, NULL, NULL, NULL, NULL, NULL, NULL),
(657, 'INÊS ZOLI TASSINARI', NULL, 'FAZ. SÃO FRANCISCO', NULL, NULL, NULL, NULL, NULL, 'RJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1754, 'INTENS MONTEIRO VILELA', 'INTENS MONTEIRO VILELA', 'Faz. Acampamento', NULL, NULL, NULL, 'Campos Altos', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '073.355.476-87', '001.408.622-0083', true, 2, 2, NULL, NULL, NULL, NULL),
(1437, 'Interbrasil Coffee Ltda', 'Interbrasil Coffee Ltda', '368 Capitão Carlos Henringer Avenue', NULL, NULL, NULL, 'Alto Jequitibá, MG / Brazil', NULL, NULL, '36976-000', '(31) 3308-6226', NULL, NULL, NULL, NULL, 'andrea.franklin@interbrasilcoffee.com', 'J', 'CL', 'VE', NULL, 'Contact Person: ANDREA FRANKLIN', '04.565.932/0001-32', NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(156, 'INTERTECH COMERCIAL EXPORTADORA LTDA', NULL, 'RUA PINTO RIBEIRO', '759', NULL, 'CENTRO', 'SÃO SEBASTIÃO D', 'SÃO SEBASTIÃO D', 'MG', '37.950-000', '(35) 5318099', NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: ALEXANDRE', '71.487.490/0001-40', NULL, '651.875.250.0050', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1077, 'Intertech Imp. e Com. LTDA', 'Intertech', 'Rua Pinto Ribeiro', '759', NULL, NULL, 'São Sebastião do Paraíso', NULL, 'MG', '37960-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Nota fiscal 
Fortaleza Ind. Com. e Exportação de café Ltda.
Rua Alves de Figueiredo, 441 centro São Tomas de Aquino - MG
CNPJ: 71.487.490/0001-40
I.E: 651.875250.0050
CEP: 37960-000

Correspondência: Rua Pinto Ribeiro, 759 - centro S.S.Paraiso - MG
CEP: 37950-000', '71.487.490/0001-40', NULL, '651.875.250.0050', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1117, 'Interway Coffee Division.', 'Interway', 'Av. Princesa do Sul', '470', NULL, NULL, 'Varginha - MG', NULL, 'MG', '37962-180', '(35) 3629-7550', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'AIDC Tecnologia Ltda

Dados para emissão da nota:
AIDC Teconologia Ltda
Av. Princesa do Sul, 470 - sls. 207/208 - jardim Andere
37.062.180  Varginha - MG
CNPJ: 07.500.596/0002-19
IE: 324.356.378-0178
Inscrição Municipal: 17.959
marcos.ikeda@primeinterway.com.br

AIDC Tecnologia Ltda
Rua Frederico Leite, 150 Sala B3
Porto Velho - Itajuba - MG
Cep.: 37501-007', NULL, NULL, NULL, true, NULL, 4, NULL, NULL, NULL, NULL),
(201, 'Ipanema Agrícola S/A', 'Fazenda Capoeirinha', 'Rodovia Alfenas / Machado - BR 179', 'KM 13', 'Faz. Capoeirinha', NULL, 'Alfenas', NULL, 'MG', '37132-440', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '42.135.913/0008-31', NULL, '001403560.03-93', true, NULL, 2, NULL, NULL, NULL, NULL),
(8, 'Ipanema Agrícola S/A', 'Fazenda Conquista', 'Rodovia - BR 369 - KM 175', NULL, 'Faz. Conquista', NULL, 'Alfenas', NULL, 'MG', '37.137-688', '(35) 3299-2700', NULL, '35-3299-2727', NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: MARCIO/GLAUCO', '42.135.913/0002-46', NULL, '001403560.00-59', true, NULL, 9, NULL, NULL, NULL, NULL),
(1178, 'IPANEMA COMERCIAL E EXPORTADORA S/A', 'FAZENDA CONQUISTA', 'RODOVIA BR 369 KM 175  -  FAZENDA CONQUISTA', NULL, NULL, NULL, 'Alfenas', NULL, 'MG', '37135-058', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '01.983.074/0003-10', NULL, '016697825.01-88', true, 2, 2, NULL, NULL, NULL, NULL),
(1094, 'Ipanema Trading Co. Inc.', 'Ipanema Trading', 'Citico Building Wickhams', NULL, 'Cay PO BOX 662', NULL, 'Tortola', 'British Virgin Island', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, 7, NULL, NULL, NULL, NULL),
(347, 'IPOJUCAN FORTUNATO B. FERNANDES', NULL, 'FAZ. CAIXETA - BREJE COMPRIDO', NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AGROALPA', NULL, '197.580.656-53', '480/5049', true, NULL, NULL, NULL, NULL, NULL, NULL),
(638, 'IRACY BORDIGNON TORATTI E OUTROS', NULL, 'FAZ. CHAPADÃO DE FERRO CAPÃO MADEIRA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '172.867.628-26', '481/6135', true, NULL, NULL, NULL, NULL, NULL, NULL),
(964, 'IRAREMA AGRICOLA LTDA', 'IRAREMA', 'ESTRADA MUNICIPAL S.S.GRAMA/POÇOS DE CALDAS', 'KM 26', NULL, NULL, 'S.S.GRAMA', 'S.S.GRAMA', 'SP', '13790-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '07.161.873/0001-25', NULL, '655.068.590.119', true, NULL, 2, NULL, NULL, NULL, NULL),
(728, 'IRENE JANUSSI FRANCO  E OUTROS', 'IRENE', 'FAZ. PLANALTO', NULL, NULL, NULL, 'NOVA REZENDE', 'NOVA REZENDE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '965.386.008-91', '451/0021', true, NULL, NULL, NULL, NULL, NULL, NULL),
(733, 'IRENE JANUSSI FRANCO E OUTROS', 'IRENE', 'FAZ. BOA VISTA', NULL, NULL, NULL, 'PIRASSUNUNGA', 'PIRASSUNUNGA', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'QUALICAFEX', NULL, '965.386.008-91', '053.603.400/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(656, 'ISMAEL JOSÉ DE ANDRADE E OU', NULL, 'FAZ. PAIOLINHO', NULL, NULL, NULL, 'SERRA DO SALITR', 'SERRA DO SALITR', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '385.147.456-20', '667/2139', true, NULL, NULL, NULL, NULL, NULL, NULL),
(249, 'ISMAEL JOSÉ DE ANDRADE E OU', NULL, 'FAZ. PALMITAL', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(76, 'ISMAEL JOSE DE ANDRADE E OUTRO', NULL, 'FAZ. ARAGAO', NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(177, 'ISMAEL JOSÉ DE ANDRADE E OUTROS', NULL, 'FAZ. CAPIM BRANCO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, '(34) 8512455', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '385.147.456-20', '143/0885', true, NULL, NULL, NULL, NULL, NULL, NULL);
