-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(1333, 'FERNANDO VIEIRA VINHAL', 'FERNANDO VIEIRA VINHAL', 'Faz. Bravinhos / Fonseca', NULL, NULL, NULL, 'Carmo do Paranaíba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '999.819.206-49', '001.321041-0054', true, 2, 2, NULL, NULL, NULL, NULL),
(205, 'FERREIRA COMÉRCIO DE CAFÉ LTDA', NULL, 'AV. BARÃO DO RIO BRANCO', '353', 'SALA 4A', NULL, 'MANHUAÇÚ', 'MANHUAÇÚ', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: INCOFEX', '02.571.512/0001-33', NULL, '394.757.973.0079', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1257, 'FF SUPLICY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 16, 16, NULL, NULL, NULL, NULL),
(1297, 'FLAVIO DINIZ JUNQUEIRA E OUTROS', 'FLAVIO DINIZ JUNQUEIRA E OUTROS', 'FAZENDA NOVA ESPERANÇA', NULL, NULL, NULL, 'ORLANDIA', 'BRASIL', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CPF.: 744.132.958-20', '08.175.712/0001-53', NULL, '491.091.569.110', true, 16, 16, NULL, NULL, NULL, NULL),
(526, 'FLAVIO MAZZARO', 'FLAVIO MAZZARO', 'RUA ALFREDO BATTINI', '482', NULL, 'JARDIM SAN REMO', 'CURITIBA', 'CURITIBA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '238.982.409-1', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(852, 'FLORIDA COMERCIO EXTERIOR LTDA', 'FLORIDA', 'RUA PINTO DIAS', '97', NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'ACAIA', '04.694.219/0001-99', NULL, '481.182721-0090', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1774, 'FMR Cafés - Comercio Importação e Exportação LTDA', 'FMR Cafés', 'Rodovia SP 342 KM, 204 room 6', NULL, 'Espirito Santo do Pinhal - SP/Brazil', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'FMR Cafés - Comercio Importação e Exportação ltda 
Rodovia SP 342 Km, 204 Sala 6
Espirito Santo do Pinhal - SP               
Cep:13.990-000
CNPJ: 28.877.872/0001-51                  
I.E:530.057.690.119

fmrcafe@fmrcafe.com.br
felipe@fmrcafe.com.br
fernando@fmrcafe.com.br
gaspari@fmrcafe.com.br', '28.877.872/0001-51', NULL, '530.057.690.119', true, 7, 7, NULL, NULL, NULL, NULL),
(1711, 'FRANCISCO JOSE MARTINS DE CARVALHO', 'FRANCISCO JOSE MARTINS DE CARVALHO', 'Faz. Cedro', NULL, NULL, NULL, 'Corrego danta', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '643.919.736-34', '002.071.451-0076', true, 2, 2, NULL, NULL, NULL, NULL),
(583, 'FRANCISCO KAZUO MIZOTE', NULL, 'FAZ. MIZOTE IV           RECEITA FEDERAL 2441727-0', NULL, NULL, NULL, 'BARREIRAS', 'BARREIRAS', 'BA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '330.928.269-49', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(678, 'FRANCISCO KOUJI TAKAHASHI', 'FRANCISCO', 'FAZ. SÃO FRANCISCO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '021.047.129-80', '481/518', true, NULL, NULL, NULL, NULL, NULL, NULL),
(835, 'FRANCISCO OTÁVIO LOTUFO', 'LOTUFO', NULL, NULL, NULL, NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(233, 'FRANCISCO SÉRGIO DE ASSIS', NULL, 'FAZENDA TERRA RICA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '529.560.679-15', '431/1481', true, NULL, NULL, NULL, NULL, NULL, NULL),
(154, 'FRANCISCO SÉRGIO DE ASSIS', NULL, 'FAZ. NOSSA SENHORA DO CARMO', NULL, NULL, NULL, 'IRAI DE MINAS', 'IRAI DE MINAS', 'MG', NULL, '(34) 8421966', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: L.A.G', NULL, '529.560.679-15', '316/0797', true, NULL, NULL, NULL, NULL, NULL, NULL),
(442, 'FROHLIC CAFÉ COM. IMP. EXP. LTDA', NULL, 'ROD. DO CAFÉ', '2337', NULL, 'SÃO CRISTOVÃO', 'NOVA VENÉCIA', 'NOVA VENÉCIA', 'ES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: RUDIO', '01.171.108/0001-00', NULL, '081.815.99-9', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1005, 'G. Bijdendijk B.V.', NULL, 'Molenakker 2 - NL-8077 TK Hulshorst', NULL, 'The Nertherlands', NULL, NULL, NULL, NULL, NULL, '40 378620-0', '40 37862022', NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(533, 'G. FERREIRA', 'G. FERREIRA', 'AV. BARÃO DO RIO BRANCO', '353', 'SALA 4', NULL, 'MANHUAÇU', 'MANHUAÇU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: COOP. CARATINGA', '02.252.204/0001-45', NULL, '394.109.988-0085', true, NULL, NULL, NULL, NULL, NULL, NULL),
(243, 'G.M. DA SILVA ARAUJO', NULL, 'RUA SÃO VICENTE DE PAULO', '82', NULL, 'CENTRO', 'SANTA BARBARA D', 'SANTA BARBARA D', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: CUPERTINO', '01.820.130/0001-33', NULL, '756.675.171.0099', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1478, 'GABRIEL AFONSO MEI ALVES DE OLIVEIRA E OUTRA', 'GABRIEL AFONSO', 'Faz. Bom Jesus', NULL, NULL, NULL, 'Cristais Paulistas', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '542.058.678-91', '280.054.415.111', true, 2, 2, NULL, NULL, NULL, NULL),
(152, 'Gabriel Afonso Mei Alves de Oliveira e Outra.', NULL, 'Faz. Bom Jesus, Estrada Vicinal Argemiro Leonardo', '- Km 10', NULL, 'Zona Rural', 'Cristais Paulista', NULL, 'SP', '14460-000', NULL, NULL, NULL, NULL, 'julio@labaredadocaititu.com.br;flavia@labaredaagropecuaria.com.br', NULL, 'J', 'CL', 'VE', NULL, 'Message received on December 12th, 2013.

Os dados do seller estão errados.
O Correto é Gabriel Afonso Mei Alves de Oliveira e Outra.
Fazenda Bom Jesus, Estrada Vicinal Argemiro Leonardo, Km 10
Zona Rural
Cristais Paulista/SP
CEP: 14460-000

Endereço para correspondência:
Rua Doutor Carrão, 247 - Sala 3
Franca/SP - Brasil
CEP: 14.405-324
Tel:+55(16)3702-5355

Rua Do Sol, 970
Franca - SP', '07.983.222/0001-10', NULL, '280.054.415.111', true, NULL, 2, NULL, NULL, NULL, NULL),
(1582, 'GABRIEL DOS REIS', 'GABRIEL DOS REIS', 'Fazenda Sol Nascente', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', '38970-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CONTATO: NILSON   - : nilsongs8@gmail.com', NULL, '434.118.356-72', '001511213-0008', true, 2, 2, NULL, NULL, NULL, NULL),
(342, 'GABRIEL FRANCISCO JUNQUEIRA', NULL, 'FAZ. PROVIDÊNCIA', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '168.677.426-53', '134/5847', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1675, 'GABRIEL MASINI CRISCUOLO PARREIRAS', 'GABRIEL MASINI CRISCUOLO PARREIRAS', 'Fazenda Santa Luzia', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', '38970-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '148.093.476-30', '003774287-0045', true, 2, 2, NULL, NULL, NULL, NULL),
(1559, 'Gaiola empreendimentos agropecuários Ltda', 'Gaiola empreendimentos agropecuários Ltda', 'Fazenda Santa Maria', NULL, NULL, NULL, 'Araxa', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '03.650.307/0001-26', NULL, '001442393 0048', true, 2, 2, NULL, NULL, NULL, NULL),
(437, 'GALILEU C. NEVES E MANOEL N. CARDOSO', NULL, 'FAZ. CACHOEIRA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '323.456.906-15', '431/0862', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1865, 'GALVÃO COM. E INTERMEDIAÇÃO DE COMMODITIES LTDA', 'GALVÃO COM. E INTERMEDIAÇÃO DE COMMODITIES LTDA', 'Av. Vereador João Alegre', '135', NULL, 'Bairro Sta. Terezinha', 'Campos Altos', NULL, 'MG', '38970-000', '(37)3426-3428', NULL, NULL, NULL, 'cafeeiragalvao@hotmail.com', NULL, 'J', 'CL', 'VE', NULL, NULL, '31.631.172/0001-97', NULL, '0032858500010', true, 8, 2, NULL, NULL, NULL, NULL),
(172, 'GERALDO CONGIO', 'GERALDO CONGIO', 'FAZEMDA JANGADA', NULL, NULL, NULL, 'CABO VERDE', 'CABO VERDE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: NEWTON VAZ', NULL, '028524706-91', '095/1302', true, NULL, NULL, NULL, NULL, NULL, NULL),
(926, 'GERALDO GONÇALVES SIQUEIRA', 'SIQUEIRA', 'FAZ. SANTA CECÍLIA', NULL, NULL, NULL, 'CARMO DO PARANAÍBA', 'CARMO DO PARANAÍBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COOCACER - ZE REINALDO', NULL, '266.522.776-20', '143.1785', true, NULL, NULL, NULL, NULL, NULL, NULL),
(805, 'GERALDO MAGELA  DE OLIVEIRA E OUTRO', 'GERALDO', 'FAZ. SANTA HELENA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'EXPOCACCER', NULL, '004.694.676-49', '481/5797', true, NULL, NULL, NULL, NULL, NULL, NULL),
(272, 'GILBERTO WESTIN COSENZA', NULL, 'FAZENDA SILABEL', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '107.603.266-49', '431/0633', true, NULL, NULL, NULL, NULL, NULL, NULL),
(290, 'GILMAR BARBOSA CABRAL', NULL, 'FAZ. PENEDO', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '408.072.669-49', '431/1561', true, NULL, NULL, NULL, NULL, NULL, NULL),
(823, 'GILMAR JORDAN COLOMBO', 'GILMAR', 'FAZENDA CHAPADÃO DO FERRO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '436.832.669-53', '481/7384', true, NULL, NULL, NULL, NULL, NULL, NULL),
(928, 'GILMAR TOYOKASU NITTA', 'NITTA', 'FAZ. SÃO BARTOLOMEU', NULL, NULL, NULL, 'CARMO DO PARANAÍBA', 'CARMO DO PARANAÍBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COOCACER - ZE REINALDO', NULL, '903.165.336-53', '143/4211', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1329, 'GILMAR TOYOKASU NITTA', 'GILMAR TOYOKASU NITTA', 'Faz. Sao Bartolomeu', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '903.165.336-53', '001.147611-0077', true, 2, 2, NULL, NULL, NULL, NULL),
(1609, 'GIOVANI GARCIA DE CARVALHO', 'GIOVANI GARCIA DE CARVALHO', 'Fazenda Canto Alegre', NULL, NULL, NULL, 'Coqueiral', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'SAAG', NULL, NULL, '676.799.606-82', '001.149.670-0015', true, 2, 2, NULL, NULL, NULL, NULL),
(935, 'GIOVANI MIARI BRITO', 'GIOVANI', 'FAZ. POTREIROS', NULL, NULL, NULL, 'TRÊS PONTAS', 'TRÊS PONTAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '000.361.886-20', '694/0168', true, NULL, NULL, NULL, NULL, NULL, NULL),
(376, 'GIUCAFÉ EXPORTAÇÃO E IMPORTAÇÃO LTDA', NULL, 'ROD. BR 101', 'KM 139', NULL, 'CANIVETE', 'LINHARES', 'LINHARES', 'ES', '29.900-970', '(27) 3738211', NULL, '(27) 373-8283', NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: LUIZ CLAUDIO', '31.805.823/0001-18', NULL, '081.261.96-9', true, NULL, NULL, NULL, NULL, NULL, NULL),
(351, 'GLACIR DALL''AGNOL E OUTROS', NULL, 'FAZENDA CASTELHANA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '536.598.486-20', '431/2240', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1479, 'GLOBAL COFFEE EXPORTACAO LTDA', 'GLOBAL COFFEE', 'Avenida Francisco Machado', '555', 'sala 1', NULL, 'Piumhi', NULL, 'MG', '37925-000', NULL, NULL, NULL, NULL, NULL, 'juliano@agbomsucesso.com.br', 'J', 'CL', 'VE', NULL, NULL, '20.602.521/0001-26', NULL, '0023.900-0900-76', true, 2, 2, NULL, NULL, NULL, NULL),
(1516, 'Gold Coffee Company', 'Gold Coffee Company', 'Jupiter, FL 33468', NULL, 'PO Box 719', NULL, NULL, NULL, NULL, NULL, '561-746-8110', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Mr. John Parry
goldcafe@msn.com', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(1266, 'GOLDEN ATACADISTA E EXPORTADORA DE CAFE LTDA', 'GOLDEN', 'Rua Mirandopolis', '1343', NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '08.158.699/0001-24', NULL, '001.0109.58-0060', true, 2, 2, NULL, NULL, NULL, NULL),
(913, 'Gram Cerri Com. Exp. Imp. LTDA.', 'Gram Cerri', 'Av. Juscelino Kubitschek', '333', NULL, 'Vila Gomes', 'São Sebastião da Grama -', 'Brazil', 'SP', '13.790.000', '(19) 36461780', NULL, NULL, NULL, NULL, 'gramcerri@yahoo.com.br', 'J', 'CL', 'VE', NULL, 'contact.: Mr. Fabio Augusto Massini
cel (19) 81490919', '07.416.694/0001-91', NULL, '655.068.776.112', true, NULL, 21, NULL, NULL, NULL, NULL),
(1470, 'Grano Trading Exportadora e Importadora LTDA', 'Grano Trading Exportadora e Importadora LTDA', 'Rodovia MG 188, KM 25, s/n', 'S/N', 'Zona Rural', NULL, 'Coromandel', NULL, 'MG', '38.550-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', 'Noé Francisco Bartholomei Rodrigues', 'De: Fabiana V. Boroni 
Enviada em: sexta-feira, 28 de abril de 2023 17:16

Grano''s address has been changed:
Grano Trading Exportadora e Importadora Ltda
Avenida Juscelino Kubitschek de Oliveira, 2741
Bairro Residencial Gramado
Patos de Minas/MG
CEP: 38706-215


Rabobank
Agência: 1565
CC: 3600

Old address:
Rodovia MG 188, KM 25, s/n
Zona Rural - Coromandel, MG
CEP 38.550-000

Shipper:
INACIO CARLOS URBAN
BAIRRO/DISTRITO: ZONA RURAL
MUNICIPIO: COROMANDEL - MG
END: FAZENDA RIO BRILHANTE CAFE
CNPJ/CPF: 19409613000', '03.977.522/0001-36', NULL, '349093548.00-69', false, 7, 7, NULL, NULL, NULL, NULL),
(1323, 'Grao Sudeste Com.Imp.e Export. de Café e Cereais Ltda', 'Grao Sudeste Com.Imp.e Export. de Café e Cereais Ltda', 'Av. Dr. Renato Azevedo', '508', NULL, 'Centro', 'Machado', 'Brasil', 'mg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '10.947.249/0001-62', NULL, '001.269.146.0061', true, 16, 16, NULL, NULL, NULL, NULL),
(1850, 'Green Trade Ltda', 'Green Trade Ltda', 'Rua do Comércio de Café, 101', NULL, 'Varginha, Minas Gerais', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'RE', 'VE', NULL, 'Green Trade Ltda
Rua do Comercio de Cafe, 101, letra B Industrial
Varginha, Minas Gerais 37026-530, Brazil', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(1440, 'Grupo Farroupilha', 'Grupo Farroupilha', 'Rua Major Gote', '585', '8° andar', NULL, 'Patos de Minas, MG', 'Brasil', 'MG', '38702-054', '(34) 3822-9950', NULL, NULL, NULL, 'farroupilha@grupofarroupilha.com', NULL, 'J', 'CL', 'VE', NULL, 'Dados para faturamento:

Inacio Carlos Urban       
End: Fazenda Rio Brilhante Café    
Município: Coromandel - MG    
Bairro/Distrito: Zona Rural    
CPF : 194.096.130-00    
Inscrição Estadual : 001112255.04 - 64    
Cep....: 38.550-000', NULL, NULL, NULL, true, 7, 4, NULL, NULL, NULL, NULL),
(1228, 'Gui Pádua', 'Gui Pádua', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 16, 16, NULL, NULL, NULL, NULL),
(941, 'GUILHERME JOSÉ REHDER', 'REHDER', 'FAZ. FARTURA-RDO. VARGEM GRANDE DO SUL / S.ROQUE', 'DA', 'FARTURA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'QUALICAFEX', '08.196.949/0003-82', NULL, '711113313111', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1664, 'GUILHERME PEREIRA BENFICA', 'GUILHERME PEREIRA BENFICA', 'Fazenda Santa Martha', NULL, NULL, NULL, 'Araxá', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '100.126.316-20', '002827678-0024', true, 2, 2, NULL, NULL, NULL, NULL),
(346, 'GUSTAVO GOMES FERNANDES E OUTROS', NULL, 'FAZ. RIO VERDE', NULL, NULL, NULL, 'CONCEIÇÃO DO RI', 'CONCEIÇÃO DO RI', 'MG', NULL, '(35) 33501204', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '606.493.997-49', '177/0717', true, NULL, NULL, NULL, NULL, NULL, NULL),
(281, 'GUSTAVO VIEIRA FERREIRA', NULL, 'FAZENDA PASSEIO', NULL, NULL, NULL, 'ALFENAS', 'ALFENAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ALFENAS CAFÉ', NULL, '532.572.786-91', '016/1366', true, NULL, NULL, NULL, NULL, NULL, NULL);
