-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(1630, 'OLIMPIO GARCIA MENDES', 'OLIMPIO GARCIA MENDES', 'Fazenda Larga', NULL, NULL, NULL, 'Ibia', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '050.423.876-09', '0020.68094-006', true, 2, 2, NULL, NULL, NULL, NULL),
(1766, 'OLIZETE APARECIDA CRIPPA ROCHA', 'OLIZETE APARECIDA CRIPPA ROCHA', 'Faz. Nossa Senhora da Aparecida', NULL, NULL, NULL, 'Perdizes', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '931.843.109-06', '001981718-0093', true, 2, 2, NULL, NULL, NULL, NULL),
(560, 'OMERO GARCIA DE DEUS', NULL, 'FAZ. CABECEIRA DA CACHOEIRA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '511.559.666-00', '143/2924', true, NULL, NULL, NULL, NULL, NULL, NULL),
(789, 'ORESTES QUERCIA', 'QUERCIA', 'FAZ. NOSSA SENHORA APARECIDA', NULL, NULL, NULL, 'PEDREGULHO', 'PEDREGULHO', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'QUERCIA', '3.963.917-4', '024.008.718-68', '051802911/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(845, 'ORIGEM BRAZIL COFFEE', 'ORIGEM', NULL, NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CAIO', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(301, 'ORIVALDO MALAMAM', NULL, 'FAZ. REALEJO', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '128.489.739-49', '564/0222', true, NULL, NULL, NULL, NULL, NULL, NULL),
(592, 'ORNEILTON ARAUJO SOARES', 'SOARES', 'FAZ. SERRA NEGRA '' DOURADOS''', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', 'CONTATO: ACAIA', 'ACAIA', NULL, '424.252.049-20', '481/3187', true, NULL, NULL, NULL, NULL, NULL, NULL),
(306, 'OSCAR HILEBRAND E OUTROS', NULL, 'FAZ. CACHOEIRA LAMBARI', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '085.814.019-53', '431/1884', true, NULL, NULL, NULL, NULL, NULL, NULL),
(639, 'OSCAR RIBEIRO', 'OSCAR RIBEIRO', 'FAZ. SERRADAO', NULL, NULL, NULL, 'GUIMARANIA', 'GUIMARANIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '007.968.326-68', '289/0325', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1, 'OSMAR PEREIRA NUNES JUNIOR E OU', 'OSMAR PEREIRA', 'FAZ. FREITAS', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'RE', 'VE', NULL, NULL, NULL, '53577060697', '481/4064', true, NULL, NULL, NULL, NULL, NULL, NULL),
(725, 'OSMAR SCHINCARIOL', 'OSMAR', 'FAZ. PIRAPITINGA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '088.198.319-53', '431/1601', true, NULL, NULL, NULL, NULL, NULL, NULL),
(338, 'OSMAR SCHINCARIOL', 'OSMAR', 'FAZ. SÃO PAULO', NULL, NULL, NULL, 'COROMANDEL', 'COROMANDEL', 'G', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '088.198.319-53', '193/2461', true, NULL, NULL, NULL, NULL, NULL, NULL),
(472, 'OSMILDO MOURA E OUTROS', NULL, 'FAZ. ATALHO', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '024.374.141.34', '431/1043', true, NULL, NULL, NULL, NULL, NULL, NULL),
(715, 'OSVALDO BALAN E OUTROS', 'OSVALDO', 'SITIO SANTO ANTONIO - GLEBA PIRAPÓ', NULL, NULL, NULL, 'APUCARANA', 'APUCARANA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '107.817.069-4', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(713, 'OSVALDO DAMIÃO E OUTROS', 'OSVALDO', 'ESTRADA FAZ. GAUCHA - SITIO DAMIÃO', NULL, NULL, NULL, 'APUCARANA', 'APUCARANA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '003.397.709-25', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(311, 'OSVALDO MARQUES VIEIRA', NULL, 'FAZ. BOA VISTA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '061.384.626-53', '431/0016', true, NULL, NULL, NULL, NULL, NULL, NULL),
(305, 'OSVALMIR HILEBRAND E OUTROS', NULL, 'FAZ. ARARAS', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '858.433.349-53', '431/2080', true, NULL, NULL, NULL, NULL, NULL, NULL),
(641, 'OSWALDO  GONÇALVES E OUTRO', NULL, 'FAZ. DA BARRA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '660.771.418-87', '481/0655', true, NULL, NULL, NULL, NULL, NULL, NULL),
(800, 'OTAVIANO BELIZARIO MENDES', 'MENDES', 'FAZ. BOA VISTA', NULL, NULL, NULL, 'TAPIARAI', 'TAPIARAI', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COPACAFE', NULL, '174.717.886-15', '682/0136', true, NULL, NULL, NULL, NULL, NULL, NULL),
(174, 'OTAVIANO PLÍMPIO VILELA', NULL, 'FAZENDA SANTO ANTONIO', NULL, NULL, NULL, 'CABO VERDE', 'CABO VERDE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: NEWTON VAZ', NULL, '096.477.756-87', '095/0759', true, NULL, NULL, NULL, NULL, NULL, NULL),
(193, 'OZAIR CORREIA', 'OZAIR CORREIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: INCOFEX', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1229, 'P CORRETAGEM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 16, 9, NULL, NULL, NULL, NULL),
(1078, 'Panfoods Co., Limited', NULL, '16 St. Clare Street', NULL, NULL, NULL, 'London - UK', NULL, NULL, 'EC3N 1LQ', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'PANFOODS COMPANY LTD
MARUBENI
EDUARDO


Export. Marubeni Colorado Ltda
Rua Ezzio Pucci, 2901
Franca - S.Paulo

58.184.840/0001-84
310.041.318.115

Panfoods Co., Limited
16 St. Clare Street
London
EC3N 1LQ
United Kingdom', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(601, 'PASCOAL PEREIRA MARQUES', NULL, 'FAZ. CARACOL', NULL, NULL, NULL, 'SERRA DO SALITR', 'SERRA DO SALITR', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '058.406.439-04', '667/1714', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1412, 'Paulista Comércio Exportação e Importação de Café S/A', 'Paulista Comércio Exportação e Importação (Falcafé)', 'Rua Governador Pedro de Toledo', '220', NULL, 'Vila Montenegro', 'Espírito Santo do Pinhal', 'Brasil', 'SP', '13990-000', '55 19 36619061', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Dados da Unidade de Ouro Fino:

Rua José Zamot n° 96 - Casa 2
Várzea
CEP: 37570-000
CNPJ: 04.618.562/0002-35
IE: 001.063.507.0073', '04.618.562/0001-54', NULL, '530.085.240.113', true, 12, 7, NULL, NULL, NULL, NULL),
(670, 'PAULO CESAR BARREIRA', 'PAULO CESAR', 'FAZ. TRANSAGO', NULL, NULL, NULL, 'RIO PARANAIBA', 'RIO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ASSOCAFE', NULL, '011.400.356-49', '555/2861', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1657, 'PAULO CESAR CALDEIRA ANGELO E OUTROS', 'PAULO CESAR CALDEIRA ANGELO E OUTROS', 'Fazenda Morro Grande', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '315.503.558-72', '00115588-0056', true, 2, 2, NULL, NULL, NULL, NULL),
(464, 'PAULO CÉSAR DA SILVA E OUTROS', NULL, 'FAZ. BOA ESPERANÇA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ASSOCAFE', NULL, '008.029.108-23', '143/1992', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1607, 'PAULO DUARTE FONTES', 'PAULO DUARTE FONTES', 'SITIO MEDALHA MILAGROSA-ESTR.OURO FINO/ MONTE SIAO', 'KM  10', NULL, 'BAIRRO DOS FARIAS', 'OURO FINO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '044.997.947-49', '001226188.00-06', true, 2, 2, NULL, NULL, NULL, NULL),
(460, 'PAULO SÉRGIO DE ALMEIDA', NULL, 'FAZ. SANTA TEREZINHA', NULL, NULL, NULL, 'PARAISÓPOLIS', 'PARAISÓPOLIS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: BOURBON', NULL, '192.152.076-00', '473/0670', true, NULL, NULL, NULL, NULL, NULL, NULL),
(395, 'PAULO SERGIO MARQUES DE CARVALHO DIAS', NULL, 'FAZENDA MANACÁ', NULL, NULL, NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '026.093.986-20', '518/0259', true, NULL, NULL, NULL, NULL, NULL, NULL),
(336, 'PAULO SÉRGIO MARQUES DE CARVALHO DIAS', NULL, 'FAZ. SÃO MIGUEL', NULL, NULL, NULL, 'BOTELHOS', 'BOTELHOS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CRISTIANO OTTONI', NULL, '026.093.986-20', '084/0372', true, NULL, NULL, NULL, NULL, NULL, NULL),
(423, 'PAULO SÉRGIO RODRIGUES E OUTRO', NULL, 'FAZENDA CASTELHANA DE BAIXO', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '943.161.989-04', '431/2504', true, NULL, NULL, NULL, NULL, NULL, NULL),
(587, 'PAULO SILVA', 'PAULO SILVA', 'FAZ. MACAÚBAS DE BAIXO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ACAIA', NULL, '086.911.936-20', '481/2644', true, NULL, NULL, NULL, NULL, NULL, NULL),
(66, 'PAULO VELOSO DOS SANTOS', NULL, 'FAZ. NOVA SUICA - RODOVIA BR 354 KM 278', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '010.033.996-49', '001181147.00-92', true, NULL, 2, NULL, NULL, NULL, NULL),
(101, 'PAULO VELOSO DOS SANTOS', NULL, 'FAZ. BERRADOR', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: JUNIOR', NULL, '010.033.996-49', '143/1214', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1444, 'Paulo Veloso dos Santos', NULL, 'Rod. BR 354 Km 278 - Zona Rural', NULL, 'P.O. Box 16', NULL, 'Carmo do Paranaíba, MG/ Brasil', NULL, NULL, NULL, '+55 34 3851-620', NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'Paulo Veloso dos Santos
Código do Exportador: 4169
CPF: 010.033.996-49
Inscrição Estadual: 001181147.00-92
Endereço: RODOVIA BR 354, KM 278 - ZONA RURAL 
CAIXA POSTAL 16, Carmo do Paranaíba - MG, Brasil.
CEP: 38840-000
Tel: +55 34 3851-6200', NULL, NULL, '001181147.00-92', true, 7, 7, NULL, NULL, NULL, NULL),
(1434, 'PAULO VELOSO JUNIOR', 'PAULO VELOSO JUNIOR', 'Faz. Nova Suiça - Rod. BR 354 Km 278', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', '38840-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '480.191.276-15', '0013887700252', true, 2, 7, NULL, NULL, NULL, NULL),
(1359, 'PAULO VELOSO JUNIOR e outras', 'PAULO VELOSO JUNIOR e outras', 'Faz. Paraiso - RODOVIA BR 354 KM 283, S/N, 35', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '48019127615', '0022827710030', true, 2, 2, NULL, NULL, NULL, NULL),
(1592, 'PC COMÉRCIO DE CAFÉ E ARMAZÉNS GERAIS LTDA', 'PC COMÉRCIO DE CAFÉ E ARMAZÉNS GERAIS LTDA', 'Av. Gal Astolfo Ferreira Mendes', '1880', NULL, NULL, 'Patrocinio', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '12.185.972/0001-87', NULL, '002.197.997-0084', true, 2, 2, NULL, NULL, NULL, NULL),
(773, 'PCS EXPORTADORA LTDA', 'PCS', 'ROD. POÇOS/PALMEIRAL', 'KM 20', NULL, NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CEREALISTA POÇOS DE CALDAS', '60.802.527/0001-61', NULL, '518.042.479-011', true, NULL, NULL, NULL, NULL, NULL, NULL),
(374, 'PEDRO ANTONIO DOS SANTOS', NULL, 'FAZ. CACHOEIRA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: QUENIO', NULL, '393.929.966-91', '143/1295', true, NULL, NULL, NULL, NULL, NULL, NULL),
(813, 'PEDRO DOS REIS', 'REIS', 'FAZ. RECANTO DO MORRO ALTO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '038.096.096-68', '481/6450', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1542, 'PEDRO HENRIQUE MACHADO BORGES', 'PEDRO HENRIQUE MACHADO BORGES', 'Fazenda Morro da Mesa', NULL, NULL, NULL, 'Araxá', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '071.677.796-79', '0023886310027', true, 2, 2, NULL, NULL, NULL, NULL),
(818, 'PEDRO HUMBERTO VELOSO', 'VELOSO', NULL, NULL, NULL, NULL, NULL, NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(602, 'PEDRO LUIZ ROSSI', NULL, 'FAZ. SERRA NEGRA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '397.433.499-87', '481/2243', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1544, 'PEDRO MARTINS DE MELO', 'PEDRO MARTINS DE MELO', 'Fazenda Morro da Mesa', NULL, NULL, NULL, 'Araxá', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '036.596.666-53', '0011745100-075', true, 2, 2, NULL, NULL, NULL, NULL),
(1282, 'PEDRO NILSON LEITE E OUTRO', 'PEDRO NILSON', 'Faz. Diplomata', NULL, NULL, NULL, 'Bonfinopolis', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '334.190.359-34', '001.180.334.0045', true, 2, 2, NULL, NULL, NULL, NULL),
(1252, 'PEDRO PAULO DONIZETE DA FONSECA', 'PEDRO PAULO', 'AV. Fatima Porto', '5555', NULL, 'Jardim Andrades', 'Patos de Minas', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '262797466-15', '0013538120005', true, 2, 2, NULL, NULL, NULL, NULL),
(187, 'PEDRO RICCI', 'PEDRO RICCI', 'FAZ. CASTELHANA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '005.381.839-34', '431/0042', true, NULL, NULL, NULL, NULL, NULL, NULL);
