-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(178, 'ISMAEL JOSÉ DE ANDRADE E OUTROS', NULL, 'FAZ. CACHOEIRA', NULL, NULL, NULL, 'RIO PARANAÍBA', 'RIO PARANAÍBA', 'MG', NULL, '(34) 8512455', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '385.147.456-20', '555/0937', true, NULL, NULL, NULL, NULL, NULL, NULL),
(325, 'ISMAEL JOSÉ DE ANDRADE E OUTROS', 'IS', 'FAZ. SÃO SILVESTRE', NULL, NULL, NULL, 'SERRA DO SALITR', 'SERRA DO SALITR', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '385.147.456-20', '667/1527', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1668, 'Ita Brasil Exportadora de Cafe EIRELI', 'Itabrasil', 'Rua Dona Vitoria 22,', NULL, 'Biguatinga', NULL, 'São Pedro da União - MG', NULL, NULL, '37.855-000', '(35) 3554-6112', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', 'fiscal@itabrasilcoffee.com.br
jorge@itabrasilcoffee.com.br', 'CNPJ: 27.649.988/0001-70
Razão Social: Ita Brasil Exportadora de Cafe EIRELI
Nome Fantasia: Itabrasil
Data de Abertura: 03/05/2017
Tipo: MATRIZ
Situação: ATIVA
Natureza Jurídica: 230-5 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)
Capital Social: 300000.00

Endereço
CEP: 37.855-000
Logradouro: R Dona Vitoria Número: 22
Bairro: Biguatinga
Município: Sao Pedro da Uniao UF: MG', '27.649.988/0001-70', NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(429, 'ITAPORANGA COM. EXP. LTDA', NULL, 'RUA ISAAC SIMÃO', '829', NULL, NULL, 'CAMPESTRE', 'CAMPESTRE', 'MG', '37.730-000', '(35) 37431357', NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '26.379.511/0001-50', NULL, '110.619.823.0053', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1035, 'J & R EXPORTADORA DE CAFE LTDA', NULL, 'R. XV DE NOVEMBRO, 41 S/40CENTRO - SANTOS (SP)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'J & R EXPORTADORA DE CAFE LTDA
J & R
TRADING DEPARTMENT', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1222, 'J. PARTICIPACOES CORRETORA DE MERC. LTDA', 'JP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'RE', 'VE', NULL, NULL, NULL, NULL, NULL, true, 16, 2, NULL, NULL, NULL, NULL),
(389, 'J. R COMISSÁRIA DE CAFÉ LTDA', 'J.R', 'AV. GOVERNADOR VALADARES', '48', 'SALA 1', NULL, 'RAUL SOARES', 'RAUL SOARES', 'MG', NULL, '(34) 32142011', NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: JAIME', '03.949.404/0001-14', NULL, '540.088.718-0093', true, NULL, NULL, NULL, NULL, NULL, NULL),
(541, 'J. VERONA & CIA LTDA', NULL, 'AV. IRATY', '640', NULL, NULL, 'APUCARANA', 'APUCARANA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '81.457.749/0001-64', NULL, '636.04987-50', true, NULL, NULL, NULL, NULL, NULL, NULL),
(192, 'JADIR STRINGHETA E OUTROS', NULL, 'FAZ. CASTELHANA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, '(34) 8421966', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: COOP. MTE CARMELO', NULL, '484.702.259-49', '564/0226', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1626, 'Jandir Fernandes da Silva', 'Jandir Fernandes da Silva', 'Fazenda Barreiro', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '127.603.156-49', '001.435.598-0073', true, 2, 2, NULL, NULL, NULL, NULL),
(711, 'JANUARIO DE ALMEIDA', 'JANUARIO', 'SITIO SANTA TEREZINHA', NULL, NULL, 'AGUA DO PILÃOZINHO', 'CORUMBATAI DOSUL', 'CORUMBATAI DOSUL', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '424.334.529-53', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(761, 'JARBAS PEREIRA DE ANDRADE', 'JARBAS', 'FAZ. PINTA ROXA', NULL, NULL, NULL, 'PRESIDENTE OLEGARIO', 'PRESIDENTE OLEGARIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CAIO', NULL, '164.225.389-87', '534/3482', true, NULL, NULL, NULL, NULL, NULL, NULL),
(98, 'JARBAS PEREIRA DE ANDRADE', NULL, 'FAZ. SÃO BENTO-CUPIM', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ISMAEL', NULL, '164225389-87', '143/0883', true, NULL, NULL, NULL, NULL, NULL, NULL),
(324, 'JARBAS PEREIRA DE ANDRADE', NULL, 'FAZ. CABECEIRA DO CORREGO ENGENHO DA SERRA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '164.225.389-87', '143/0887', true, NULL, NULL, NULL, NULL, NULL, NULL),
(313, 'JARBAS PEREIRA DE ANDRADE', NULL, 'FAZ. CAMPO DO MEIO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE', NULL, '164.225.389-87', '143/2112', true, NULL, NULL, NULL, NULL, NULL, NULL),
(580, 'JARVE GOMES DE AGUIAR', NULL, 'FAZ. SANTA BÁRBARA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '191.476.436-68', '431/1784', true, NULL, NULL, NULL, NULL, NULL, NULL),
(529, 'JAYME COSTA E SILVA', NULL, 'FAZ. CORREGO DO LAGE', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, '134/2306', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1550, 'JCA - Exportação, Assessoria, Empreendimentos e Participações Ltda.', 'JCA - Exportação, Assessoria, Empreendimentos e Participações Ltda.', 'Fazenda Ambiental Fortaleza, s/nº', NULL, NULL, NULL, 'Distrito de Igaraí, Mococa/SP', NULL, NULL, '13750-000', '(19) 3695-4500', 'ou 4180', NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'JCA - Exportação, Assessoria, Empreendimentos e 
Participações LTDA.
Endereço:
Fazenda Ambiental Fortaleza, s/nº - Galpão A - 
Distrito de Igaraí (Zona Rural)
CEP: 13750-000 - Mococa (SP)
CNPJ: 04.102.939/0001-18
I.E: 453.150.863.119
Telefone: (19) 3695-4500 ou 4180

Mr. Marcos Croce 
Mr. Wago Figueira
FafCoffees | Fazenda Ambiental Fortaleza | Faf Studio
Praça Horácio Sabino, 22 - Jardim das Bandeiras
São Paulo, SP|BRAZIL| CEP: 05412-010
phone: +55(11)38625833 | mobile: +55(11)972558800
skype: wdesouzafigueira www.fafbrazil.com|
www.bobolinkcoffee.com', '04.102.939/0001-1804', NULL, '453.150.863.119', true, 7, 7, NULL, NULL, NULL, NULL),
(968, 'JERRY MAGNO RESENDE', 'JERRY', 'FAZ. PARANÁ', NULL, NULL, NULL, 'RIO PARANAIBA', 'RIO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'alexandre@resendecoffee.com.br
jerry@resendeagro.com.br
paulo@resendeagro.com.br

Av joao batista da silva,423 2 andar
Bairro jk
Carmo do paranaiba
Cep 38844014', NULL, '904.934.276-00', '001.289.091-0180', true, NULL, 2, NULL, NULL, NULL, NULL),
(1647, 'JERRY MAGNO RESENDE', 'JERRY', 'Fazenda Coqueiros', NULL, NULL, NULL, 'Rio Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'alexandre@resendecoffee.com.br
jerry@resendeagro.com.br
paulo@resendeagro.com.br

Av joao batista da silva,423 2 andar
Bairro jk
Carmo do paranaiba
Cep 38844014', NULL, '904.934.276-00', '0012890910008', true, 2, 2, NULL, NULL, NULL, NULL),
(571, 'JOÃO BATISTA CAIXETA DA SILVA E/OU', NULL, 'BARCELONA', NULL, NULL, NULL, 'SERRA DOSALITRE', 'SERRA DOSALITRE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '339.820.406-53', '667/0608', true, NULL, NULL, NULL, NULL, NULL, NULL),
(664, 'JOAO BATISTA CARNEIRO', NULL, 'FAZ. BRAVINHOS II', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ASSOCAFE', NULL, '108.102.936-68', '143/3644', true, NULL, NULL, NULL, NULL, NULL, NULL),
(925, 'JOÃO BATISTA CARNEIRO', 'BATISTA', 'FAZ. BRAVINHOS II', NULL, NULL, NULL, 'CARMO DO PARANAIBA', 'CARMO DO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COOCACER - ZE REINALDO', NULL, '108.102.936-68', '143/3644', true, NULL, NULL, NULL, NULL, NULL, NULL),
(196, 'JOÃO BATISTA DA COSTA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: INCOFEX', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(222, 'JOÃO BATISTA DE ABREU', NULL, 'RUA DOS ITALIANOS', '305', NULL, NULL, 'BOTELHOS', 'BOTELHOS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CARVALHAES', NULL, '005.280.136-53', '084/0887', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1847, 'JOÃO BATISTA DONIZETE DE SOUZA', 'JOÃO BATISTA DONIZETE DE SOUZA', 'Fazenda Macedina', NULL, NULL, NULL, 'S.S. Paraiso', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'DATA NASC: 13/11/1956', 'CONTATO: EXATA', NULL, '198.101.216-87', '001.346.827-0089', true, 2, 2, NULL, NULL, NULL, NULL),
(1848, 'JOÃO BATISTA DONIZETE DE SOUZA', 'JOÃO BATISTA DONIZETE DE SOUZA', 'Fazenda Boa Vista', NULL, NULL, NULL, 'S.S. PARAISO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'DATA NASC: 13/11/1956', 'EXATA', NULL, '198.101.216-87', '001.312.549-0081', true, 2, 2, NULL, NULL, NULL, NULL),
(158, 'JOÃO BATISTA MARQUES', NULL, 'FAZ. CACHOEIRA - BON JARDIN', NULL, NULL, NULL, 'PATROCÍNIO', 'PATROCÍNIO', 'MG', NULL, '(34) 8313202', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ÉBER ANTUNES', NULL, '144.615.956-68', '481/1585', true, NULL, NULL, NULL, NULL, NULL, NULL),
(626, 'JOÃO BATISTA ROMÃO', NULL, 'FAZ.  N.S. FÁTIMA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '536.291.756-00', '481/4241', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1628, 'JOAO FARID ANANIAS', 'JOAO FARID ANANIAS', 'Faz. Jardim', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '032.547.556.34', '001.173.375-0061', true, 2, 2, NULL, NULL, NULL, NULL),
(645, 'JOÃO FARINHA LOPES', NULL, 'FAZ. CHAPADÃO DO FERRO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '176.271.639-68', '481/3321', true, NULL, NULL, NULL, NULL, NULL, NULL),
(622, 'JOÃO FERNANDES COSTA', NULL, 'FAZ. PENEDO L. BREJÃO', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '323.344.276-91', '431/2257', true, NULL, NULL, NULL, NULL, NULL, NULL),
(386, 'JOÃO GONÇALVES SIQUEIRA', NULL, 'FAZENDA SANTA CECÍLIA', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '039.650.076-53', '143/0408', true, NULL, NULL, NULL, NULL, NULL, NULL),
(545, 'JOÃO HONORIO DE CARVALHO RAMOS', NULL, 'FAZ. SERTAOZINHO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO. ADAILTON', NULL, '365.655.806-00', '481/4922', true, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'JOAO LUIS TEODORO', NULL, 'AV. BARAO DO RIO BRANCO', '167', NULL, NULL, 'MANHUACU', 'MANHUACU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: COOP.CARATINGA', '01.053.415/0001-96', NULL, '394.962.004.0029', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1503, 'JOÃO MARCOS SANCHES', 'JOÃO MARCOS SANCHES', 'Fazenda Vereda Grande', NULL, NULL, NULL, 'Presidente Olegario', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '429.119.906-68', '116.628.800-06', true, 2, 2, NULL, NULL, NULL, NULL),
(314, 'JOÃO MARTINELLI E OUTROS', NULL, 'FAZ. SANTA BARBARA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '129.397.149-91', '431/1025', true, NULL, NULL, NULL, NULL, NULL, NULL),
(585, 'JOÃO PADILHA', 'JOÃO PADILHA', 'SITIO SÃO JOÃO-MUNICIO SANTA AMÉLIA', NULL, NULL, NULL, 'ABATIA', 'ABATIA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: PLENO', NULL, '115.376.399-00', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(821, 'JOÃO ROBERTO BEGNOSSI', 'BEGNOSSI', 'FAZENDA MACAUBAS "CAPÃO DA ONÇA"', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '502.324.289-72', '481/4896', true, NULL, NULL, NULL, NULL, NULL, NULL),
(633, 'JOÃO RUIZ LOURENÇO', NULL, 'FAZ. LAGOA DOS ESTULANO', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '040.093.128-15', '143/3690', true, NULL, NULL, NULL, NULL, NULL, NULL),
(387, 'JOAQUIM BERNARDES DA SILVA DIAS', NULL, 'FAZ. SANTA ALINA', NULL, NULL, NULL, 'S.S. DA GRAMA', 'S.S. DA GRAMA', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CRISTIANO OTTONI', NULL, '007.039.668-04', '065500053/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(322, 'JOAQUIM BERNARDES DE CARVALHO DIAS', NULL, 'FAZ. SANTA ALINA', NULL, NULL, NULL, 'S.S. DA GRAMA', 'S.S. DA GRAMA', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CRISTIANO OTTONI', NULL, '005.284.636.91', '065500053/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(400, 'JOAQUIM FERNANDES BRAGA FILHO', 'JOA', 'FAZENDA AGUÁ LIMPA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '408880299-34', NULL, '431/2485', true, NULL, NULL, NULL, NULL, NULL, NULL),
(616, 'JOAQUIM FERNANDES BRAGA FILHO', NULL, 'FAZ. AGUA LIMPA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '408.880.299-34', '431/2485', true, NULL, NULL, NULL, NULL, NULL, NULL),
(62, 'JOAQUIM PEDRINHO ALVES', NULL, 'CEL. ANTONIO DA SILVA', '22', NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', '35.300-032', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(709, 'JOBIS DA SILVA', 'JOBIS', 'SITIO SÃO JOÃO', NULL, NULL, 'BORGES', 'CORUMBATAI DO SUL', 'CORUMBATAI DO SUL', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '439.272.209-06', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1699, 'JONATA MORAIS GONÇALVES', 'JONATA MORAIS GONÇALVES', 'Faz. Mutuca', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '016.072.626-30', '003.363.898-0013', true, 2, 2, NULL, NULL, NULL, NULL),
(768, 'JORGE AZEVEDO FRANÇA E OUTRO', 'JORGE', 'FAZ. BARREIRAS', NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CAIO', NULL, '449.010.548-72', '480/5114', true, NULL, NULL, NULL, NULL, NULL, NULL),
(263, 'JORGE BARAKAT', 'JORGE BARAKAT', 'FAZENDA PARAÍSO', NULL, NULL, NULL, 'JOÃO PINHEIRO', 'JOÃO PINHEIRO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CAIO', NULL, '174.855.176-00', '363/2581', true, NULL, NULL, NULL, NULL, NULL, NULL),
(399, 'JOSÉ ALENCAR BRANCO URTADO', 'JOSE ALENCAR', 'FAZENDA MARJOREAN', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '418.860.038-15', NULL, 'IP:431/0517', true, NULL, NULL, NULL, NULL, NULL, NULL);
