-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(288, 'CARLOS ALBERTO PEREIRA', NULL, 'FAZ. SÃO FELIX', NULL, NULL, NULL, 'ESTRELA DO SUL', 'ESTRELA DO SUL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '183.378.216-04', '248/0627', true, NULL, NULL, NULL, NULL, NULL, NULL),
(340, 'CARLOS ALBERTO PEREIRA', NULL, 'FAZ. SÃO FELIX', NULL, NULL, NULL, 'ESTRELA DO SUL', 'ESTRELA DO SUL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '183.378.216-04', '248/0627', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1304, 'CARLOS HENRIQUE MENEZES DE MENDONCA', 'CARLOS HENRIQUE MENEZES DE MENDONCA', 'FAZENDA LENHEIROS', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '07034566607', '0013098130032', true, 2, 2, NULL, NULL, NULL, NULL),
(1586, 'CARLOS HENRIQUE RIBEIRO DO VALLE', 'CARLOS HENRIQUE RIBEIRO DO VALLE', 'Fazenda Monte Alto', NULL, 'Zona Rural', NULL, 'Guaxupe', NULL, 'MG', '37800-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CONTATO : EMANUEL
emmanuel@montealtocoffees.com', NULL, '446.269.678-68', '001254989-0140', true, 2, 2, NULL, NULL, NULL, NULL),
(1587, 'CARLOS HENRIQUE RIBEIRO DO VALLE', 'CARLOS HENRIQUE RIBEIRO DO VALLE', 'Faz. Reunidas da Cachoeira', NULL, 'Bebedouro', NULL, 'Monte Santo de Minas', NULL, 'MG', '37968-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CONTATO: EMANUEL

emmanuel@montealtocoffees.com', NULL, '446.269.678-68', '001254989-0060', true, 2, 2, NULL, NULL, NULL, NULL),
(831, 'CARLOS ROBERTO  DOS SANTOS', 'SASA', NULL, NULL, NULL, NULL, 'PEDRAVALVA', 'PEDRAVALVA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(785, 'CARLOS THOMAS BRASILEIRO', 'BRASILEIRO', 'FAZ. FOLHEADOS E SANTANA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '880.994.826-20', '481/4179', true, NULL, NULL, NULL, NULL, NULL, NULL),
(417, 'CARLOS URBANO LEITE DE MATOS', NULL, 'FAZ. CAPARAÓ', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '582.086.316-04', '134/3880', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1251, 'CARMELITA HONORIO DOS SANTOS', 'CARMELITA', 'Faz. Cachoeira', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '011.931.626.-96', '001.322943-0018', true, 2, 2, NULL, NULL, NULL, NULL),
(1793, 'Carmo do Paranaíba LTDA.', 'CARPEC', 'Av. João Batista da Silva, 398', NULL, 'Bairro JK - Carmo do Paranaíba, MG', NULL, '38844-014', NULL, NULL, NULL, '(34) 3851-7222', NULL, NULL, NULL, NULL, 'carpec@carpec.com.br', 'J', 'CL', 'VE', 'Mr. Daniel Paulo de Oliveira', 'CARMO DO PARANAIBA LTDA
( CARPEC )- AVENIDA JOÃO BATISTA DA SILVA - 398 - 
BAIRRO JK / CARMO DO PARANAÍBA - MG - BRASIL
CEP 38844-014 
LOCAL DE CARREGAMENTO: FAZ. CORREGO  DOS LENHEIROS 
MARGEM ROD. AGEU  GARCIA DE DEUS,AMG 1.410 S/N - KM 2,4- ZONA RURAL - CARMO DO PARANAIBA-MG CNPJ-194457330007-53 IE-1430742000540.', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(1107, 'Carmocer -Cooperativa dos Cafeicultores do Cerrado da Regiao de Carmo do Paranaiba', 'CARMOCER', 'Rua Governador Valadores', '1553', NULL, 'PARAISO', 'Carmo do Paranaiba', NULL, 'MG', '38.840-000', '(34)3851-2995', NULL, NULL, NULL, 'contato@carmocer.com.br', NULL, 'J', 'CL', 'VE', NULL, NULL, '04.773.010/0002-00', NULL, '143.176.406-0130', true, NULL, 2, NULL, NULL, NULL, NULL),
(599, 'CATARINA MIE TAKAHASHI MYAKI E OUTROS', NULL, 'FAZ. SÃO JOSE', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ACAIA', NULL, '042.297.868-56', '481/1822', false, NULL, NULL, NULL, NULL, NULL, NULL),
(603, 'CATARINA MIE TAKAHASHI MYAKI E OUTROS', NULL, 'FAZ. SANTA CATARINA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '046.584.509-68', '481/2390', false, NULL, NULL, NULL, NULL, NULL, NULL),
(555, 'CATARINA MIE TAKAHASI MYAKI  E OU MIRO', NULL, 'FAZ. CENTENÁRIO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '042.297.686-56', '481/1857', false, NULL, NULL, NULL, NULL, NULL, NULL),
(459, 'CELSO DE ALMEIDA', NULL, 'FAZ. SANTA MARIA', NULL, NULL, NULL, 'PARAISÓPOLIS', 'PARAISÓPOLIS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: BOURBON', NULL, '263.891.776-15', '473/0673', true, NULL, NULL, NULL, NULL, NULL, NULL),
(218, 'CELSO LUIS DALL''AGNOL', NULL, 'FAZENDA CASTELHANA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '498.325.906-63', '431/2176', true, NULL, NULL, NULL, NULL, NULL, NULL),
(558, 'CEREALISTA ALINE LTDA', 'CEREALISTA', 'AV. BARÃO DO RIO BRANCO', 'S/N', NULL, NULL, 'DOURADINA', 'DOURADINA', 'PR', NULL, NULL, 'PLENO', NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '80.593.296/0001-30', NULL, '84.200.226-55', true, NULL, NULL, NULL, NULL, NULL, NULL),
(764, 'CEREALISTA POÇOS DE CALDAS LTDA', 'ERTETE', 'AV. PRES. VENCESLAU BRAZ', '2600-B', NULL, NULL, 'POÇOS DE CALDAS', 'POÇOS DE CALDAS', 'MG', '37706-000', NULL, NULL, '35-37131497', NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '07.293.974/0001-50', NULL, '518.345.244.0025', true, NULL, NULL, NULL, NULL, NULL, NULL),
(200, 'CERRADO MINEIRO', 'CERRADO MINEIRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(606, 'CÉSAR JORDÃO E OUTRO', 'CESA', 'MARIANA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '663.098.916-34', '431/2067', true, NULL, NULL, NULL, NULL, NULL, NULL),
(934, 'CESAR SILOS DE SOUZA', 'SILOS', 'FAZ. DOS BARROS ESCR. FAZENDEIRO GIL', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '091.497.318-58', '481/5073', true, NULL, NULL, NULL, NULL, NULL, NULL),
(403, 'CHARONEL AGROPECUÁRIA S/A', NULL, 'FAZ. ROMARIA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: AMOCA', '18.431.700/0001-04', 'IPR: 564/0026', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(131, 'CIA. AGROP. MONTE ALEGRE', NULL, 'FAZ. MAROLÂNDIA', NULL, NULL, NULL, 'ALFENAS', 'ALFENAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'CONTATO: JORGE', '19.053.206/0003-70', '001429239.02-23', NULL, true, NULL, 2, NULL, NULL, NULL, NULL),
(350, 'CIA. Agrop. Monte Alegre', 'MONTERG', 'CAIXA POSTAL 62', NULL, NULL, NULL, 'AREADO', 'AREADO', 'MG', '37140-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, 2, NULL, NULL, NULL, NULL),
(206, 'CIA. AGROPECUÁRIA MONTE ALEGRE', NULL, 'FAZ. TAQUARUÇU', NULL, NULL, NULL, 'AREADO', 'AREADO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: JORGE', '19.053.206/0001-08', 'IPR: 043/0911', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'Cia. Agropecuária Monte Alegre.', 'Monte Alegre', 'Fazenda Monte Alegre, w/nº', NULL, NULL, 'Zona Rural', 'Monte Belo -', NULL, 'MG', '37.115-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'CONTATO: JORGE
CIA AGROPECUARIA MONTE ALEGRE
CIA M.ALEGRE
COFFEE DEPARTMENT

Monte Alegre Comercial Ltda
Taguaruçu, BL 01
Areado - MG
CNPJ: 02.036.286/0001-90
IE: 043.711.567.0075
CEP 37140-000 Caixa postal 62


----------------------------------------------------------------------
Escritório é Na /fazenda Taquarinha
Municípiio de Monte Belo- MG
BR 491 - Quilômetro 141
Sentido Areado a Monte Belo, andar mais ou menos 13 km. entrar a esquerda a mais ou menos 100 metros de pois da ponte.
Andar em estrada de terra mais ou menos 1,5 km até o escritório.
Antes de chegar no escritótio tem uma cancela com interfone para identificação.', '19.053.206/0001-08', 'IPR: 430/1897', '0014292390061', true, NULL, 7, NULL, NULL, NULL, NULL),
(765, 'CIA. DE PROMOÇÃO AGRICOLA - CPA', 'CPA', 'FAZ. COROMANDEL', NULL, NULL, NULL, 'COROMANDEL', 'COROMANDEL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CAIO', '20.512.356/0002-00', NULL, '193/0210', true, NULL, NULL, NULL, NULL, NULL, NULL),
(100, 'CIA. TEXTIL DE CASTANHAL', NULL, 'AV. CARIOCA', NULL, NULL, NULL, 'SAO PAULO', 'SAO PAULO', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: WILTON', '053.89812/0002-75', NULL, '113.861.083.110', true, NULL, NULL, NULL, NULL, NULL, NULL),
(930, 'CIAMEX EXPORTADORA MINEIRA DE CAFÉ LTDA', 'CIAMEX', 'AV. FARIA PEREIRA', '3574', 'SALA 03 E 04', NULL, 'PATROCÍNIO', 'PATROCÍNIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'ACAIA', '03.726.291/0001-98', NULL, '001.105399-0090', true, NULL, NULL, NULL, NULL, NULL, NULL),
(209, 'CIANORTE', 'CIANORTE', NULL, NULL, NULL, NULL, 'VARGINHA', 'VARGINHA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(830, 'CICERO VIEGAS ALBUQUERQUE', 'CICERO', NULL, NULL, NULL, NULL, 'CARMO DE MINAS', 'CARMO DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1819, 'CINCO GRÃOS COM. ATACADISTA DE CAFÉ LTDA', 'CINCO GRÃOS COM. ATACADISTA DE CAFÉ LTDA', 'Av. Capitão Firmino Rocha', 'S/N', NULL, NULL, 'Patrocinio Paulista', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '23.880.589/0001-65', NULL, '511.028.332-112', true, 2, 2, NULL, NULL, NULL, NULL),
(1678, 'CLAUDIA YATIO NAKAO', 'CLAUDIA YATIO NAKAO', 'Faz. Sao Francisco -  BR 365 KM  440', NULL, NULL, NULL, 'Patos de Minas', NULL, 'MG', '38700-999', '34-3821-8556', NULL, NULL, NULL, NULL, 'marie3mc@hotmail.com', 'F', 'CL', 'VE', 'adm3mcnakao@outlook.com
claudianakao1@hotmail.com', 'PAULINHO', '16179963', '866.394.396-20', '001138780-0019', true, 2, 2, NULL, NULL, NULL, NULL),
(675, 'CLAUDIO GALLIN', 'CLAUDIO', 'FAZ. FULDAS', NULL, NULL, NULL, 'CARMO DO PARANAIBA', 'CARMO DO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ASSOCAFE', NULL, '692.976.301-20', '143/3.382', true, NULL, NULL, NULL, NULL, NULL, NULL),
(169, 'CLAUDIO GILBERTO PATRÍCIO ARROYO', NULL, 'FAZ. RECANTO DA AMIZADE', NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CAIO_CORRETORA', NULL, '043.550.598-04', '480/4536', true, NULL, NULL, NULL, NULL, NULL, NULL),
(722, 'CLAUDIO PAVANI E OUTROS', 'CLRS', 'FAZ. NOSSA SENHORA APARECIDA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '619.697.299-53', '431/2453', true, NULL, NULL, NULL, NULL, NULL, NULL),
(384, 'CLAUDIO ZUBIOLI E OUTROS', NULL, 'FAZ. SANTA BARBARA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '668.877.639-15', '564/0600', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1186, 'Cléo Tulio de Brito', 'Cleo Tulio de Brito', 'Fazenda Santa Edwirges, Zona Rural', NULL, NULL, NULL, 'Elói Mendes/MG - 37110-000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'contato@shcoffees.com/hugo@shcoffees.com', 'Nome/Razão Social: Cléo Tulio de Brito

CPF: 193.267.266-49

Endereço: Fazenda Santa Edwirges, Zona Rural,
Elói    Mendes - MG, CEP: 37110-000 
IE: 0011590880110 

Dados Bancários: Banco do Brasil (001), 
Agência: 0421-9, Conta Corrente: 2134-2,
titular da Conta: Cléo Tulio de Brito.', 'CPF: 193.267.266-49', NULL, '0011590880110', true, 8, 7, NULL, NULL, NULL, NULL),
(685, 'CLEVES ANTONIO DE PAULA', 'CLEVES', 'FAZ. SERRA NEGRA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '744691186-72', '481/5562', true, NULL, NULL, NULL, NULL, NULL, NULL),
(589, 'CLORINDA DEL GUERRA DE CARVALHO DE ROSAS E OUTROS', NULL, 'SITIO RETIRO SÃO VICENTE', NULL, NULL, NULL, 'ESP.STO DO PINH', 'ESP.STO DO PINH', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: QUALICAFEX', NULL, '056.693.168-00', 'P.05300077.0/002', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1319, 'CLOVIS VENANCIO DE JESUS', 'CLOVIS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 2, 2, NULL, NULL, NULL, NULL),
(556, 'COAGEL - COOPERATIVA AGROP. GOIO-ERE LTDA', 'COAGEL', 'AV. JOVELINO R. DA COSTA - SAÍDA TUNEIRAS', 'S/N', NULL, NULL, 'MOREIRA SALES', 'MOREIRA SALES', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '76.211.770/0012-06', NULL, '817.007.85-60', true, NULL, NULL, NULL, NULL, NULL, NULL),
(989, 'Coamo - Agroindustrial Cooperativa', 'COAMO', 'Av. Presidente John Kennedy', NULL, NULL, 'Jardim Lar', 'Campo Mourão', NULL, 'PR', '87.306-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '75904383/0008-06', NULL, '801.02.620-63', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1197, 'Cobimex Connect Brasil Export Ltda.', 'Cobimex Connect Brasil Export Ltda.', 'Avenida Celina Ferreira Ottoni,', '4360', 'sala 01', NULL, 'Varginha', 'Brazil', 'MG', '37048-395', '(31) 3308-6200', NULL, NULL, NULL, 'Email: Please contact Atlantica''s team.', 'Email: Please contact Atlantica''s team.', 'J', 'CL', 'VE', NULL, 'FDA 14384129170

Contact.: Mrs. Irene Vieira', '05.525.999/0003-78', NULL, '546227186.02-10', true, 7, 4, NULL, NULL, NULL, NULL),
(992, 'COCAMAR - Coop. AgroIndustrial', 'COCAMAR', 'ESTRADA DOS PIONEIROS', '1000', NULL, NULL, 'MARINGA', NULL, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Cocamar - Coop. AgroIndustrial

Estrada Osvaldo Moraes Correia, 1000 Lot 12
Maringá - Paraná 
Cep: 87065-240
CNPJ: 79.114.450/0017-22
IE: 701.103.19-05


Nota Fiscal ( Matriz )

Cocamar - Coop. AgroIndustrial
Estrada Osvaldo Moraes Correia, 1000 Lot 12
Maringá - Paraná 
Cep: 87065-240
CNPJ: 79.114.450/0001-65
IE: 701.028.5970', '79.114-450/0017-22', NULL, '701.103.19-05', true, NULL, NULL, NULL, NULL, NULL, NULL),
(887, 'COCAMAR - Cooperativa AgroIndustrial', 'COCAMAR', 'Rodovia BR 50KM 039', NULL, NULL, NULL, 'Araguari - MG', NULL, NULL, '38440-000', '34 32424239', NULL, NULL, NULL, NULL, NULL, 'J', 'RE', 'VE', NULL, 'PLENO', '79.114.450/0103-90', '1720007', '035.857.633.0010', true, NULL, 7, NULL, NULL, NULL, NULL),
(574, 'COCAMAR -COOPERAVATIVA AGROINDUSTRIAL', 'COCAMAR', 'ESTRADA OSVALDO DE MORAES CORREIA', '1000', NULL, NULL, 'MARINGÁ', 'MARINGÁ', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '79.114.450/0001-65', NULL, '035.857.633-0010', false, NULL, 7, NULL, NULL, NULL, NULL),
(248, 'COCANORTE COM. E IND. IMP. E EXP. DE CAFÉ LTDA', NULL, 'AV. JOÃO PINHEIRO', '243', 'APTO 1', NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, '(44) 262767', NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '01.362.494/0001-17', NULL, '431.978.487.0065', true, NULL, NULL, NULL, NULL, NULL, NULL),
(167, 'COCAPEC - Coop. de Cafeicultores e Agropecuaristas.', 'COCAPEC', 'Av. Wilson Sabio de Mello,', '3100', NULL, 'Distrito Industrial -', 'Franca /', NULL, 'SP', '14406-052', NULL, NULL, '16 3711-6270', NULL, NULL, 'gerencia.cafe@cocapec.com.br', 'J', 'CL', 'VE', 'www.cocapec.com.br', 'Contato: Mr. Anselmo Magno
secretária: Eliane (negocios.cafe@cocapec.com.br
+55 (16) 3711-6255


Presidente da Cocapec:
João Alves de Toledo Filho', '54.772.017/0001-96', NULL, '310.077.843.113', true, NULL, 7, NULL, NULL, NULL, NULL),
(1368, 'COCAPEC- COOP. DE CAFEICULTORES E AGROPECUARISTAS', 'COCAPEC', 'Rua Barao do Rio Branco', '1484', NULL, NULL, 'Ibiraci', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '54.772.017/0015-91', NULL, '297.523.499.0387', true, 2, 2, NULL, NULL, NULL, NULL);
