-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(669, 'JOSE RONALDO DE MELO', 'JOSE RONALDO', 'FAZ. PARAISO', NULL, NULL, NULL, 'CARMO DO PARANAIBA', 'CARMO DO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ASSOCAFE', NULL, '239.307.306-00', '143/1167', true, NULL, NULL, NULL, NULL, NULL, NULL),
(586, 'JOSÉ UILSON PADILHA', NULL, 'SITIO SANTA MARIA', NULL, NULL, NULL, 'ABATIA', 'ABATIA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: PLENO', NULL, '279.535.139-00', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(542, 'JOSÉ VERONA', 'JOSÉ VERONA', 'SITIO DAS PAINEIRAS', NULL, NULL, 'CONTORNO SUL', 'APUCARANA', 'APUCARANA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '011.026.489-49', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(718, 'JOSE VICTOR GRILO', 'JOSE', 'SITIO STA CATARINA', 'LOTE 17', NULL, NULL, 'JARDIM ALEGRE', 'JARDIM ALEGRE', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '086.743.109-15', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(617, 'JOSÉ ZUBIOLI', 'JOSÉ ZUBIOLI', 'FAZ. SANTA BARBARA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '116.993.889-20', '564/0233', true, NULL, NULL, NULL, NULL, NULL, NULL),
(420, 'JOSUÉ  PEREIRA DE FIGUEIREDO', NULL, 'FAZ. BOM JARDIM', NULL, NULL, NULL, 'STO. ANTONIO DO', 'STO. ANTONIO DO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '100.613.206-68', '080/0430', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1207, 'JR Assessoria, Intermediação e Corretagens Ltda.', 'JR. Assessoria', 'Rua XV de Novembro,', '41', 'conj. 40', 'Centro', 'Santos', NULL, 'SP', '11010-151', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'JR Assessoria, Intermediação e Corretagens Ltda
Rua XV de Novembro, 41 conj. 40
Centro - Santos
Cep: 11010-151 
CNPJ: 64.721.517/0001-52
Insc Estadual: Isento
Insc Municipal: 100.362-5.', '64.721.517/0001-52', '100.362-5', 'Isento', true, 7, 7, NULL, NULL, NULL, NULL),
(1753, 'JULIANO HENRIQUE BORGES', 'JULIANO HENRIQUE BORGES', 'Faz. Sao Jose da lagoa', NULL, NULL, NULL, 'Sao Gotardo', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CL', 'VE', NULL, 'NILSON', NULL, '034.631.466-65', '001.815.105-0012', true, 2, 2, NULL, NULL, NULL, NULL),
(1654, 'JULIANO RIBEIRO ARAUJO', 'JULIANO RIBEIRO ARAUJO', 'Fazenda Paraiso', NULL, NULL, NULL, 'Ibiá', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '072.778.456-09', '001230098-0053', true, 2, 2, NULL, NULL, NULL, NULL),
(955, 'JULIO CESAR OCTAVIANI', 'JULIO', 'FAZENDA BARRA MANSA', NULL, NULL, NULL, 'S.SEBASTIÃO DO PARAISO', 'S.SEBASTIÃO DO PARAISO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '016 179 578 10', NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1852, 'JÚLIO CÉZAR DINIZ', 'JÚLIO CÉZAR DINIZ', 'Fazenda Das Paineiras', NULL, NULL, NULL, 'Passos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', NULL, 'VE', 'DATA DE NASC: 14/10/1958', 'EXATA CORRETORA', NULL, '311.952.886-20', '001.167.211-0270', true, 2, 2, NULL, NULL, NULL, NULL),
(185, 'JULIO KOJI YASSUNAKA', NULL, 'FAZ. MARRECOS', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '361.758.979-00', '546/0020', true, NULL, NULL, NULL, NULL, NULL, NULL),
(235, 'JÚLIO KOJI YASSUNAKA', NULL, 'FAZENDA GUAÍRA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '361.758.979-00', '564/0467', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1683, 'JULIO MARIA LOPES E OU', 'JULIO MARIA LOPES E OU', 'Faz. Sta Barbara das Guaritas', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '719.481.806-00', '001.271.156-0080', true, 2, 2, NULL, NULL, NULL, NULL),
(1539, 'JURANDIR VIEIRA DE CAMARGO E OUTROS', 'JURANDIR VIEIRA DE CAMARGO E OUTROS', 'Faz. Creoulos', NULL, NULL, NULL, 'Pedrinópolis', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '069.313-978-18', '0027544390063', true, 2, 2, NULL, NULL, NULL, NULL),
(620, 'JURY CALVET BORBA E HELDER BOVI', NULL, 'FAZ. DONA IDALVA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'AMOCA', NULL, '472.156.079-68', '564/0661', true, NULL, NULL, NULL, NULL, NULL, NULL),
(109, 'KEIZO YAMANAKA', 'KEIZO YAMANAKA', 'FAZ. MUNDO NOVO', NULL, NULL, NULL, 'PARACATU', 'PARACATU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1292, 'KELLY SILVA COSTA VELOSO', 'KELLY VELOSO', 'Fazenda Paraiso', 's/n', NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'RE', 'VE', NULL, NULL, NULL, '675.970.926-87', '00144.149.400-10', true, 2, 2, NULL, NULL, NULL, NULL),
(1038, 'Labareda Caititu Comércio de Café LTDA.', 'Labareda State Coffee', 'Rua do Sol', '970', 'Residencial Paraíso', NULL, 'Franca - SP', 'Brasil', 'SP', '14.403-149', '(16) 3702-5355', NULL, '(16) 3702-5355', NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'GABRIEL AFONSO MEI ALVES DE OLIVEIRA E OUTRA
ESTRADA VICINAL ARGEMIRO LEONARDO KM 10, ZONA RURAL.
Cristais Paulista - SP
CEP: 14460-000
CNPJ: 07.983.222/0001-10 
IE: 280.054.415.111
Fone: 16 3702-5355', '08.954.755/0001-37', NULL, '310.428.479.110', true, NULL, 7, NULL, NULL, NULL, NULL),
(1039, 'LAGOA LTDA', NULL, 'FAZENDA MONTE ALEGREMONTE BELO (MG)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'LAGOA LTDA
LAGOA
MARCELO VIEIRA/SILVIO LEITE', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1044, 'LAMBARI EXP.E COM.DE CAFE LTDA', NULL, 'RUA Sao Joao da Boa Vista', NULL, NULL, 'Jardim dos Estados', NULL, NULL, 'MG', '37701-054', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CL', 'VE', NULL, 'LAMBARI EXP. E COM. DE CAFE LTDA
LAMBARI
SR. RAYMOND LOUIS REBETEZ



Endereço p/ Nota:

Rodovia Poços de Caldas A Palmeiral, KM 12
casa 01.


Segue abaixo dados da Astro Café p/ fatura:

 

Astro Torrefação e Comércio de Café Ltda.
Rod.: Mogi Guaçu a Espírito Santo do Pinhal, km 185,5 casa 2
Cep.: 13990-000 - zona rural
CNPJ: 04.356.926/0001-75 - IE 530.084.810.116
Espírito Santo do Pinhal - SP 

 

End. p/ Correspondência
Rua São João da Boa Vista, 831 / 867 - Jardim dos Estados
Cep.: 37701-054 – Caixa Postal 955 - Poços de Caldas - MG', '02.928.058/0001-25', NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(293, 'LANDULFO FALEIROS CARDOSO E OUTROS', NULL, 'FAZ. VEREDA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '328.278.496-15', '564/0482', true, NULL, NULL, NULL, NULL, NULL, NULL),
(729, 'LAURA DIAS REHDER', 'LAURA', 'FAZ. FARTURA', NULL, NULL, NULL, 'VARGEM GRANDE DO SUL', 'VARGEM GRANDE DO SUL', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'QUALICAFEX', NULL, '286.630.058-99', '071101096/013', true, NULL, NULL, NULL, NULL, NULL, NULL),
(796, 'LAZARO FRANCISCO DOS SANTOS', 'LAZARO', 'FAZ. ARARAS', NULL, NULL, NULL, 'BAMBUI', 'BAMBUI', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COPACAFE', 'M-3933.024', '174.702.696-49', '051/2117', true, NULL, NULL, NULL, NULL, NULL, NULL),
(438, 'LEOCARLOS MARQUES MUNDIM E OUTROS', NULL, 'FAZ. BOA VISTA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '351.548.456-68', '431/1132', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1313, 'LEONARDO MARTINS FERREIRA E OUTROS', 'LEONARDO MARTINS', 'Fazenda Chapadão', NULL, NULL, NULL, 'Candeias', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '648.071.856-91', '001341973-0055', true, 2, 2, NULL, NULL, NULL, NULL),
(165, 'LEOPOLDINA ORLANDELLE MARTIN GALLEGO', NULL, 'FAZ. RECANTO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '004.205.356-08', '481/1005', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1048, 'Lessivan Marcos de Oliveira Pacheco', NULL, 'Fazenda Lagoa do Morro s/n, Zona Rural', NULL, NULL, NULL, 'Brejões', NULL, 'BA', '45325000', '73 3542-2230', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'produtor Rural  80.012.162-PR', '242.912.185-91', NULL, NULL, true, NULL, 4, NULL, NULL, NULL, NULL),
(1247, 'LILIANA FERREIRA MENDES DE MORAIS', 'LILIANA', 'Faz. Lagoinha - Rod. BR 369 Km 17 a 18', NULL, NULL, NULL, 'Sao Francisco de Paula', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '718.671.476-53', '001.549.691-0030', true, 7, 2, NULL, NULL, NULL, NULL),
(1831, 'LILIANE PEREIRA COSTA NAKAO', 'LILIANE PEREIRA COSTA NAKAO', 'Fazenda Catanduva', NULL, NULL, NULL, 'Presidente Olegário', NULL, 'MG', '38700-999', '(34) 99916-6663', '(34) 3821-8556', NULL, NULL, 'adm@3mcnakao.com', 'marie3mc@hotmail.com', 'F', 'CL', 'VE', 'NASCIMENTO: 23/03/1975
nakaocoffee@hotmail.com', 'CONTATO: PAULINHO', '14.171.638-1', '776.412.136-34', '004789198-0055', true, 2, 2, NULL, NULL, NULL, NULL),
(911, 'LINCOLN FERREIRA', 'LINCON', 'FAZENDA SANTO ANDRE', NULL, NULL, NULL, 'PRATINHA', 'PRATINHA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'PLENO', NULL, '017.698.716-91', '37994039', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1568, 'LINDALVA DE OLIVEIRA DUTRA VIVENZA', 'LINDALVA DE OLIVEIRA DUTRA VIVENZA', 'FAZ. AGROP. CONESOL - ESTRADA DE TERRA', '8 km', 'a esquerda', NULL, 'Campos Altos', NULL, 'MG', '38970-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'paolo@vivenzacaffe.com.br', 'RHAPHAEL / EDISOM', NULL, '372.306.036-68', '001154649-0078', true, 2, 2, NULL, NULL, NULL, NULL),
(334, 'LINDOLPHO DE CARVALHO DIAS', NULL, 'FAZ. CACHOEIRA', NULL, NULL, NULL, 'S.S. DA GRAMA', 'S.S. DA GRAMA', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CRISTIANO OTTONI', NULL, '03.017.287-04', '065503967/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(147, 'LJM - COMÉRCIO EXP. E IMP. DE CAFÉ LTDA', NULL, 'ESTR. MUNIC. GRAMINEA/ANDRADAS', 'KM 1', NULL, NULL, 'ANDRADAS', 'ANDRADAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: CORRET. JAIR', '42.863.126/0001-30', NULL, '026.812.135.0022', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1709, 'Louis Dreyfus Company, Colombia', 'Louis Dreyfus Company, Colombia', 'Carrera 7 #71-52 Tower A', NULL, NULL, NULL, 'Bogotá - Colombia', NULL, NULL, NULL, '+57 7455300', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', 'Mrs. Johanna Fandiño', 'Louis Dreyfus Company, Colombia
Mrs. Johanna Fandiño
Carrera 7 #71-52 Tower A
Bogota
+57 7455300

LOUIS DREYFUS : 
Contact : Mrs. Johanna Fandiño 
Address : Carrera 7 # 71-52 Tower A Bogota  
Phone : +57.7455300
Email: johanna.fandino@ldc.com', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(405, 'LOURIVALDO TEODORO JÚNIOR', NULL, 'FAZ. SANTA FÉ - GAMELEIRA', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '461.125.376-72', '564/0320', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1744, 'LUCAS PARRA LOMAZ', 'LUCAS PARRA LOMAZ', 'Faz. Montividio', NULL, NULL, NULL, 'Tapitai', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '111.457.156-30', '002.363.744-0024', true, 2, 2, NULL, NULL, NULL, NULL),
(1435, 'LUCCA VILLACA MACHADO VELOSO', 'LUCCA VILLACA MACHADO VELOSO', 'Faz. Nova Suiça -  BR 354 KM 278', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', '38840-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '068.552.036-63', '00225279200-55', true, 2, 2, NULL, NULL, NULL, NULL),
(244, 'LUCIANA MARTINEZ GROSSI', 'LUCIANA', 'FAZENDA LUCIANA', NULL, NULL, NULL, 'PATROCINIO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CONTATO: GROSSI', NULL, '966.733.626-33', '001.264.402.02-47', true, NULL, 2, NULL, NULL, NULL, NULL),
(817, 'LUCIANA MYAKI MARRA', 'MARRA', 'FAZENDA SÃO JOSE', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '049.718.786-88', '481/1822', true, NULL, NULL, NULL, NULL, NULL, NULL),
(548, 'LUCIANO RODRIGUES BRANQUINHO E OUTRO', NULL, 'FAZENDA OLHOS D''AGUA', NULL, NULL, NULL, 'BONF. DE MINAS', 'BONF. DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CIDADE: BONFINÓPOLIS DE MINAS GERAIS', NULL, '967.046.406.49', '082/1720', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1397, 'LUCIO GONDIM VELLOSO E OUTRO', 'LUCIO', 'Faz. Fradiques', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '050.010.626-67', '0011254520023', true, 2, 2, NULL, NULL, NULL, NULL),
(600, 'LUIS BRAZ  E OUTROS', NULL, 'FAZ. SERRA NEGRA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '090.207.489-04', '481/3044', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1458, 'LUIZ ANTONIO TONIN', 'LUIZ ANTONIO TONIN', 'Fazenda Paraiso', NULL, NULL, NULL, 'Alfenas', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '237.453.986-53', '001.216.982-0400', true, 2, 2, NULL, NULL, NULL, NULL),
(1459, 'LUIZ ANTONIO TONIN', 'LUIZ ANTONIO TONIN', 'Fazenda Sao Domingos', NULL, NULL, NULL, 'Sao Sebastiao do Paraiso', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '237.453.986-53', '001.216.982-0248', true, 2, 2, NULL, NULL, NULL, NULL),
(1522, 'LUIZ ANTONIO TONIN', 'LUIZ ANTONIO TONIN', 'Fazenda Horizonte', NULL, NULL, NULL, 'Sao Sebastiao do Paraiso', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '237.453.986-53', '001.216.982-0086', true, 2, 2, NULL, NULL, NULL, NULL),
(1523, 'LUIZ ANTONIO TONIN', 'LUIZ ANTONIO TONIN', 'Fazenda Santa Clara', NULL, NULL, NULL, 'Itamogi', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '237.453.986-53', '001.216.982-0167', true, 2, 2, NULL, NULL, NULL, NULL),
(316, 'LUIZ AUGUSTO PEREIRA MONGVILOD', NULL, 'FAZ.  SÃO RAFAEL', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '158.618.098-36', '431/2185', true, NULL, NULL, NULL, NULL, NULL, NULL),
(422, 'LUIZ CARLOS MEROTTI CORTEZ', NULL, 'FAZ. ESTÂNCIA SÃO JORGE', NULL, NULL, NULL, 'ROMARIA', 'ROMARIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '280.324.979-00', '564/0316', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1411, 'Luiz Claudio Queiroz Marques da Cruz e outros', 'Luiz Claudio Queiroz Marques da Cruz e outros', 'Faz. Boa Esperança', NULL, NULL, NULL, 'Pratinha', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '376.341.351-00', '00177812300-94', true, 2, 2, NULL, NULL, NULL, NULL);
