-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(144, 'YASUO MAMOSE', 'FAZENDA PASTÃO 1', 'FAZENDA PASTÃO 1', NULL, NULL, NULL, 'MONTE CARMELO', NULL, 'MG', NULL, '(34) 8422272', NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', 'DATA DE NASC: 25/10/1941', 'CONTATO: LAG', '011.957.439-04', NULL, '00125394.0019', true, NULL, 2, NULL, NULL, NULL, NULL),
(148, 'YASUO MAMOSE', 'FAZ. COCAIS', 'FAZENDA COCAIS', NULL, NULL, NULL, 'IRAI DE MINAS', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'DATA DE NASC. 25/10/1941', 'CONTATO: AMOCA', '011.957.439-04', NULL, '00125394.02-72', true, NULL, 2, NULL, NULL, NULL, NULL),
(1400, 'YASUO MAMOSE', 'FAZ. SANTA BARBARA', 'FAZENDA SANTA BARBARA', NULL, NULL, NULL, 'Monte Carmelo', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '01..957.439-04', '001252394-0353', true, 2, 2, NULL, NULL, NULL, NULL),
(1169, 'YOLANDA MARQUES CARVALHO DIAS', 'YOLANDA', 'Faz. Mariana', NULL, NULL, NULL, 'Patos de Minas', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '038.531.076-56', '001320064-0081', true, 7, 2, NULL, NULL, NULL, NULL),
(1268, 'YOLANDA MARQUES CARVALHO DIAS', 'YOLANDA', 'Faz. Fortaleza', NULL, NULL, NULL, 'Patos de Minas', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '038.531.076-56', '001320064-0243', true, 2, 2, NULL, NULL, NULL, NULL),
(426, 'ZABULON AFONSO DOS SANTOS', NULL, 'FAZ. LAGOA DOS ESTUFANOS', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ISMAEL', NULL, '498.511.956-34', '143/2606', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1325, 'ZABULON AFONSO DOS SANTOS', NULL, 'FAZENDA LAGOS DOS ESTULANOS', NULL, NULL, NULL, 'CARMO DO PARANAIBA', 'BRAZIL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, '498.511.956-34', NULL, '001.299.531-0035', true, 9, 2, NULL, NULL, NULL, NULL),
(570, 'ZAQUEU CHAGAS', 'ZAQUEU CHAGAS', 'FAZ. ESMERIL-VARGEM', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '144.631.056-68', '481/24292', true, NULL, NULL, NULL, NULL, NULL, NULL);
