-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(932, 'PEDRO RIVELLINI', 'RIVELLINI', 'FAZENDA RECANTO', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '389.426.669-49', '481/5654', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1259, 'PIONEIRA SAFRAS COMERCIO DE CAFE LTDA', 'PIONEIRAS', 'Avenida Brasil', '392', 'Jd. Sao Luis', NULL, 'Santana do Parnaiba', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '13.307.281/0001-71', NULL, '623.031.032.111', true, 2, 2, NULL, NULL, NULL, NULL),
(70, 'PLAZA COMERCIO DE CAFE LTDA', NULL, 'AV. MELO VIANA', '560', NULL, 'BAIXADA', 'MANHUACU', 'MANHUACU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '00.642.276/0001-72', NULL, '394.947.226.0018', true, NULL, NULL, NULL, NULL, NULL, NULL),
(960, 'PORTAL CAFÉ COMERCIO E EXPORTAÇÃO DE CAFÉ LTDA', 'PORTAL', 'AV. VENEZUELA', '3053', NULL, NULL, NULL, NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'ACAIA', '10.780.036/0001-99', NULL, '001.141.627-0094', true, NULL, NULL, NULL, NULL, NULL, NULL),
(901, 'PORTO SEGURO COMERCIAL E EXPORTADORA DE CAFE', 'PORTO', 'RUA PRESIDENTE JOSE PAIVA', '61', 'SALA 02', NULL, 'VARGINHA', 'VARGINHA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'ACAIA', '01.970.960/0001.47', NULL, '707.696.752-0017', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1179, 'Pratapereira Comércio Import. e Exp. de Café Ltda.', 'Pratapereira', 'Alameda do Café, 805', 'Sl. 02', NULL, 'Jardim Andere,', 'Varginha', NULL, 'MG', '37026-400', '035 32199050', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'Endereço antigo:
Av. dos Imigrantes
Av. dos Imigrantes, 1340 - Sl. 02
Cidade Nova, Varginha/MG - Brasil


Dados p/ NF:

Pratapereira Com. Imp. E Exp. de Café LTDA 
Alameda do Café, 805 - Sl. 02- Jardim Andere,  Varginha-MG
Tel.: (35) 3219-9050      CEP: 37.026-400
CNPJ: 00.544.628/0001-58        I. E.: 707.925.805.0003', '00.544.628/0001-58', NULL, '707.925.805.00-03', true, 7, 2, NULL, NULL, NULL, NULL),
(658, 'PRODUTORES - VIDE OBSERVAÇÃO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(829, 'PRONOVA-COOP. DOS CAFEIC DAS MONTANHAS DO ESP. STO', 'PRONOVA', 'ROD. PEDRO COLA KM 01', NULL, NULL, NULL, 'VENDA NOVA DOS IMIGRANTES', 'VENDA NOVA DOS IMIGRANTES', 'ES', NULL, '28-3546-1069', NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, NULL, '06.894.506/0001-78', NULL, '082.280.36-3', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1083, 'Qualy Marcas Comércio e Exportação de CereaisLtda.', 'Qualy', 'Avenida Francisco Machado,', '555', 'Sala 01', NULL, 'Piumhi', 'Brasil', 'MG', '37925-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'João Marcos


Atualizar dados na nota fiscal:

QUALY MARCAS COMERCIO E EXPORTAÇÃO DE CEREAIS LTDA.
AV. QUEROBINO MOURÃO FILHO, 643  Galpão B  - BELA VISTA -
 PIUMHI/MG - CEP: 37.925-000
IE E CNPJ MANTÉM OS MESMOS.

Colocar ref. da qualy na NFiscal', '23.591.589/0001-45', NULL, '515.078.079.0094', true, NULL, 4, NULL, NULL, NULL, NULL),
(1665, 'Racafe & CIA. S.C.A.', 'Racafe & CIA. S.C.A.', 'Carrera 11 # 82-01 Floor 5', NULL, NULL, NULL, 'Bogotá - Colombia', NULL, NULL, NULL, '(571) 611 8700', NULL, '(571) 651 5781', NULL, NULL, NULL, 'J', 'CL', 'VE', 'Mrs. Sonia Llanos', 'RACAFE & CIA SAS : Contact Mrs Sonia Llanos
Phone : +57.6118700
Address : Carrera 11 # 82-01 Floor 5 
Email : sllanos@racafe.com / trade@racafe.com', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(1659, 'RAFAEL ELIAS PEREIRA', 'RAFAEL ELIAS PEREIRA', 'Fazenda Santa Barbara das Guaritas', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '199.571.736-34', '001328900-0052', true, 2, 2, NULL, NULL, NULL, NULL),
(794, 'RAGE ESSEF MATUCK', 'RAGE', 'FAZ. SANTA ROSA', NULL, NULL, NULL, 'SOLEDADE DE MINAS', 'SOLEDADE DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '041.460.857-72', '678/0535', true, NULL, NULL, NULL, NULL, NULL, NULL),
(406, 'RAMON OLINI ROCHA', NULL, 'FAZ. ALTÔNIA', NULL, NULL, NULL, 'ARAGUARI', 'ARAGUARI', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '593.094.749-04', '035/5157', true, NULL, NULL, NULL, NULL, NULL, NULL),
(371, 'RC MOREIRA DA SILVA', NULL, 'RUA MARIA ALEXANDRINA', '40', NULL, 'ENGENHO DA SERRA', 'MANHUAÇU', 'MANHUAÇU', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO: ODEBRECHT', '02.153.646/0001-34', NULL, '394.883.709-0027', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1439, 'REDUTO COM.CAFÉ IMP.EXP.LTDA.', 'REDUTO COM.CAFÉ IMP.EXP.LTDA.', 'Rod. Andradas a Esp. Sto do Pinhall', NULL, NULL, NULL, 'Andradas', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, '14.197.369/0001-40', NULL, '001.829.756-0058', true, 2, 2, NULL, NULL, NULL, NULL),
(53, 'REFINADORA DE OLEOS BRASIL LTDA', NULL, 'AV. JOSÉ RIBEIRO TRISTÃO', 'KM 1', NULL, NULL, 'VARGINHA', 'VARGINHA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'VE', 'VE', NULL, 'CONTATO:', '61.079.935/0023-05', NULL, '707.827.301.0091', true, NULL, NULL, NULL, NULL, NULL, NULL),
(425, 'REGINA HELENA M.P. DE CARVALHO DIAS ESPOLIO', NULL, 'FAZ. RAINHA', NULL, NULL, NULL, 'SÃO SEBASTIÃO D', 'SÃO SEBASTIÃO D', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: CRISTIANO', NULL, '222.977.268-64', '0655.0392.0/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(924, 'REGINALDO LEANDRO MOREIRA SOUZA', 'LEANDRO', 'FAZ. OLHOS D''AGUA', NULL, NULL, NULL, 'RIO PARANAIBA', 'RIO PARANAIBA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'COOCACER - ZE REINALDO', NULL, '049.332.706-19', '555/3476', true, NULL, NULL, NULL, NULL, NULL, NULL),
(512, 'REINALDO CASEIRO - COOCACER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1482, 'Reinaldo Olini Rocha', 'Reinaldo Olini Rocha', 'Fazenda São Matheus', NULL, NULL, NULL, 'Ibiá', NULL, 'MG', '38950-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'data de nascimento: 12/07/1966', NULL, NULL, '555.320.639-15', '118435400-88', true, 2, 2, NULL, NULL, NULL, NULL),
(1483, 'Reinaldo Olini Rocha', 'Reinaldo Olini Rocha', 'Fazenda Malhada', NULL, NULL, NULL, 'Ibia', NULL, 'MG', '38950000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'data de nascimento: 12/07/1966', NULL, NULL, '555.320.639-15', '001184354.0320', true, 2, 2, NULL, NULL, NULL, NULL),
(1549, 'Reinaldo Olini Rocha', 'Reinaldo Olini Rocha', 'FAZ. GALICIA', NULL, NULL, NULL, 'Perdizes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'REINALDO.OLINI@ACAUAS.COM.BR', 'F', 'CL', 'VE', 'data de nascimento: 12/07/1966', 'CPF.: 555.320.639-15

Rodovia BR 262 KM 678 A DIREITA
Número: S/N
Complemento: CAIXA POSTAL 507
Bairro/Distrito: INDUSTRIAL
Município: Araxá UF: MG
CEP: 38183-971', NULL, '555.320.639-15', '0011843640169', true, 7, 2, NULL, NULL, NULL, NULL),
(1603, 'REINALDO OLINI ROCHA', 'REINALDO - FAZ. MACAUBAS', 'Fazenda Macaubas', NULL, NULL, NULL, 'Araguari', NULL, 'MG', '38449-999', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', 'data de nascimento: 12/07/1966', NULL, NULL, '555.320.639-15', '001184354-0576', true, 2, 2, NULL, NULL, NULL, NULL),
(58, 'RENATO ALVES NOGUEIRA', 'RENATO', 'AV. CESARIO ALVIM', '234F', NULL, NULL, 'CARATINGA', NULL, 'MG', '35.300-036', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'Renato Alves Nogueira

Data de nascimento: 25/07/1965

Endereço da fazenda : Córrego do Bertoldo, BR 116 Km 522 nº 1.095 Bairro das Graças 
Caratinga MG

CEI : 111 340 000 780', NULL, '812.697.736-15', '001228250.00-67', true, NULL, 2, NULL, NULL, NULL, NULL),
(1701, 'RENATO CAETANO DOMINGOS', 'RENATO CAETANO DOMINGOS', 'Faz Mutuca', NULL, NULL, NULL, 'Campos Altos', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'NILSON', NULL, '032.769.386-00', '001.552.442-0054', true, 2, 2, NULL, NULL, NULL, NULL),
(430, 'RENI PAULO ALBERTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(743, 'RICARDO DAUNT DE CAMPOS SALLES', 'RICARDO', 'FAZENDA SÃO JOAQUIM - ESTRADA DO CATINGUEIRO', NULL, NULL, NULL, 'ESPÍRITO SANTO DO PINHAL', 'ESPÍRITO SANTO DO PINHAL', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'QUALICAFEX', NULL, '578.955.628.00', '053001039/000', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1651, 'RICARDO DE ALMEIDA BARCELOS', 'RICARDO DE ALMEIDA BARCELOS', 'Faz. Agua Limpa', NULL, NULL, NULL, 'Carmo do Paranaiba', NULL, 'MG', NULL, NULL, NULL, NULL, '3499643296', NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, 'MG-528559', '939.761.866-00', '0014366190427', true, 2, 2, NULL, NULL, NULL, NULL),
(1488, 'RICARDO FERREIRA SANTOS', 'RICARDO FERREIRA SANTOS', 'Fazenda Bela Vista', 's/n', NULL, 'Zona Rural', 'Carmo do Rio Claro', NULL, 'MG', '37150-000', NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, NULL, '043.533.228-77', '002.088513-0057', true, 2, 2, NULL, NULL, NULL, NULL),
(522, 'RICARDO IGINOTT - CHAPADÃO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(111, 'RICARDO SANTOS', 'RICARDO SANTOS', 'CORREGO DAS ROSAS', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '070.996.816-72', '134/3869', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1633, 'RIO RANCHO AGROPECUÁRIA LTDA', 'RIO RANCHO AGROPECUÁRIA LTDA', 'Fazenda Santa Rosa', NULL, NULL, NULL, 'Santa Rosa da Serra', NULL, 'MG', '38.805-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, 'CONTATO: NILSON


2) Endereço de Cobrança: Av. Professor Mário Werneck, 2501 - sala 303, Bairro Buritis, CEP: 30.575-180 em Belo Horizonte/MG, Brasil', '22.619.217/0004-60', NULL, '278.094999-1530', true, 2, 2, NULL, NULL, NULL, NULL),
(212, 'ROBERTO CARLOS DE CARVALHO E OUTROS', NULL, 'FAZ. CAPÃO GRANDE', NULL, NULL, NULL, 'PATOS DE MINAS', 'PATOS DE MINAS', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: ANDRADE BROS', NULL, '019.767.788-67', '480/5013', true, NULL, NULL, NULL, NULL, NULL, NULL),
(824, 'ROBERTO TERUKAZU NAKAMURA', 'NAKAMURA', 'FAZ. KATHIJARA - ROD. SERRA DO SALITRE/ARAXA KM 52', NULL, NULL, NULL, 'SERRA DO SALITRE', 'SERRA DO SALITRE', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ACAIA', NULL, '329.031.039-67', '667/1194', true, NULL, NULL, NULL, NULL, NULL, NULL),
(415, 'ROBINSON LEITE DE MATOS', NULL, 'FAZ. MARICÁ', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '011.979.086-68', '134/1593', true, NULL, NULL, NULL, NULL, NULL, NULL),
(416, 'ROBINSON LEITE DE MATOS JÚNIOR', NULL, 'FAZ. CAPARAÓ', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '461.802.307-49', '134/3879', true, NULL, NULL, NULL, NULL, NULL, NULL),
(414, 'ROBINSON LEITE DE MATOS JÚNIOR', NULL, 'FAZ. BURITI', NULL, NULL, NULL, 'CARATINGA', 'CARATINGA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO:', NULL, '461.802.307-49', '134/1589', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1785, 'RODRIGO DE FREITAS SILVA', 'RODRIGO DE FREITAS SILVA', 'Sitio Santa Rita', NULL, NULL, NULL, 'Jeriquaqura', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, NULL, '08.501.545/0002-74', NULL, '402.055.180.114', true, 2, 2, NULL, NULL, NULL, NULL),
(1658, 'RODRIGO GUIMARÃES BERNARDES', 'RODRIGO GUIMARÃES BERNARDES', 'Fazenda Nossa Senhora dos Remedios', NULL, NULL, NULL, 'Serra do Salitre', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'VANDUIR', NULL, '029.505.496-40', '001413818.01-33', true, 2, 2, NULL, NULL, NULL, NULL),
(1653, 'ROGERIO RIBEIRO ARAUJO', 'ROGERIO RIBEIRO ARAUJO', 'Fazenda Paraiso', NULL, NULL, NULL, 'Ibiá', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'ACAUA', NULL, '072.778.486-24', '001230111-0222', true, 2, 2, NULL, NULL, NULL, NULL),
(393, 'ROMEU FERREIRA DE QUEIROZ', NULL, 'FAZ. SUCURI ARAUJOS', NULL, NULL, NULL, 'COROMANDEL', 'COROMANDEL', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: EDMILSON', NULL, '081.608.996-53', '193/2256', true, NULL, NULL, NULL, NULL, NULL, NULL),
(401, 'ROMEU LANGONI PENA', 'ROMEU', 'FAZENDA IGREJINHA', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '477333066-04', '431/1157', true, NULL, NULL, NULL, NULL, NULL, NULL),
(271, 'ROMEU MUNDIM PENA', NULL, 'FAZENDA ARARAS', NULL, NULL, NULL, 'MONTE CARMELO', 'MONTE CARMELO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: AMOCA', NULL, '039.758.276-53', '431/0130', true, NULL, NULL, NULL, NULL, NULL, NULL),
(372, 'ROMIS ANTONIO DOS SANTOS', NULL, 'FAZ. FRADIQUES', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: QUENIO', NULL, '393.901.876-72', '143/1447', true, NULL, NULL, NULL, NULL, NULL, NULL),
(671, 'ROMULO JOSE CARNEIRO MENDONÇA E OUTROS', 'ROMULO', 'FAZ. SÃO BENTO', NULL, NULL, NULL, 'CARMO DO PARANAIBA', 'CARMO DO PARANAIBA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'ASSOCAFE', NULL, '431.576.376-49', '143/2075', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1348, 'RONAN MARIANO DE ANDRADE', 'RONAN MARIANO DE ANDRADE', 'FAZENDA PARAISO', NULL, NULL, NULL, 'Campos Alto', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CL', 'VE', NULL, 'CONTATO: NILSON', NULL, '57073368691', '0013688000080', true, 2, 2, NULL, NULL, NULL, NULL),
(637, 'ROSANGELA TURGATTI TORATTI E OUTROS', NULL, 'FAZ. KATIARA', NULL, NULL, NULL, 'PATROCINIO', 'PATROCINIO', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, NULL, NULL, '016.836.228-71', '481/2140', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1225, 'RRPJ Cafe Assessoria e Representacao Ltda', NULL, NULL, NULL, NULL, NULL, 'SANTOS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'RE', 'VE', NULL, NULL, NULL, NULL, NULL, true, 2, 2, NULL, NULL, NULL, NULL),
(1235, 'RRPJ Café Assessoria e Representação Ltda', 'RRPJCafé', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'VE', NULL, NULL, NULL, NULL, NULL, true, 16, 16, NULL, NULL, NULL, NULL),
(375, 'RUBENS ANTONIO DOS SANTOS', NULL, 'FAZ. FRADIQUES', NULL, NULL, NULL, 'CARMO DO PARANA', 'CARMO DO PARANA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'VE', 'VE', NULL, 'CONTATO: QUENIO', NULL, '302.191.086-68', '143/1447', true, NULL, NULL, NULL, NULL, NULL, NULL);
