-- Bulk import of all remaining legacy clients
INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES
(1442, 'Coffee People OÜ', 'Coffee People OÜ', 'Sära tee 9,', NULL, '75312 - Peetri', NULL, 'Järvamaa, Estonia', NULL, NULL, NULL, '372 5340 9454', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'Mr. Annar Alas - annar@coffeepeople.ee
Mrs. Heili Politanov - heili@gourmetcoffee.ee', NULL, NULL, NULL, true, 7, 7, NULL, NULL, NULL, NULL),
(997, 'COFFEE TRADE CORPORATION S.R.L', 'COFFEE TRADE', 'VIA CESARE FEDERICI, 1PALAZZO DEI DEPUTATI 00147 -', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '00 39 6 5132443', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COFFEE TRADE CORPORATION S.R.L
COFFEE TRADE
ENRICO ROMANO', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1000, 'COFFEXPORT S.A.', 'COFFEXPORT', 'GENERAAL LEMANSTRAAT', '74', 'BUS 112600', NULL, 'ANTWERP - BE', NULL, NULL, NULL, '0032 3 2816016', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COFFEXPORT S.A.
COFFEXPORT
COFFEE DEPARTMENT', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1002, 'COFIROASTERS S.A.', 'COFIROASTERS', 'RUE DU RHÔNECH- GENEVESWITZERLAND', '67', '1207', NULL, 'GENEVE - SWITZERLAND', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', 'GOTTHARD BANK

1, AVENUE DU THEATRECH-1002 - LAUSANNESWITZERLANDATT.: MR. KATZ', NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(651, 'COIMEX TRADING COMPANY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(1014, 'Colonial International Coffee', 'Colonial', '3250 NW 60th St.', NULL, NULL, NULL, 'Miami / Florida', 'USA', NULL, 'Fl 33142', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(348, 'COM. IND. BRANCO PERES DE CAFÉ LTDA', NULL, 'RUA FREI GASPAR', '25', NULL, 'CENTRO', 'SANTOS', 'SANTOS', 'SP', NULL, '32195656', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '43.008.036/0009-81', NULL, '633.248.140.114', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1106, 'COMCAFÉ - COMERCIAL COQUEIRAL DE CAFÉ CER. E SAC.', 'COMCAFE', 'Rua Coronel João Borges', NULL, NULL, 'centro', 'Coqueiral', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '11.351.719/0001-93', NULL, '001.504.631-002', true, NULL, NULL, NULL, NULL, NULL, NULL),
(454, 'COMERCIAL AGRICOLA CARVALHO LTDA', 'CARVALHO', 'AV. SALVADOR SABINO', '37', 'SALA 2', NULL, 'MATIPÓ', 'MATIPÓ', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: ZE GERALDO', '01.755.600/0001-22', NULL, '409.008.213.0085', true, NULL, NULL, NULL, NULL, NULL, NULL),
(410, 'COMERCIAL AGRÍCOLA CARVALHO LTDA', 'CARVALHO', 'AV. SALVADOR SABINO', '37', 'SALA 4', NULL, 'MATIPÓ', 'MATIPÓ', 'MG', NULL, '(35) 32142011', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: ZÉ GERALDO', '01.755.600/0001-22', NULL, '409.008.213.0085', true, NULL, NULL, NULL, NULL, NULL, NULL),
(735, 'COMERCIAL DE CAFÉ ARÁBICA LTDA', 'ARABICA', 'RUA XV DE NOVEMBRO', '5/40', NULL, NULL, 'BAURU', 'BAURU', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '05.006.672/0001-28', NULL, '209.327.500.113', true, NULL, NULL, NULL, NULL, NULL, NULL),
(241, 'COMERCIAL DE CAFÉ E CEREAIS N R LTDA', NULL, 'ROD. SP 215', 'KM 34,1', NULL, NULL, 'VARGEM GRANDE D', 'VARGEM GRANDE D', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: LUCIANO', '57.934.366/0009-02', NULL, '711.024.765.119', false, NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'COMERCIAL DE CAFE E CEREAIS NR  LTDA', NULL, 'RUA JOSEFINA SARNENTO', '395', '2° ANDAR SALA 2', 'CENTRO', 'CAMPINAS', 'CAMPINAS', 'SP', NULL, '(19) 6511570', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: LUCIANO', '57.934.366/0008-21', NULL, '530.031.033.117', false, NULL, NULL, NULL, NULL, NULL, NULL),
(186, 'COMERCIAL DE CAFÉ E CEREAIS NR LTDA', NULL, 'AV. OLIVEIRA MOTTA', '87', NULL, NULL, 'ESP. SANTO DO P', 'ESP. SANTO DO P', 'SP', NULL, '(19) 6151570', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: LUCIANO', '57.934.366/0001-55', NULL, '530.019.988.116', false, NULL, NULL, NULL, NULL, NULL, NULL),
(267, 'COMERCIAL DE CAFÉ E CEREAIS NR LTDA', NULL, 'ESTRADA ALBERTINA PINHAL', 'KM 1', 'SALA 2', NULL, 'ALBERTINA', 'ALBERTINA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '57.934.366/0003-17', NULL, '014.826.065.0098', false, NULL, NULL, NULL, NULL, NULL, NULL),
(1381, 'COMERCIAL EXPORTADORA DE CAFÉ NOVA GARÇA EIRELI', 'COMERCIAL EXPORTADORA DE CAFÉ NOVA GARÇA EIRELI', 'Avenida Rafael Paes de Barros', '266', NULL, 'Willians', 'Garça', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '18.214.140/0001-28', NULL, '315.041.173.114', true, 2, 2, NULL, NULL, NULL, NULL),
(1312, 'COMERCIAL INDUSTRIAL BRANCO PERES DE CAFÉ LTDA', 'COMERCIAL INDUSTRIAL BRANCO PERES DE CAFÉ LTDA', 'AV. RIO BRANCO', '1108', NULL, NULL, 'ADAMANTINA', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '43.008.036/0008-09', NULL, '150.005.080.115', true, 16, 2, NULL, NULL, NULL, NULL),
(320, 'COMERCIO E IND. BRASILEIRAS COINBRA S/A', 'COINBRA', 'RUA DO COMÉRCIO', '18/20', NULL, NULL, 'SANTOS', 'SANTOS', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO: ALMEIDA






















PAGTO MENCIONAR CNPJ: 47.067.525/0001-08', '47.067.525/0006-12', NULL, '633.011.540.113', true, NULL, NULL, NULL, NULL, NULL, NULL),
(318, 'COMERCIO E IND. BRASILEIRAS COINBRA S/A', 'COINBRA', 'ROD. BR 491 KM 233', 'S/N', NULL, NULL, 'VARGINHA', 'VARGINHA', 'MG', NULL, '(35) 2142295', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:






















CNPJ: 47.067.525/0001-08', '47.067.525/0075-44', NULL, '707.621.265.0536', true, NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'COMERCIO E IND. BRASILEIRAS COINBRA S/A', NULL, 'AV.ARTHUR BERNADES', '657', NULL, NULL, 'MACHADO', 'MACHADO', 'MG', '37.750-000', '(35) 2952874', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '47.067.525/0075-44', NULL, '390.621.265.0557', true, NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'COMERCIO E IND. BRASILEIRAS COINBRA S/A', NULL, 'RUA DOIS', '11', NULL, 'CRUZEIRO DA SERRA', 'PATROCINIO', 'PATROCINIO', 'MG', '38.740-000', '(34) 8313459', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '47.067.525/0041-03', NULL, '481.621.265.0220', true, NULL, NULL, NULL, NULL, NULL, NULL),
(47, 'COMEXIM LTDA', 'COMEXIM', 'ROD. MG 290', 'KM 54,3', NULL, 'CORREGO DA GRALHA', 'OURO FINO', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '58.150.087/0005-97', NULL, '460.223.984.0097', true, NULL, 2, NULL, NULL, NULL, NULL),
(1725, 'COMEXIM LTDA', 'COMEXIM LTDA', 'Av. Rio de Janeiro', '221', 'sala 33', NULL, 'Londrina', NULL, 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '58.150.087/0001-63', '902.10652-90', NULL, true, 2, 2, NULL, NULL, NULL, NULL),
(528, 'COMISSARIA EXP. E IMP. COMEXIM LTDA', 'COMEXIM', 'RUA REINALDO MASSI', '20', NULL, NULL, 'ROLÂNDIA', 'ROLÂNDIA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '58.150.007/0011-35', NULL, '902.106.52-90', true, NULL, NULL, NULL, NULL, NULL, NULL),
(581, 'COMISSARIA EXP. E IMP. COMEXIM LTDA', 'COMEXIM', 'ROD. BA 142 KM 48', '217', NULL, 'CENTRO', 'UTINGA', 'UTINGA', 'BA', '46.810-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '58.150.087/0010-54', NULL, '46.907.374-NO', true, NULL, NULL, NULL, NULL, NULL, NULL),
(742, 'COMISSÁRIA EXP. E IMP. COMEXIM LTDA', 'COMEXIM', 'AV. LUIZ PASTEUR', '480', NULL, NULL, 'LONDRINA', 'LONDRINA', 'PR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '58.150.087/0011-35', NULL, '902.106.52-90', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1029, 'COMPAGNIA MERIDIONALE CAFFE', 'CIA MERIDIONALE', 'ZONA INDUSTRIALE - 21A STRADA95100 - CATANIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COMPAGNIA MERIDIONALE CAFFE
CIA MERIDIONALE
COFFEE DEPARTMENT', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(692, 'COMPANHIA CACIQUE DE CAFE SOLUVEL', 'CACIQUE', 'RUA HORACIO SABINO COIMBRA', '100', NULL, NULL, 'LONDRINA', 'LONDRINA', 'PR', '86072-900', '3782000', NULL, '3782000', NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '78.588.415/0001-15', NULL, '6010250437', true, NULL, NULL, NULL, NULL, NULL, NULL),
(564, 'COMPANHIA CACIQUE DE CAFÉ SOLUVEL', 'CACIQUE', 'AV. FERNANDO C . C. COIMBRA', '100', NULL, NULL, 'BARUERI', 'BARUERI', 'SP', '06465-090', '(11) 41952511', NULL, '(11) 41914399', NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '78.588.415/0020-88', NULL, '206.011.780.113', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1032, 'COMPANIA MERCANTIL DEL CAFÉ S/A', 'CIA MERCANTIL', 'JALON 17 - 28220 MAJADAHONDA', NULL, NULL, NULL, 'MADRID', 'ESPANHA', NULL, NULL, '34 916362980', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COMPANIA MERCANTIL DEL CAFÉ S/A
COMPANIA MERCANTIL DEL CAFÉ S/A
RICARDO LASVIGNES', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'COMPEL - COMERCIAL PEQUI LTDA', NULL, 'AV. AIRTON BORGES DA SILVA', '1629', NULL, NULL, 'UBERLÂNDIA', 'UBERLÂNDIA', 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '20.163.978/0003-43', NULL, '702.449.137.0002', false, NULL, NULL, NULL, NULL, NULL, NULL),
(1052, 'Coop Norge Kaffe AS', 'Coop Norge', 'Filipstadveien 15', '0250', NULL, NULL, 'Oslo', NULL, NULL, NULL, '22 89 99 99', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(762, 'COOP. COFFEES', 'COOP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(483, 'COOP. DE SÃO MANOEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1195, 'COOP. REG. CAF. EM GUAXUPE', 'COOXUPE', 'Rod. BR 146', '100', 'Japy', NULL, 'Guaxupe', NULL, 'MG', '37800-000', NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '20.770.566/0086-07', NULL, '287.048.636.6863', true, 2, 2, NULL, NULL, NULL, NULL),
(82, 'COOP. REG. DE CAFEIC. EM GUAXUPE LTDA', NULL, 'RUA XV DE NOVEMBRO', '65', '6° ANDAR', 'CENTRO', 'SANTOS', 'SANTOS', 'SP', NULL, '2197469', NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '20.770.566/0011-81', NULL, '633.203.360.113', true, NULL, 4, NULL, NULL, NULL, NULL),
(484, 'COOPERNOVA - COOP AGROP. DA REGIÃO DA MANTIQUEIRA', 'COOPERNOVA', 'ROD. SP 344 SÃO JOÃO-AGUAI', 'KM 222,8', NULL, NULL, NULL, NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, '02.982.392/0002-48', NULL, '639.065.623.117', true, NULL, NULL, NULL, NULL, NULL, NULL),
(520, 'COOPERNOVA - COOP. AGROP. DA REGIÃO DA MANTIQUEIRA', NULL, 'ROD. SP 344 KM 222,8', NULL, NULL, NULL, 'SÃO JOÃO DA BOA', 'SÃO JOÃO DA BOA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CIDADE: SÃO JOÃO DA BOA VISTA', '02.982.392/0002-48', NULL, '639.065.623.117', true, NULL, NULL, NULL, NULL, NULL, NULL),
(1067, 'COPACABANA FOOD & BEVERAGE COR', 'COPACABANA', '2162 N.W. 82ND AVENUE, 33122USA', '82ND', NULL, NULL, 'MIAMI', 'USA', NULL, NULL, '(305) 463-8555', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COPACABANA FOOD & BEVERAGE CORP.
COPACABANA
RASMUS WOLTHERS', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1140, 'Copenhagen Roaster', 'Chokolade Compagniet', 'Brandstrupvej,10', NULL, NULL, 'DK-2610 - Rodovre,', NULL, 'Denmark', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'Shipping Instructions
 
Shipping Company: Wolthers shipping - Mr. Jansen - email shipping@wolthers.com.br 
Vessel:  (wolthers will inform you later)
Booking Number: (wolthers will inform you later)
Origin: Santos Port
Destination: COPENHAGEN
Modality: FCL/FCL
Consignee: Estate Coffee / Copenhagen Roaster A/S 
Notify: Estate Coffee / Copenhagen Roaster A/S 
          Gl. Køge Landevej 22, 2500 Valby, Denmark
          Contact person: Anne Marie Flyger - phone +45 38 11 12 11 - email Annemarie@chokolade-compagniet.dk
Freight: Collect
Special Bag Marks: Brasil Dulce
Docs Required: Phyto, Weight, Quality and ICO certificates are required (as informed on contract)

Docs to be sent thru: Paperwork to be send with DHL/FEDEX or TNT to Estate Coffee/Copenhagen Roster A/S,
Dr. Olgas Vej 30, 2000 Frederiksberg C. Denmark

Updated on August 15th, 2011.', NULL, NULL, NULL, true, 3, 7, NULL, NULL, NULL, NULL),
(1070, 'COPENHAGEN ROASTER  A/S', 'Estate Coffee', 'Gl. Køge Landevej 22 (building V) / 2500 Valby', NULL, NULL, NULL, 'Copenhagen', NULL, NULL, NULL, '45 38 11 12 80', NULL, '45 36 46 12 80', NULL, NULL, NULL, 'J', NULL, 'CO', NULL, 'Our bank: (message received on October 07th, 2008)

Vestfynsk bank
Østergade 42
5610 Assens  
Danmark

reg. Nr:  6851 
account Nr: 122515  
IBAN nr:  DK0868510000122515 
Swift:  VESBDK22  

www.estatecoffee.dk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(983, 'Copenhagen Roaster A/S (Chokolate)', 'Chokolate', 'Brandstrupvej, 10', NULL, NULL, NULL, 'Rodovre', 'Denmark', NULL, 'DK-2610', '45 38 11 12 11', NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'Shipping Instructions
 
Shipping Company: Wolthers shipping - Mr. Jansen - email shipping@wolthers.com.br 
Vessel:  (wolthers will inform you later)
Booking Number: (wolthers will inform you later)
Origin: Santos Port
Destination: COPENHAGEN
Modality: FCL/FCL
Consignee: Estate Coffee / Copenhagen Roaster A/S 
Notify: Estate Coffee / Copenhagen Roaster A/S 
          Gl. Køge Landevej 22, 2500 Valby, Denmark
          Contact person: Anne Marie Flyger - 
phone +45 38 11 12 11 - email Annemarie@chokolade-compagniet.dk
Freight: Collect
Special Bag Marks: Brasil Dulce
Docs Required: Phyto, Weight, Quality and ICO certificates are required (as informed on contract)

Docs to be sent thru: Paperwork to be send with DHL/FEDEX or TNT to Estate Coffee/Copenhagen Roster A/S,
Dr. Olgas Vej 30, 2000 Frederiksberg C. Denmark

Updated on August 15th, 2011.', NULL, NULL, NULL, true, NULL, 7, NULL, NULL, NULL, NULL),
(1071, 'COSCO - CAFIMPORT S.R.L.', 'COSCO', '16121 - GENOVA - ITALY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'COSCO - CAFIMPORT S.R.L.
COSCO
CARLOS DOMINGUES', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1336, 'Costa Café Comércio Exportação e Importação Ltda', 'Costa Café Comércio Exportação e Importação Ltda', 'Rod.SP.346 - Km.202 + 130 Mts - Sl.01', NULL, NULL, NULL, 'Esp. Santo do Pinhal', NULL, 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '54.122.775/0002-40', NULL, '530.014.050.110', true, 2, 2, NULL, NULL, NULL, NULL),
(1494, 'Costa Café Comércio Exportação e Importação Ltda', 'Costa Café Comércio Exportação e Importação Ltda', 'Estr. Albertina / Esp. Sto do Pinhal', 'Km 01', NULL, NULL, 'Albertina', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, NULL, '54.122.775/0004-01', NULL, '014.577.867-0174', true, 2, 2, NULL, NULL, NULL, NULL),
(83, 'COSTA RIBEIRO EXP. E IMP. LTDA', NULL, 'ROD. SP 342', 'KM 204', 'SALA 3', NULL, 'ESP. SANTO DO P', 'ESP. SANTO DO P', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, 'CONTATO:', '53.446.332/0001-60', NULL, '530.013.407.118', true, NULL, NULL, NULL, NULL, NULL, NULL),
(485, 'COTIA TRADING S/A', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL),
(1086, 'CTM - Altromercato', 'Altromercato', 'Via Macello', '18', '39100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'A partir de Jan/06:

CTM Altromercato Soc. Coop. 
Via Crispi, 9 
39100 Bolzano (BZ) 
ITALIA', NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL, NULL),
(1881, 'CULTUR COMERCIAL DE GRÃOS LTDA', 'CULTUR COMERCIAL DE GRÃOS LTDA', 'Av. Celina Ferreira Ottoni', '518', 'loa 3', NULL, 'Varginha', NULL, 'MG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J', 'CL', 'CO', NULL, 'PAULINHO - P & G', '22.010.233/0002-99', NULL, '37401540070', true, 2, 2, NULL, NULL, NULL, NULL),
(486, 'CUSTÓDIO FORZZA', 'CUSTÓDIO FORZZA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'CO', 'CO', NULL, NULL, NULL, NULL, NULL, false, NULL, 7, NULL, NULL, NULL, NULL);
