BEGIN;

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1742,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FLORIANA I',
    NULL,
    NULL,
    NULL,
    NULL,
    7,
    7,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1860,
    'A & C - Corretores de Mercadorias e Futuro Ltda.',
    'A & C - Corretores de Mercadorias',
    NULL,
    NULL,
    NULL,
    NULL,
    'Tres Pontas',
    'Brasil',
    'MG',
    NULL,
    '(35)3266-5148',
    '(35)98878-5160',
    '(35)98804-3776',
    '(35)98876-2120',
    'aeccorretores@outlook.com',
    NULL,
    'J',
    'RE',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1567,
    'AAFAPO - Associação dos Agricultores Familiares da Pontinha e Região',
    'AAFAPO',
    'Rua da Fabrica, 163',
    '163',
    NULL,
    'Centro',
    'Paraguaçu',
    'Brazil',
    'MG',
    '37.120-00',
    '(35)3637-0632',
    NULL,
    NULL,
    '(35)98446-6909',
    'edcafeicultura2014@gmail.com',
    NULL,
    'J',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1781,
    'Agro Forte',
    'Agro Forte',
    'Rua Manoel Madeira',
    '67 B',
    NULL,
    'Ind. Reinaldo Foresti',
    'Varginha',
    'Brasil',
    'MG',
    '37026-560',
    '(35)3212-6334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'J',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1354,
    'Alexandra de Fátima Marques',
    'Alexandra de Fátima Marques',
    'Sitio Santa Adelaide',
    NULL,
    NULL,
    'Bairro dos Moreiras',
    'Ouro Fino',
    'Brazil',
    'MG',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'F',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1717,
    'ANTONIO VANDO SANT ANA',
    'LOTE 23 GLEBA 210 A PADAP',
    NULL,
    NULL,
    NULL,
    'ZONA RURAL',
    'SAO GOTARDO',
    NULL,
    'MG',
    '38800000',
    '34 3671-2612',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'F',
    NULL,
    NULL,
    NULL,
    NULL,
    '301.717.416-68',
    NULL,
    '001145049.00-26',
    true,
    9,
    2,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1564,
    'Arabica Mineiro - Comércio e Exp. de Café',
    'Arábica Mineiro',
    'Rua Frei Alfredo',
    '29',
    NULL,
    'Centro',
    'Monte Belo',
    'Brazil',
    'MG',
    NULL,
    '(35) 99235-6083',
    '(35) 9971571',
    NULL,
    '(35) 99958-7863',
    'arabicamineiro@hotmail.com',
    NULL,
    'J',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1221,
    'Beto Fued',
    'Beto Fued',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'F',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1246,
    'BR - Corretora',
    'BR - Corretora',
    'Rua XV de Novembro',
    '20',
    'Sala F',
    'Centro',
    'Santos',
    'Brazil',
    'SP',
    NULL,
    '(13) 9713-5056',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'J',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO public.legacy_clients (
    legacy_client_id, descricao, descricao_fantasia, endereco, numero, complemento,
    bairro, cidade, pais, uf, cep, telefone1, telefone2, telefone3, telefone4,
    email, email_contratos, pessoa, grupo1, grupo2, referencias, obs,
    documento1, documento2, documento3, ativo, id_usuario, id_usuario_ultimo,
    logo, logo_altura, logo_largura, auto_size
) VALUES (
    1223,
    'Brazil Coffee Cerealista Exp., Imp. e Comércio de Café',
    'Brazil Coffee Cerealista',
    'Rua Diogo Feijó',
    '1929',
    NULL,
    'Estação',
    'Franca',
    'Brasil',
    'SP',
    '14405-212',
    '(16) 3724-0044',
    NULL,
    NULL,
    NULL,
    'julianojapaulo@cerealista.net.br',
    NULL,
    'J',
    'CL',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    8,
    8,
    NULL,
    NULL,
    NULL,
    NULL
);

COMMIT;

-- Sample import of 10 records
